language: node_js
sudo: required  # See http://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
node_js:
  - "4"
python:
  - "2.7"
addons:
  hosts:
    - ads.localhost
    - iframe.localhost
    # Requested by some tests because they need a valid font host,
    # but should not resolve in tests.
    - fonts.googleapis.com
  apt:
    packages:
    - protobuf-compiler
    - python-protobuf
before_install:
  - export CHROME_BIN=google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
before_script:
  - pip install --user protobuf
  - gem install percy-cli
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "7257f80fb584"
  - COMMIT_AUTHOR_EMAIL: "d@dereklew.is"
cache:
  yarn: true
  directories:
  - node_modules
