(function(){var f;function h(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};var n=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function p(a){var b=Object.create(null);if(!a)return b;for(var c;c=n.exec(a);){var d=decodeURIComponent(c[1]).trim(),e=c[2]?decodeURIComponent(c[2]).trim():"";b[d]=e}return b};var q="";
function r(a){var b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;if(c.context&&c.context.mode)c=c.context.mode;else{var d=p(c.location.originalHash||c.location.hash),e=p(c.location.search);q||(q=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"01123456789");c={localDev:!1,development:!("1"!=d.development&&!c.AMP_DEV_MODE),examiner:"2"==d.development,filter:d.filter,minified:!0,lite:void 0!=e.amp_lite,test:!1,log:d.log,version:"123456789",rtvVersion:q}}c=b.AMP_MODE=c}return c}
;var v=Object.prototype.toString;var w=Date.now();function x(a,b,c){this.win=a;this.A=b;this.f=this.win.console&&this.win.console.log&&"0"!=r().log?this.A({localDev:!1,development:r(void 0).development,filter:r(void 0).filter,minified:!0,lite:r(void 0).lite,test:!1,log:r(void 0).log,version:r(void 0).version,rtvVersion:r(void 0).rtvVersion}):0;this.h=c||""}
function y(a,b,c,d){if(0!=a.f){var e=a.win.console.log;"ERROR"==c?e=a.win.console.error||e:"INFO"==c?e=a.win.console.info||e:"WARN"==c&&(e=a.win.console.warn||e);d.unshift(Date.now()-w,"["+b+"]");e.apply(a.win.console,d)}}f=x.prototype;f.isEnabled=function(){return 0!=this.f};f.fine=function(a,b){4<=this.f&&y(this,a,"FINE",Array.prototype.slice.call(arguments,1))};f.info=function(a,b){3<=this.f&&y(this,a,"INFO",Array.prototype.slice.call(arguments,1))};
f.warn=function(a,b){2<=this.f&&y(this,a,"WARN",Array.prototype.slice.call(arguments,1))};f.l=function(a,b){if(1<=this.f)y(this,a,"ERROR",Array.prototype.slice.call(arguments,1));else{var c=z.apply(null,Array.prototype.slice.call(arguments,1));A(this,c);return c}};f.error=function(a,b){var c=this.l.apply(this,arguments);c&&self.reportError(c)};f.expectedError=function(a,b){var c=this.l.apply(this,arguments);c&&(c.expected=!0,self.reportError(c))};
f.createError=function(a){var b=z.apply(null,arguments);A(this,b);return b};f.createExpectedError=function(a){var b=z.apply(null,arguments);A(this,b);b.expected=!0;return b};
f.assert=function(a,b,c){var d;if(!a){var e=(b||"Assertion failed").split("%s"),g=e.shift(),m=g,t=[];""!=g&&t.push(g);for(g=2;g<arguments.length;g++){var k=arguments[g];k&&k.tagName&&(d=k);var E=e.shift();t.push(k);var u=E.trim();""!=u&&t.push(u);var u=m,l;l=(l=k)&&1==l.nodeType?l.tagName.toLowerCase()+(l.id?"#"+l.id:""):l;m=u+(l+E)}g=Error(m);g.fromAssert=!0;g.associatedElement=d;g.messageArray=t;A(this,g);self.reportError(g);throw g;}return a};
f.assertElement=function(a,b){this.assert(a&&1==a.nodeType,(b||"Element expected")+": %s",a);return a};f.assertString=function(a,b){this.assert("string"==typeof a,(b||"String expected")+": %s",a);return a};f.assertNumber=function(a,b){this.assert("number"==typeof a,(b||"Number expected")+": %s",a);return a};f.assertEnumValue=function(a,b,c){a:{for(var d in a)if(a[d]===b){a=!0;break a}a=!1}if(a)return b;this.assert(!1,'Unknown %s value: "%s"',c||"enum",b)};
function A(a,b){b=B(b);a.h?b.message?-1==b.message.indexOf(a.h)&&(b.message+=a.h):b.message=a.h:0<=b.message.indexOf("\u200b\u200b\u200b")&&(b.message=b.message.replace("\u200b\u200b\u200b",""))}function B(a){var b=a.message,c=String(Math.random());a.message=c;if(a.message===c)return a.message=b,a;var b=Error(a.message),d;for(d in a)b[d]=a[d];b.stack=a.stack;return b}
function z(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];e instanceof Error&&!b?b=B(e):(c&&(c+=" "),c+=e)}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}self.log=self.log||{user:null,dev:null};var C=self.log,D=null;function F(){if(!C.user){if(!D)throw Error("failed to call initLogConstructor");C.user=new D(self,function(a){var b=parseInt(a.log,10);return a.development||1<=b?4:0},"\u200b\u200b\u200b")}}
function G(){if(C.dev)return C.dev;if(!D)throw Error("failed to call initLogConstructor");return C.dev=new D(self,function(a){a=parseInt(a.log,10);return 3<=a?4:2<=a?3:0})};function H(a){var b=Object.create(null);a&&Object.assign(b,a);return b};H();function I(a,b){var c=a.Promise;c?c.resolve().then(b):a.setTimeout(b,0)};function J(){this.b=null}f=J.prototype;f.add=function(a){var b=this;this.b||(this.b=[]);this.b.push(a);return function(){b.remove(a)}};f.remove=function(a){this.b&&(a=this.b.indexOf(a),-1<a&&this.b.splice(a,1))};f.removeAll=function(){this.b&&(this.b.length=0)};f.fire=function(a){if(this.b)for(var b=this.b,c=0;c<b.length;c++)(0,b[c])(a)};f.getHandlerCount=function(){return this.b?this.b.length:0};function K(a,b){function c(a){try{return g(a)}catch(k){throw self.reportError(k),k;}}var d=void 0,e=a,g=b,m=d||!1;e.addEventListener("message",c,m)};function L(a,b){K(a,b)}function M(a,b,c,d){c=void 0===c?H(void 0):c;d=void 0===d?null:d;c.type=a;c.sentinel=b;return"amp-"+(d||"")+JSON.stringify(c)};function N(a){return(a=Number(a))?0<a?1:-1:a};var O=Object.prototype.hasOwnProperty;function P(a,b){if(null==a)throw new TypeError("Cannot convert undefined or null to object");for(var c=Object(a),d=1;d<arguments.length;d++){var e=arguments[d];if(null!=e)for(var g in e)O.call(e,g)&&(c[g]=e[g])}return c};function Q(a){this.a=a;this.B=r().rtvVersion||null;this.i=a.parent;this.j=null;this.g=H();R(this)}f=Q.prototype;f.makeRequest=function(a,b,c){var d=this.registerCallback(b,c);this.sendMessage(a);return d};f.registerCallback=function(a,b){var c=a;c in this.g||(this.g[c]=new J);return this.g[c].add(b)};f.sendMessage=function(a,b){this.i.postMessage(M(a,this.j,b,this.B),"*")};
function R(a){L(a.a,function(b){if(b.source==a.i){var c;b=b.data;if("string"==typeof b&&0==b.indexOf("amp-")&&-1!=b.indexOf("{")){var d=b.indexOf("{");try{c=JSON.parse(b.substr(d))}catch(e){G().error("MESSAGING","Failed to parse message: "+b,e),c=null}}else c=null;c&&c.sentinel==a.j&&(b=c.type,b in a.g&&a.g[b].fire(c))}})}f.setHostWindow=function(a){this.i=a};f.setSentinel=function(a){this.j=a};function S(a){this.m();this.a=a;this.o=this.a.name||null;this.tagName=this.startTime=this.sourceUrl=this.sentinel=this.referrer=this.pageViewId=this.mode=this.location=this.initialIntersection=this.initialLayoutRect=this.hidden=this.data=this.container=this.clientId=this.canonicalUrl=this.canary=this.w=null;"[object Object]"===v.call(this.a.sf_)&&this.a.sf_.cfg?T(this,this.a.sf_.cfg):this.a.AMP_CONTEXT_DATA?"string"==typeof this.a.AMP_CONTEXT_DATA?this.sentinel=this.a.AMP_CONTEXT_DATA:"[object Object]"===
v.call(this.a.AMP_CONTEXT_DATA)&&T(this,this.a.AMP_CONTEXT_DATA):T(this,this.a.name);this.c=new Q(a);this.c.setHostWindow(U(this));this.c.setSentinel(this.sentinel);V(this)}f=S.prototype;f.m=function(){return!0};function V(a){a.c.makeRequest("send-embed-state","embed-state",function(b){a.hidden=b.pageHidden;b=a.a.document.createEvent("Event");b.data={hidden:a.hidden};b.initEvent("amp:visibilitychange",!0,!0);a.a.dispatchEvent(b)})}
f.onPageVisibilityChange=function(a){return this.c.registerCallback("embed-state",function(b){a({hidden:b.pageHidden})})};f.observeIntersection=function(a){var b=this,c=this.c.makeRequest("send-intersections","intersection",function(b){a(b.changes)});I(this.a,function(){a([b.initialIntersection])});return c};f.requestResize=function(a,b){this.c.sendMessage("embed-size",H({width:a,height:b}))};
f.onResizeSuccess=function(a){this.c.registerCallback("embed-size-changed",function(b){a(b.requestedHeight,b.requestedWidth)})};f.onResizeDenied=function(a){this.c.registerCallback("embed-size-denied",function(b){a(b.requestedHeight,b.requestedWidth)})};f.addContextToIframe=function(a){a.name=this.o};f.noContentAvailable=function(){this.c.sendMessage("no-content")};
function T(a,b){var c;if("string"===typeof b)a:{try{c=JSON.parse(b);break a}catch(g){}c=void 0}else c=b;var d=c,e=d._context||d.attributes._context;a.canary=e.canary;a.canonicalUrl=e.canonicalUrl;a.clientId=e.clientId;a.container=e.container;a.data=e.tagName;a.hidden=e.hidden;a.initialLayoutRect=e.initialLayoutRect;a.initialIntersection=e.initialIntersection;a.location=e.location;a.mode=e.mode;a.pageViewId=e.pageViewId;a.referrer=e.referrer;a.sentinel=e.sentinel;a.sourceUrl=e.sourceUrl;a.startTime=
e.startTime;a.tagName=e.tagName;a.w=d.type||null}function U(a){var b=a.sentinel.match(/((\d+)-\d+)/),c=Number(b[2]),d=[];for(a=a.a;a&&a!=a.parent;a=a.parent)d.push(a.parent);return d[d.length-1-c]}function W(a){S.apply(this,arguments)}h(W,S);W.prototype.m=function(){return!1};(function(a){a.Math.sign||a.Object.defineProperty(a.Math,"sign",{enumerable:!1,configurable:!0,writable:!0,value:N})})(self);(function(a){a.Object.assign||a.Object.defineProperty(a.Object,"assign",{enumerable:!1,configurable:!0,writable:!0,value:P})})(self);(function(){D=x;G();F()})();(function(a){self.reportError=a})(function(){});try{var windowContextCreated=new Event("amp-windowContextCreated");window.context=new W(window);window.dispatchEvent(windowContextCreated)}catch(a){};})();
//# sourceMappingURL=ampcontext-v0.js.map

