(self.AMP=self.AMP||[]).push({n:"amp-share-tracking",v:"123456789",f:(function(AMP){function h(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};var l=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function m(a){if(!a)return[];for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return b};Date.now();self.log=self.log||{user:null,dev:null};var n=self.log;function p(){if(n.user)return n.user;throw Error("failed to call initLogConstructor");};function q(a,b){a=a.__AMP_TOP||a;return r(a,b)}function t(a,b){var c,d=a=a.__AMP_TOP||a,e=a,f=b,k=u(d),g=k["share-tracking"];g||(g=k["share-tracking"]={obj:null,promise:null,resolve:null,context:null,ctor:null});g.ctor||g.obj||(g.ctor=f,g.context=e,g.resolve&&r(d,"share-tracking"));c&&r(a,"share-tracking")}function v(a){a=w(a);a=w(a);a=a.isSingleDoc()?a.win:a;return r(a,"history")}function w(a){return a.nodeType?q((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}
function r(a,b){var c=u(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function u(a){var b=a.services;b||(b=a.services={});return b};var x=null;Promise.resolve();
function y(a){var b;if(!x){x=Object.create(null);if(a.AMP_CONFIG)for(b in a.AMP_CONFIG){var c=a.AMP_CONFIG[b];"number"===typeof c&&0<=c&&1>=c&&(x[b]=Math.random()<c)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(b=a.AMP_CONFIG["allow-doc-opt-in"],c=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var c=c.getAttribute("content").split(","),d=0;d<c.length;d++)-1!=b.indexOf(c[d])&&(x[c[d]]=!0);Object.assign(x,z(a));
if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){b=a.AMP_CONFIG["allow-url-opt-in"];c=a.location.originalHash||a.location.hash;a=Object.create(null);if(c)for(var e;e=l.exec(c);)d=decodeURIComponent(e[1]).trim(),e=e[2]?decodeURIComponent(e[2]).trim():"",a[d]=e;for(c=0;c<b.length;c++)d=a["e-"+b[c]],"1"==d&&(x[b[c]]=!0),"0"==d&&(x[b[c]]=!1)}}b=x;var f=b;return!!f["amp-share-tracking"]}
function z(a){a:{var b;b:{try{b=a.document.cookie;break b}catch(k){}b=void 0}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var c=a[b].trim(),d=c.indexOf("=");if(-1!=d&&"AMP_EXP"==decodeURIComponent(c.substring(0,d).trim())){a=decodeURIComponent(c.substring(d+1).trim());break a}}a=null}var e=a,f=e?e.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<f.length;b++)0!=f[b].length&&("-"==f[b][0]?a[f[b].substr(1)]=!1:a[f[b]]=!0);return a};var A={"+":"-","/":"_","=":"."};function B(a){a=String.fromCharCode.apply(String,m(a));return btoa(a).replace(/[+/=]/g,function(a){return A[a]})};function C(a){AMP.BaseElement.call(this,a);this.a=this.b=""}h(C,AMP.BaseElement);C.prototype.isLayoutSupported=function(a){return"nodisplay"==a||"container"==a};
C.prototype.buildCallback=function(){var a=this;y(this.win)||(t(this.win,function(){return Promise.reject(p().createError("amp-share-tracking disabled"))}),p().assert(!1,"amp-share-tracking experiment is disabled"));this.b=this.element.getAttribute("data-href");var b=Promise.all([D(this),this.b?E(this,this.b):Promise.resolve(B(F(this)))]).then(function(b){var c=b[0],e=b[1];if(e&&""!=e){var f=c,f=f?a.a.substr(f.length+1):a.a,k="."+e;f&&("&"!=f[0]&&(k+="&"),k+=f);var g=k;v(a.getAmpDoc()).updateFragment(g)}return{incomingFragment:c,
outgoingFragment:e}});t(this.win,function(){return b})};function D(a){return G(a).then(function(a){var b=a.match(/^\.([^&]*)/);return b?b[1]:""})}function G(a){return v(a.getAmpDoc()).getFragment().then(function(b){return a.a=b})}
function E(a,b){var c={method:"POST",credentials:"include",body:Object.create(null)};return q(a.win,"xhr").fetchJson(b,c).then(function(a){return a.json()}).then(function(a){if(a.fragment)return a.fragment;p().error("amp-share-tracking","The response from ["+b+"] does not have a fragment value.");return""},function(a){p().error("amp-share-tracking","The request to share-tracking endpoint failed:",a);return""})}
function F(a){a=a.win;if(a.crypto&&a.crypto.getRandomValues){var b=new Uint8Array(6);a.crypto.getRandomValues(b);a=b}else a=null;if(!a){a=new Uint8Array(6);for(var c=Math.random(),b=0;6>b;b++)c*=256,a[b]=Math.floor(c),c-=a[b]}return a}(function(a){a.registerElement("amp-share-tracking",C)})(self.AMP);
})});
//# sourceMappingURL=amp-share-tracking-0.1.js.map

