(self.AMP=self.AMP||[]).push({n:"amp-ad-exit",v:"123456789",f:(function(AMP){function g(a,b){function d(){}d.prototype=b.prototype;a.prototype=new d;a.prototype.constructor=a;for(var c in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c]};var k=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;Date.now();self.log=self.log||{user:null,dev:null};var l=self.log;function m(){if(l.user)return l.user;throw Error("failed to call initLogConstructor");};function n(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView;if(b=b!=(b.__AMP_TOP||b)&&p(b,"url-replace")?q(b,"url-replace"):null)return b}b=r(a);b=r(b);b=b.isSingleDoc()?b.win:b;return q(b,"url-replace")}function r(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView,b=b.__AMP_TOP||b;a=q(b,"ampdoc").getAmpDoc(a)}return a}
function q(a,b){p(a,b);var d=a.services;d||(d=a.services={});var c=d;a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function p(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};var t=null;Promise.resolve();
function u(a){var b;if(!t){t=Object.create(null);if(a.AMP_CONFIG)for(b in a.AMP_CONFIG){var d=a.AMP_CONFIG[b];"number"===typeof d&&0<=d&&1>=d&&(t[b]=Math.random()<d)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(b=a.AMP_CONFIG["allow-doc-opt-in"],d=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var d=d.getAttribute("content").split(","),c=0;c<d.length;c++)-1!=b.indexOf(d[c])&&(t[d[c]]=!0);Object.assign(t,v(a));
if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){b=a.AMP_CONFIG["allow-url-opt-in"];d=a.location.originalHash||a.location.hash;a=Object.create(null);if(d)for(var e;e=k.exec(d);)c=decodeURIComponent(e[1]).trim(),e=e[2]?decodeURIComponent(e[2]).trim():"",a[c]=e;for(d=0;d<b.length;d++)c=a["e-"+b[d]],"1"==c&&(t[b[d]]=!0),"0"==c&&(t[b[d]]=!1)}}b=t;var f=b;return!!f["amp-ad-exit"]}
function v(a){a:{var b;b:{try{b=a.document.cookie;break b}catch(h){}b=void 0}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var d=a[b].trim(),c=d.indexOf("=");if(-1!=c&&"AMP_EXP"==decodeURIComponent(d.substring(0,c).trim())){a=decodeURIComponent(d.substring(c+1).trim());break a}}a=null}var e=a,f=e?e.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<f.length;b++)0!=f[b].length&&("-"==f[b][0]?a[f[b].substr(1)]=!1:a[f[b]]=!0);return a};function w(a,b){var d,c;try{c=a.open(b,"_blank",d)}catch(f){var e;if(l.dev)e=l.dev;else throw Error("failed to call initLogConstructor");e.error("DOM","Failed to open url on target: ","_blank",f)}c||(c=a.open(b,"_top"))};function y(a){this.name=a}y.prototype.filter=function(){};function z(a,b){this.name=a;m().assert(A(b),"Invalid ClickDelay spec");this.f=b.delay;this.g=Date.now()}g(z,y);z.prototype.filter=function(){return Date.now()-this.g>=this.f};function A(a){return"clickDelay"==a.type&&"number"==typeof a.delay&&0<a.delay}function B(){var a=1E3;return{type:"clickDelay",delay:a}};function C(a){m().assert("object"==typeof a);if(a.filters){var b=a.filters,d;for(d in b)m().assert("object"==typeof b[d],"Filter specification '%s' is malformed",d),m().assert("clickDelay"==b[d].type,"Only ClickDelayFilter is currently supported.")}else a.filters={};if(a.transport){var b=a.transport,c;for(c in b)m().assert("beacon"==c||"image"==c,"Unknown transport option: '"+c+"'"),m().assert("boolean"==typeof b[c])}else a.transport={};c=a.targets;m().assert("object"==typeof c,"'targets' must be an object");
for(var e in c)D(e,c[e],a);return a}function D(a,b,d){m().assert("string"==typeof b.finalUrl,"finalUrl of target '%s' must be a string",a);b.filters&&b.filters.forEach(function(a){m().assert(d.filters[a],"filter '%s' not defined",a)});if(b.vars){a=/^_[a-zA-Z0-9_-]+$/;for(var c in b.vars)m().assert(a.test(c),"'%s' must match the pattern '%s'",c,a)}};function E(a,b){switch(b.type){case "clickDelay":return new z(a,b)}};function F(a){AMP.BaseElement.call(this,a);this.c={};this.b=[];this.a={beacon:!0,image:!0};this.registerAction("exit",this.exit.bind(this))}g(F,AMP.BaseElement);
F.prototype.exit=function(a){var b=a,d=b.args,b=b.event,c=this;m().assert(u(this.win),"amp-ad-exit experiment is off.");var e=this.c[d.target];m().assert(e,"Exit target not found: '"+d.target+"'");b.preventDefault();if(G(this.b,b)&&G(e.filters,b)){var f=H(this,d,b,e);e.trackingUrls&&e.trackingUrls.map(f).forEach(function(a){c.a.beacon&&c.win.navigator.sendBeacon&&c.win.navigator.sendBeacon(a,"")||!c.a.image||(c.win.document.createElement("img").src=a)});w(this.win,f(e.finalUrl))}};
function H(a,b,d,c){var e={CLICK_X:function(){return d.clientX},CLICK_Y:function(){return d.clientY}},f={RANDOM:!0,CLICK_X:!0,CLICK_Y:!0};if(c.vars){var h={},x;for(x in c.vars)h.customVar=x,"_"==h.customVar[0]&&(e[h.customVar]=function(a){return function(){return b[a.customVar]||c.vars[a.customVar].defaultValue}}(h),f[h.customVar]=!0),h={customVar:h.customVar}}var I=n(a.getAmpDoc());return function(a){return I.expandUrlSync(a,e,void 0,f)}}
function G(a,b){return a.every(function(a){var c=a.filter(b);m().info("amp-ad-exit","Filter '"+a.name+"': "+(c?"pass":"fail"));return c})}
F.prototype.buildCallback=function(){this.element.setAttribute("aria-hidden","true");this.b.push(E("minDelay",B()));var a=this.element.children;m().assert(1==a.length,"The tag should contain exactly one <script> child.");a=a[0];m().assert("SCRIPT"==a.tagName&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase(),'The amp-ad-exit config should be inside a <script> tag with type="application/json"');try{var b=C(JSON.parse(a.textContent)),d={},c;for(c in b.filters)d[c]=E(c,b.filters[c]);for(var e in b.targets){var f=
b.targets[e];this.c[e]={finalUrl:f.finalUrl,trackingUrls:f.trackingUrls||[],vars:f.vars||{},filters:(f.filters||[]).map(function(a){return d[a]}).filter(function(a){return a})}}this.a.beacon=!1!==b.transport.beacon;this.a.image=!1!==b.transport.image}catch(h){throw m().error("amp-ad-exit","Invalid JSON config",h),h;}};F.prototype.isLayoutSupported=function(){return!0};AMP.registerElement("amp-ad-exit",F);
})});
//# sourceMappingURL=amp-ad-exit-0.1.js.map

