(self.AMP=self.AMP||[]).push({n:"amp-bind",v:"123456789",f:(function(AMP){var v,aa=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a}(this);function da(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function w(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var ea=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function fa(a){var b=Object.create(null);if(!a)return b;for(var c;c=ea.exec(a);){var d=decodeURIComponent(c[1]).trim(),e=c[2]?decodeURIComponent(c[2]).trim():"";b[d]=e}return b};var ia="";
function y(){var a,b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;if(c.context&&c.context.mode)c=c.context.mode;else{var d=fa(c.location.originalHash||c.location.hash),e=fa(c.location.search);ia||(ia=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"01123456789");c={localDev:!1,development:!("1"!=d.development&&!c.AMP_DEV_MODE),examiner:"2"==d.development,filter:d.filter,minified:!0,lite:void 0!=e.amp_lite,test:!1,log:d.log,version:"123456789",rtvVersion:ia}}c=b.AMP_MODE=
c}return c};var ja=Object.prototype.toString;function ka(a){if(!a)return[];for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return b}function la(a){return"[object Object]"===ja.call(a)};Date.now();function ma(a){var b=a.message,c=String(Math.random());a.message=c;if(a.message===c)return a.message=b,a;var b=Error(a.message),d;for(d in a)b[d]=a[d];b.stack=a.stack;return b}function na(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];e instanceof Error&&!b?b=ma(e):(c&&(c+=" "),c+=e)}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}function oa(a){var b=na.apply(null,arguments);setTimeout(function(){self.reportError(b);throw b;})}
self.log=self.log||{user:null,dev:null};var pa=self.log;function D(){if(pa.user)return pa.user;throw Error("failed to call initLogConstructor");}function qa(){if(pa.dev)return pa.dev;throw Error("failed to call initLogConstructor");};var ra=Object.prototype.hasOwnProperty;function sa(a){var b=Object.create(null);a&&Object.assign(b,a);return b}function ta(a,b){if(ra.call(a,b))return a[b]}
function ua(a,b,c){var d=[],e=[{target:a,source:b,depth:0}];for(a={};0<e.length;){b=e.shift();a.K=b.target;a.I=b.source;a.depth=b.depth;if(d.includes(a.I))throw Error("Source object contains circular references");d.push(a.I);a.K!==a.I&&(a.depth>c?Object.assign(a.K,a.I):(Object.keys(a.I).forEach(function(a){return function(b){var c=a.I[b];if(ra.call(a.K,b)){var d=a.K[b];if(la(c)&&la(d)){e.push({target:d,source:c,depth:a.depth+1});return}}a.K[b]=c}}(a)),a={I:a.I,K:a.K,depth:a.depth}))}}
function va(a,b){var c=10;ua(a,b,c||Number.POSITIVE_INFINITY)};var wa=self.AMP_CONFIG||{},xa=wa.cdnUrl||"https://cdn.ampproject.org",Fa=("string"==typeof wa.cdnProxyRegex?new RegExp(wa.cdnProxyRegex):wa.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org/,Ga=wa.errorReportingUrl||"https://amp-error-reporting.appspot.com/r";var Ha,Ia,Ja=/[?&]amp_js[^&]*/;
function R(a){var b;Ha||(Ha=self.document.createElement("a"),Ia=self.UrlCache||(self.UrlCache=Object.create(null)));var c=Ia[a];if(c)return c;var d=Ha;d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=
d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;var f=e,k=f;return b?k:Ia[a]=k}function Ka(a){"string"==typeof a&&(a=R(a));var b;(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}
function La(a,b){var c;c=void 0===c?"source":c;D().assert(null!=a,"%s %s must be available",b,c);var d=a;D().assert(Ka(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d);return d}function Ma(a){"string"==typeof a&&(a=R(a));return Fa.test(a.origin)}
function Na(a,b){"string"==typeof b&&(b=R(b));var c;if("function"==typeof URL)c=(new URL(a,b.href)).toString();else{c=a;var d=b;"string"==typeof d&&(d=R(d));c=c.replace(/\\/g,"/");var e=R(c);c=w(c.toLowerCase(),e.protocol)?e.href:w(c,"//")?d.protocol+c:w(c,"/")?d.origin+c:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+c}return c};function Oa(a,b){if(a.nodeType){var c=Pa((a.ownerDocument||a).defaultView,b);if(c)return c}return S(a,b)}function Qa(a,b){var c=Ra(a);Pa(a,"bind");Ta(a,a,"bind",function(){return b});T(a,"bind")}function Pa(a,b){var c=Ra(a);return a!=c&&Ua(a,b)?T(a,b):null}function Va(a,b){a=Ra(a);return T(a,b)}function Wa(a,b,c){var d;a=Ra(a);Ta(a,a,b,c);d&&T(a,b)}function S(a,b){a=Xa(a);a=Ya(a);return T(a,b)}function Ra(a){return a.__AMP_TOP||a}
function Xa(a){return a.nodeType?Va((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function Ya(a){a=Xa(a);return a.isSingleDoc()?a.win:a}function T(a,b){Ua(a,b);var c=Za(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Ta(a,b,c,d){var e=Za(a),f=e[c];f||(f=e[c]={obj:null,promise:null,resolve:null,context:null,ctor:null});f.ctor||f.obj||(f.ctor=d,f.context=b,f.resolve&&T(a,c))}
function $a(a,b){var c=ab(a,b);if(c)return c;var d,e=new Promise(function(a){d=a});Za(a)[b]={obj:null,promise:e,resolve:d,context:null,ctor:null};return e}function ab(a,b){var c=Za(a)[b];if(c){if(c.promise)return c.promise;T(a,b);return c.promise=Promise.resolve(c.obj)}return null}function Za(a){var b=a.services;b||(b=a.services={});return b}function Ua(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};function bb(a,b){try{return JSON.parse(a)}catch(c){b&&b(c)}};var V=null;Promise.resolve();function cb(a){a:{var b;b:{try{b=a.document.cookie;break b}catch(k){}b=void 0}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var c=a[b].trim(),d=c.indexOf("=");if(-1!=d&&"AMP_EXP"==decodeURIComponent(c.substring(0,d).trim())){a=decodeURIComponent(c.substring(d+1).trim());break a}}a=null}var e=a,f=e?e.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<f.length;b++)0!=f[b].length&&("-"==f[b][0]?a[f[b].substr(1)]=!1:a[f[b]]=!0);return a};function db(a,b,c){if(b(a))c();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){b(a)&&(e.disconnect(),c())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){b(a)&&(d.clearInterval(f),c())},5)}}function eb(a,b){db(a.documentElement,function(){return!!a.body},b)}function fb(a){return new Promise(function(b){eb(a,b)})}function gb(a){return"SCRIPT"==a.tagName&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()};function hb(a){return a.ampExtendedElements?!!a.ampExtendedElements["amp-bind"]:!1}function ib(a){return jb(a).then(function(a){return D().assert(a,"Service %s was requested to be provided through %s, but %s is not loaded in the current page. To fix this problem load the JavaScript file for %s in this page.","bind","amp-bind","amp-bind","amp-bind")})}
function jb(a){var b=Xa(a),c=ab(Ya(a),"bind");return c?c:Promise.resolve().then(function(){return hb(b.win)?$a(Ya(a),"bind"):b.whenBodyAvailable().then(function(){return hb(b.win)?$a(Ya(a),"bind"):null})})}function kb(a){return lb(a).then(function(b){return b?b:ib(a)})}function lb(a){var b=Oa(a,"bind");return b?Promise.resolve(b):a.nodeType?mb((a.ownerDocument||a).defaultView):Promise.resolve(null)}
function mb(a){return Promise.resolve().then(function(){return hb(a)?$a(a,"bind"):fb(a.document).then(function(){return hb(a)?$a(a,"bind"):null})})};function nb(){var a=ob();return function(b){return setTimeout(b,a())}}function ob(){var a=0;return function(){var b=Math.pow(1.5,a++),c;c=b*(c||.3)*Math.random();.5<Math.random()&&(c*=-1);b+=c;return 1E3*b}};function pb(){this.h=null}v=pb.prototype;v.add=function(a){var b=this;this.h||(this.h=[]);this.h.push(a);return function(){b.remove(a)}};v.remove=function(a){this.h&&(a=this.h.indexOf(a),-1<a&&this.h.splice(a,1))};v.removeAll=function(){this.h&&(this.h.length=0)};v.fire=function(a){if(this.h)for(var b=this.h,c=0;c<b.length;c++)(0,b[c])(a)};v.getHandlerCount=function(){return this.h?this.h.length:0};var qb,xb="Webkit webkit Moz moz ms O o".split(" ");function yb(a,b,c){if(w(b,"--"))return b;qb||(qb=sa());var d=qb[b];if(!d||c){d=b;if(void 0===a[b]){var e=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var f=0;f<xb.length;f++){var k=xb[f]+e;if(void 0!==a[k]){e=k;break a}}e=""}var l=e;void 0!==a[l]&&(d=l)}c||(qb[b]=d)}return d}function zb(a,b,c){var d;(b=yb(a.style,b,void 0))&&(a.style[b]=d?c+d:c)}
function Ab(a){var b=!1;if(void 0===b){var c;c=(c=yb(a.style,"display",void 0))?a.style[c]:void 0;b="none"==c}zb(a,"display",b?"":"none")};function Bb(a){this.win=a;this.B=a.document;this.J=yb(this.B,"hidden",!0);void 0===this.B[this.J]&&(this.J=null);this.X=yb(this.B,"visibilityState",!0);void 0===this.B[this.X]&&(this.X=null);this.oa=new pb;this.O=null;if(this.J){this.O="visibilitychange";var b=this.J.indexOf("Hidden");-1!=b&&(this.O=this.J.substring(0,b)+"Visibilitychange")}this.ga=this.wa.bind(this);this.O&&this.B.addEventListener(this.O,this.ga);this.L=null}v=Bb.prototype;
v.Fa=function(){this.O&&this.B.removeEventListener(this.O,this.ga)};v.isHidden=function(){return this.J?this.B[this.J]:!1};v.getVisibilityState=function(){return this.X?this.B[this.X]:this.isHidden()?"hidden":"visible"};v.onVisibilityChanged=function(a){return this.oa.add(a)};v.wa=function(){this.oa.fire()};v.onBodyAvailable=function(a){var b=this.B;if(b.body)return a(),null;this.L||(this.L=new pb,db(b.documentElement,function(){return!!b.body},this.ua.bind(this)));return this.L.add(a)};
v.ua=function(){this.L.fire();this.L.removeAll();this.L=null};var Cb={"amp-dynamic-css-classes":"[custom-element=amp-dynamic-css-classes]",variant:"amp-experiment"};function Db(a){var b=Eb(a).map(function(b){return Va(a,"timer").timeoutPromise(3E3,$a(a,b),"Render timeout waiting for service "+b+" to be ready.")});return Promise.all(b)}function Eb(a){var b=a.document;return Object.keys(Cb).filter(function(a){return b.querySelector(Cb[a])})};function Fb(a){var b,c=a.defaultView;if(!c.__AMP_BODY_VISIBLE){var d=function(){var b=a.body,c={opacity:1,visibility:"visible",animation:"none"},d;for(d in c)zb(b,d,c[d]);try{S(a,"resources").renderStarted()}catch(l){}};try{Wa(c,"documentState",Bb),Va(c,"documentState").onBodyAvailable(function(){c.__AMP_BODY_VISIBLE||(c.__AMP_BODY_VISIBLE=!0,b?Db(c).catch(function(a){oa(a);return[]}).then(function(b){d();0<b.length&&S(a,"resources").schedulePass(1,!0);try{var e=Va(c,"performance");e.tick("mbv");
e.flush()}catch(k){}}):d())})}catch(e){d(),oa(e)}}};var Gb=self.AMPErrors||[];self.AMPErrors=Gb;function Hb(a){Hb=nb();return Hb(a)}function Ib(a){try{return JSON.stringify(a)}catch(b){return String(a)}}var Jb;
function W(a,b){try{var c;if(a)if(void 0!==a.message)a=ma(a),c=!0;else{var d=a;a=Error(Ib(d));a.origError=d}else a=Error("Unknown error");if(!a.reported){a.reported=!0;var e=b||a.associatedElement;e&&e.classList&&(e.classList.add("i-amphtml-error"),y().development&&(e.classList.add("i-amphtml-element-error"),e.setAttribute("error-message",a.message)));if(self.console){var f=console.error||console.log;a.messageArray?f.apply(console,a.messageArray):e?f.call(console,a.message,e):f.call(console,a.message)}e&&
e.sa&&e.sa("amp:error",a.message);Kb.call(void 0,void 0,void 0,void 0,void 0,a)}}catch(k){setTimeout(function(){throw k;})}}function Kb(a,b,c,d,e){this&&this.document&&Fb(this.document);if(!y().development){var f=!1;try{f=Lb()}catch(l){}if(!(f&&.01<Math.random())){var k=Mb(a,b,c,d,e,f);k&&Hb(function(){(new Image).src=k})}}}
function Mb(a,b,c,d,e,f){var k=!1;e&&(a=e.message?e.message:String(e),e.expected&&(k=!0));a||(a="Unknown error");if(!/_reported_/.test(a)&&"CANCELLED"!=a){if(-1!=a.indexOf("Failed to load:")||"Script error."==a)if(k=!0,.001<Math.random())return;var l=0<=a.indexOf("\u200b\u200b\u200b");f=Ga+"?v="+encodeURIComponent("123456789")+"&noAmp="+(f?1:0)+"&m="+encodeURIComponent(a.replace("\u200b\u200b\u200b",""))+"&a="+(l?1:0);k&&(f+="&ex=1");var g="1p";self.context&&self.context.location?(f+=
"&3p=1",g="3p"):y().runtime&&(g=y().runtime);f+="&rt="+g;var m=self;m.AMP_CONFIG&&m.AMP_CONFIG.canary&&(f+="&ca=1");self.location.ancestorOrigins&&self.location.ancestorOrigins[0]&&(f+="&or="+encodeURIComponent(self.location.ancestorOrigins[0]));self.viewerState&&(f+="&vs="+encodeURIComponent(self.viewerState));self.parent&&self.parent!=self&&(f+="&iem=1");if(self.AMP&&self.AMP.viewer){var h=self.AMP.viewer.getResolvedViewerUrl(),q=self.AMP.viewer.maybeGetMessagingOrigin();h&&(f+="&rvu="+encodeURIComponent(h));
q&&(f+="&mso="+encodeURIComponent(q))}Jb||(Jb=Nb());f+="&jse="+Jb;var p=[],m=V,r;for(r in m)p.push(r+"="+(m[r]?"1":"0"));f+="&exps="+encodeURIComponent(p.join(","));if(e){f+="&el="+encodeURIComponent(e&&e.associatedElement?e.associatedElement.tagName:"u");e.args&&(f+="&args="+encodeURIComponent(JSON.stringify(e.args)));if(!l&&!e.ignoreStack&&e.stack){var z=(e.stack||"").substr(0,1E3);f+="&s="+encodeURIComponent(z)}e.message+=" _reported_"}else f+="&f="+encodeURIComponent(b||"")+"&l="+encodeURIComponent(c||
"")+"&c="+encodeURIComponent(d||"");f+="&r="+encodeURIComponent(self.document.referrer);f+="&ae="+encodeURIComponent(Gb.join(","));Gb.push(a);f+="&fr="+encodeURIComponent(self.location.originalHash||self.location.hash);2072<=f.length&&(f=f.substr(0,2064).replace(/\%[^&%]+$/,"")+"&SHORT=1");return f}}function Lb(){for(var a=self.document.querySelectorAll("script[src]"),b=0;b<a.length;b++)if(!Ma(a[b].src.toLowerCase()))return!0;return!1}
function Nb(){function a(){}a.prototype.t=function(){throw Error("message");};var b=new a;try{b.t()}catch(e){var c=e.stack;if(w(c,"t@"))return"Safari";if(-1<c.indexOf(".prototype.t@"))return"Firefox";var d=c.split("\n").pop();if(/\bat .* \(/i.test(d))return"IE";if(w(c,"Error: message"))return"Chrome"}return"unknown"};function Ob(a,b){for(var c=[],d=0;d<a.length;d++){var e=a[d];b(e,d,a)||(c.push(e),a.splice(d,1),d--)}};function Pb(a,b){var c,d=La(b.getAttribute("src"),b);return Oa(a,"url-replace").expandAsync(d).then(function(c){var d={};b.hasAttribute("credentials")?d.credentials=b.getAttribute("credentials"):d.requireAmpResponseSourceOrigin=!1;return Va(a.win,"batched-xhr").fetchJson(c,d)}).then(function(a){return a.json()}).then(function(a){if(null==a)throw Error("Response is undefined.");var b;b=c||".";if("."!=b){b=b.split(".");for(var d=0;d<b.length;d++){var e=b[d];if(!e){a=void 0;break}if(!la(a)||void 0===
a[e]||null==a||"object"!=typeof a||!Object.prototype.hasOwnProperty.call(a,e)){a=void 0;break}a=a[e]}}b=a;return b})};function Y(a,b,c){this.type=a;this.args=b;this.value=c};(function(){function a(a,b,c,d){c=c||{};for(d=a.length;d--;c[a[d]]=b);return c}function b(){this.yy={}}var c=[1,7],d=[1,10],e=[1,11],f=[1,12],k=[1,13],l=[1,23],g=[1,17],m=[1,18],h=[1,19],q=[1,20],p=[1,21],r=[1,22],z=[1,26],G=[1,25],t=[1,27],F=[1,28],B=[1,29],I=[1,30],C=[1,31],K=[1,32],H=[1,33],E=[1,34],L=[1,35],N=[1,36],O=[1,37],P=[1,38],x=[1,39],u=[1,41],A=[5,10,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,34,35,44,46],ya=[1,47],za=[1,52],X=[5,10,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,35,
44,46],ba=[44,46],Aa=[1,80],Ba=[10,35,44],Ca=[5,10,14,15,19,20,21,22,23,24,25,26,27,28,35,44,46],ga=[5,10,19,20,21,22,23,24,25,26,27,28,35,44,46],Da=[5,10,19,20,25,26,27,28,35,44,46],ha={trace:function rb(){},yy:{},za:{error:2,result:3,expr:4,EOF:5,operation:6,invocation:7,member_access:8,"(":9,")":10,variable:11,literal:12,"!":13,"-":14,"+":15,"*":16,"/":17,"%":18,"&&":19,"||":20,"<=":21,"<":22,">=":23,">":24,"!=":25,"==":26,"?":27,":":28,".":29,NAME:30,args:31,array:32,member:33,"[":34,"]":35,primitive:36,
object_literal:37,array_literal:38,STRING:39,NUMBER:40,TRUE:41,FALSE:42,NULL:43,",":44,"{":45,"}":46,object:47,key_value:48,key:49,$accept:0,$end:1},S:{2:"error",5:"EOF",9:"(",10:")",13:"!",14:"-",15:"+",16:"*",17:"/",18:"%",19:"&&",20:"||",21:"<=",22:"<",23:">=",24:">",25:"!=",26:"==",27:"?",28:":",29:".",30:"NAME",34:"[",35:"]",39:"STRING",40:"NUMBER",41:"TRUE",42:"FALSE",43:"NULL",44:",",45:"{",46:"}"},la:[0,[3,2],[3,1],[4,1],[4,1],[4,1],[4,3],[4,1],[4,1],[6,2],[6,2],[6,2],[6,3],[6,3],[6,3],[6,
3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,5],[7,4],[7,2],[31,2],[31,3],[8,2],[33,2],[33,3],[11,1],[12,1],[12,1],[12,1],[36,1],[36,1],[36,1],[36,1],[36,1],[38,2],[38,3],[32,1],[32,3],[37,2],[37,3],[47,1],[47,3],[48,3],[49,1],[49,1]],performAction:function sb(a,b,c,d,e,n){var f=n.length-1;switch(e){case 1:return n[f-1];case 2:return"";case 3:case 4:case 5:case 7:case 8:this.c=n[f];break;case 6:this.c=n[f-1];break;case 9:this.c=new Y(12,[n[f]]);break;case 10:this.c=new Y(13,[n[f]]);
break;case 11:this.c=new Y(14,[n[f]]);break;case 12:this.c=new Y(15,[n[f-2],n[f]]);break;case 13:this.c=new Y(16,[n[f-2],n[f]]);break;case 14:this.c=new Y(17,[n[f-2],n[f]]);break;case 15:this.c=new Y(18,[n[f-2],n[f]]);break;case 16:this.c=new Y(19,[n[f-2],n[f]]);break;case 17:this.c=new Y(20,[n[f-2],n[f]]);break;case 18:this.c=new Y(21,[n[f-2],n[f]]);break;case 19:this.c=new Y(22,[n[f-2],n[f]]);break;case 20:this.c=new Y(23,[n[f-2],n[f]]);break;case 21:this.c=new Y(24,[n[f-2],n[f]]);break;case 22:this.c=
new Y(25,[n[f-2],n[f]]);break;case 23:this.c=new Y(26,[n[f-2],n[f]]);break;case 24:this.c=new Y(27,[n[f-2],n[f]]);break;case 25:this.c=new Y(28,[n[f-4],n[f-2],n[f]]);break;case 26:this.c=new Y(1,[n[f-3],n[f]],n[f-1]);break;case 27:this.c=new Y(1,[void 0,n[f]],n[f-1]);break;case 28:this.c=new Y(2,[]);break;case 29:this.c=new Y(2,[n[f-1]]);break;case 30:this.c=new Y(3,[n[f-1],n[f]]);break;case 31:this.c=new Y(4,null,n[f]);break;case 32:this.c=new Y(4,[n[f-1]]);break;case 33:this.c=new Y(5,null,n[f]);
break;case 34:case 35:case 36:case 52:this.c=n[f];break;case 37:n=a.substr(1,b-2);this.c=new Y(6,null,n);break;case 38:this.c=new Y(6,null,Number(a));break;case 39:this.c=new Y(6,null,!0);break;case 40:this.c=new Y(6,null,!1);break;case 41:this.c=new Y(6,null,null);break;case 42:this.c=new Y(7,[]);break;case 43:this.c=new Y(7,[n[f-1]]);break;case 44:this.c=new Y(8,[n[f]]);break;case 45:case 49:this.c=n[f-2];this.c.args.push(n[f]);break;case 46:this.c=new Y(9,[]);break;case 47:this.c=new Y(9,[n[f-
1]]);break;case 48:this.c=new Y(10,[n[f]]);break;case 50:this.c=new Y(11,[n[f-2],n[f]]);break;case 51:this.c=new Y(6,null,n[f])}},table:[{3:1,4:2,5:[1,3],6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{1:[3]},{5:[1,24],14:z,15:G,16:t,17:F,18:B,19:I,20:C,21:K,22:H,23:E,24:L,25:N,26:O,27:P,29:x,33:40,34:u},{1:[2,2]},a(A,[2,3]),a(A,[2,4]),a(A,[2,5]),{4:42,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,
45:r},a(A,[2,7]),a(A,[2,8]),{4:43,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{4:44,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{4:45,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},a(A,[2,33],{31:46,9:ya}),a(A,[2,34]),a(A,[2,35]),a(A,[2,36]),a(A,[2,37]),a(A,[2,38]),a(A,[2,39]),a(A,[2,40]),a(A,[2,41]),{30:za,36:53,39:g,40:m,41:h,42:q,43:p,
46:[1,48],47:49,48:50,49:51},{4:56,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,32:55,34:l,35:[1,54],36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{1:[2,1]},{4:57,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{4:58,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{4:59,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{4:60,6:4,7:5,8:6,9:c,
11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{4:61,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{4:62,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{4:63,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{4:64,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,
45:r},{4:65,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{4:66,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{4:67,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{4:68,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{4:69,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,
39:g,40:m,41:h,42:q,43:p,45:r},{4:70,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{30:[1,71]},a(A,[2,30]),{4:72,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{10:[1,73],14:z,15:G,16:t,17:F,18:B,19:I,20:C,21:K,22:H,23:E,24:L,25:N,26:O,27:P,29:x,33:40,34:u},a(X,[2,9],{33:40,29:x,34:u}),a(X,[2,10],{33:40,29:x,34:u}),a(X,[2,11],{33:40,29:x,34:u}),a(A,[2,27]),{4:56,6:4,7:5,8:6,9:c,10:[1,74],11:8,
12:9,13:d,14:e,15:f,30:k,32:75,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},a(A,[2,46]),{44:[1,77],46:[1,76]},a(ba,[2,48]),{28:[1,78]},{28:[2,51]},{28:[2,52]},a(A,[2,42]),{35:[1,79],44:Aa},a(Ba,[2,44],{33:40,14:z,15:G,16:t,17:F,18:B,19:I,20:C,21:K,22:H,23:E,24:L,25:N,26:O,27:P,29:x,34:u}),a(Ca,[2,12],{33:40,16:t,17:F,18:B,29:x,34:u}),a(Ca,[2,13],{33:40,16:t,17:F,18:B,29:x,34:u}),a(X,[2,14],{33:40,29:x,34:u}),a(X,[2,15],{33:40,29:x,34:u}),a(X,[2,16],{33:40,29:x,34:u}),a([5,10,19,20,27,28,
35,44,46],[2,17],{33:40,14:z,15:G,16:t,17:F,18:B,21:K,22:H,23:E,24:L,25:N,26:O,29:x,34:u}),a([5,10,20,27,28,35,44,46],[2,18],{33:40,14:z,15:G,16:t,17:F,18:B,19:I,21:K,22:H,23:E,24:L,25:N,26:O,29:x,34:u}),a(ga,[2,19],{33:40,14:z,15:G,16:t,17:F,18:B,29:x,34:u}),a(ga,[2,20],{33:40,14:z,15:G,16:t,17:F,18:B,29:x,34:u}),a(ga,[2,21],{33:40,14:z,15:G,16:t,17:F,18:B,29:x,34:u}),a(ga,[2,22],{33:40,14:z,15:G,16:t,17:F,18:B,29:x,34:u}),a(Da,[2,23],{33:40,14:z,15:G,16:t,17:F,18:B,21:K,22:H,23:E,24:L,29:x,34:u}),
a(Da,[2,24],{33:40,14:z,15:G,16:t,17:F,18:B,21:K,22:H,23:E,24:L,29:x,34:u}),{14:z,15:G,16:t,17:F,18:B,19:I,20:C,21:K,22:H,23:E,24:L,25:N,26:O,27:P,28:[1,81],29:x,33:40,34:u},a(A,[2,31],{31:82,9:ya}),{14:z,15:G,16:t,17:F,18:B,19:I,20:C,21:K,22:H,23:E,24:L,25:N,26:O,27:P,29:x,33:40,34:u,35:[1,83]},a(A,[2,6]),a(A,[2,28]),{10:[1,84],44:Aa},a(A,[2,47]),{30:za,36:53,39:g,40:m,41:h,42:q,43:p,48:85,49:51},{4:86,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,
45:r},a(A,[2,43]),{4:87,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},{4:88,6:4,7:5,8:6,9:c,11:8,12:9,13:d,14:e,15:f,30:k,34:l,36:14,37:15,38:16,39:g,40:m,41:h,42:q,43:p,45:r},a(A,[2,26]),a(A,[2,32]),a(A,[2,29]),a(ba,[2,49]),a(ba,[2,50],{33:40,14:z,15:G,16:t,17:F,18:B,19:I,20:C,21:K,22:H,23:E,24:L,25:N,26:O,27:P,29:x,34:u}),a(Ba,[2,45],{33:40,14:z,15:G,16:t,17:F,18:B,19:I,20:C,21:K,22:H,23:E,24:L,25:N,26:O,27:P,29:x,34:u}),a([5,10,28,35,44,46],
[2,25],{33:40,14:z,15:G,16:t,17:F,18:B,19:I,20:C,21:K,22:H,23:E,24:L,25:N,26:O,27:P,29:x,34:u})],defaultActions:{3:[2,2],24:[2,1],52:[2,51],53:[2,52]},parseError:function Sa(a,b){if(b.recoverable)this.trace(a);else throw Error(a);},parse:function M(a){function b(a){d.length-=2*a;f.length-=a;t.length-=a}var c=this,d=[0],e=[],f=[null],t=[],g=this.table,k="",l=0,F=0,B=0,p=2,m=1,I=t.slice.call(arguments,1),h=Object.create(this.lexer),q={yy:{}},r;for(r in this.yy)Object.prototype.hasOwnProperty.call(this.yy,
r)&&(q.yy[r]=this.yy[r]);h.setInput(a,q.yy);q.yy.lexer=h;q.yy.parser=this;"undefined"==typeof h.yylloc&&(h.yylloc={});var z=h.yylloc;t.push(z);var K=h.options&&h.options.ranges;this.parseError="function"===typeof q.yy.parseError?q.yy.parseError:Object.getPrototypeOf(this).parseError;var G=function(){var a;a=h.lex()||m;"number"!==typeof a&&(a=c.za[a]||a);return a};for(var C,A,x,u,H={},U,E,L;;){x=d[d.length-1];if(this.defaultActions[x])u=this.defaultActions[x];else{if(null===C||"undefined"==typeof C)C=
G();u=g[x]&&g[x][C]}if("undefined"===typeof u||!u.length||!u[0]){var N="";r=[];for(U in g[x])this.S[U]&&U>p&&r.push("'"+this.S[U]+"'");N=h.showPosition?"Parse error on line "+(l+1)+":\n"+h.showPosition()+"\nExpecting "+r.join(", ")+", got '"+(this.S[C]||C)+"'":"Parse error on line "+(l+1)+": Unexpected "+(C==m?"end of input":"'"+(this.S[C]||C)+"'");this.parseError(N,{text:h.match,token:this.S[C]||C,line:h.yylineno,loc:z,expected:r})}if(u[0]instanceof Array&&1<u.length)throw Error("Parse Error: multiple actions possible at state: "+
x+", token: "+C);switch(u[0]){case 1:d.push(C);f.push(h.yytext);t.push(h.yylloc);d.push(u[1]);C=null;A?(C=A,A=null):(F=h.yyleng,k=h.yytext,l=h.yylineno,z=h.yylloc,0<B&&B--);break;case 2:E=this.la[u[1]][1];H.c=f[f.length-E];H.ea={first_line:t[t.length-(E||1)].first_line,last_line:t[t.length-1].last_line,first_column:t[t.length-(E||1)].first_column,last_column:t[t.length-1].last_column};K&&(H.ea.range=[t[t.length-(E||1)].range[0],t[t.length-1].range[1]]);r=this.performAction.apply(H,[k,F,l,q.yy,u[1],
f,t].concat(I));if("undefined"!==typeof r)return r;E&&(d=d.slice(0,-2*E),f=f.slice(0,-1*E),t=t.slice(0,-1*E));d.push(this.la[u[1]][0]);f.push(H.c);t.push(H.ea);L=g[d[d.length-2]][d[d.length-1]];d.push(L);break;case 3:return!0}}}},Ea=function(){return{EOF:1,parseError:function(a,b){if(this.yy.parser)this.yy.parser.parseError(a,b);else throw Error(a);},setInput:function(a,b){this.yy=b||this.yy||{};this._input=a;this._more=this._backtrack=this.done=!1;this.yylineno=this.yyleng=0;this.yytext=this.matched=
this.match="";this.conditionStack=["INITIAL"];this.yylloc={first_line:1,first_column:0,last_line:1,last_column:0};this.options.ranges&&(this.yylloc.range=[0,0]);this.offset=0;return this},input:function(){var a=this._input[0];this.yytext+=a;this.yyleng++;this.offset++;this.match+=a;this.matched+=a;var b=a.match(/(?:\r\n?|\n).*/g);b?(this.yylineno++,this.yylloc.last_line++):this.yylloc.last_column++;this.options.ranges&&this.yylloc.range[1]++;this._input=this._input.slice(1);return a},unput:function(a){var b=
a.length,c=a.split(/(?:\r\n?|\n)/g);this._input=a+this._input;this.yytext=this.yytext.substr(0,this.yytext.length-b);this.offset-=b;var d=this.match.split(/(?:\r\n?|\n)/g);this.match=this.match.substr(0,this.match.length-1);this.matched=this.matched.substr(0,this.matched.length-1);c.length-1&&(this.yylineno-=c.length-1);a=this.yylloc.range;this.yylloc={first_line:this.yylloc.first_line,last_line:this.yylineno+1,first_column:this.yylloc.first_column,last_column:c?(c.length===d.length?this.yylloc.first_column:
0)+d[d.length-c.length].length-c[0].length:this.yylloc.first_column-b};this.options.ranges&&(this.yylloc.range=[a[0],a[0]+this.yyleng-b]);this.yyleng=this.yytext.length;return this},more:function(){this._more=!0;return this},reject:function(){if(this.options.backtrack_lexer)this._backtrack=!0;else return this.parseError("Lexical error on line "+(this.yylineno+1)+". You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n"+this.showPosition(),
{text:"",token:null,line:this.yylineno});return this},less:function(a){this.unput(this.match.slice(a))},pastInput:function(){var a=this.matched.substr(0,this.matched.length-this.match.length);return(20<a.length?"...":"")+a.substr(-20).replace(/\n/g,"")},upcomingInput:function(){var a=this.match;20>a.length&&(a+=this._input.substr(0,20-a.length));return(a.substr(0,20)+(20<a.length?"...":"")).replace(/\n/g,"")},showPosition:function(){var a=this.pastInput(),b=Array(a.length+1).join("-");return a+this.upcomingInput()+
"\n"+b+"^"},test_match:function(a,b){var c,d;this.options.backtrack_lexer&&(d={yylineno:this.yylineno,yylloc:{first_line:this.yylloc.first_line,last_line:this.last_line,first_column:this.yylloc.first_column,last_column:this.yylloc.last_column},yytext:this.yytext,match:this.match,matches:this.matches,matched:this.matched,yyleng:this.yyleng,offset:this.offset,_more:this._more,_input:this._input,yy:this.yy,conditionStack:this.conditionStack.slice(0),done:this.done},this.options.ranges&&(d.yylloc.range=
this.yylloc.range.slice(0)));if(c=a[0].match(/(?:\r\n?|\n).*/g))this.yylineno+=c.length;this.yylloc={first_line:this.yylloc.last_line,last_line:this.yylineno+1,first_column:this.yylloc.last_column,last_column:c?c[c.length-1].length-c[c.length-1].match(/\r?\n?/)[0].length:this.yylloc.last_column+a[0].length};this.yytext+=a[0];this.match+=a[0];this.matches=a;this.yyleng=this.yytext.length;this.options.ranges&&(this.yylloc.range=[this.offset,this.offset+=this.yyleng]);this._backtrack=this._more=!1;this._input=
this._input.slice(a[0].length);this.matched+=a[0];a=this.performAction.call(this,this.yy,this,b,this.conditionStack[this.conditionStack.length-1]);this.done&&this._input&&(this.done=!1);if(a)return a;if(this._backtrack)for(var e in d)this[e]=d[e];return!1},next:function(){if(this.done)return this.EOF;this._input||(this.done=!0);var a,b,c;this._more||(this.match=this.yytext="");for(var d=this._currentRules(),e=0;e<d.length;e++)if((b=this._input.match(this.rules[d[e]]))&&(!a||b[0].length>a[0].length))if(a=
b,c=e,this.options.backtrack_lexer){a=this.test_match(b,d[e]);if(!1!==a)return a;if(this._backtrack)a=!1;else return!1}else if(!this.options.flex)break;return a?(a=this.test_match(a,d[c]),!1!==a?a:!1):""===this._input?this.EOF:this.parseError("Lexical error on line "+(this.yylineno+1)+". Unrecognized text.\n"+this.showPosition(),{text:"",token:null,line:this.yylineno})},lex:function(){var a=this.next();return a?a:this.lex()},begin:function(a){this.conditionStack.push(a)},popState:function U(){return 0<
this.conditionStack.length-1?this.conditionStack.pop():this.conditionStack[0]},_currentRules:function tb(){return this.conditionStack.length&&this.conditionStack[this.conditionStack.length-1]?this.conditions[this.conditionStack[this.conditionStack.length-1]].rules:this.conditions.INITIAL.rules},topState:function J(a){a=this.conditionStack.length-1-Math.abs(a||0);return 0<=a?this.conditionStack[a]:"INITIAL"},pushState:function n(a){this.begin(a)},stateStackSize:function Q(){return this.conditionStack.length},
options:{},performAction:function(a,b,c,d){var e=d;switch(c){case 1:return 43;case 2:return 41;case 3:return 42;case 4:return 40;case 5:return 30;case 6:return 39;case 7:return 39;case 8:return 15;case 9:return 14;case 10:return 16;case 11:return 17;case 12:return 19;case 13:return 20;case 14:return 25;case 15:return 26;case 16:return 21;case 17:return 22;case 18:return 23;case 19:return 24;case 20:return 13;case 21:return 27;case 22:return 28;case 23:return 18;case 24:return 34;case 25:return 35;
case 26:return 45;case 27:return 46;case 28:return 9;case 29:return 10;case 30:return 44;case 31:return 29;case 32:return"INVALID";case 33:return 5}},rules:[/^(?:\s+)/,/^(?:null\b)/,/^(?:true\b)/,/^(?:false\b)/,/^(?:[0-9]+(\.[0-9]+)?\b)/,/^(?:[a-zA-Z_][a-zA-Z0-9_]*)/,/^(?:'[^\']*')/,/^(?:"[^\"]*")/,/^(?:\+)/,/^(?:-)/,/^(?:\*)/,/^(?:\/)/,/^(?:&&)/,/^(?:\|\|)/,/^(?:!=)/,/^(?:==)/,/^(?:<=)/,/^(?:<)/,/^(?:>=)/,/^(?:>)/,/^(?:!)/,/^(?:\?)/,/^(?::)/,/^(?:%)/,/^(?:\[)/,/^(?:\])/,/^(?:\{)/,/^(?:\})/,/^(?:\()/,
/^(?:\))/,/^(?:,)/,/^(?:\.)/,/^(?:.)/,/^(?:$)/],conditions:{INITIAL:{rules:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33],inclusive:!0}}}}();ha.lexer=Ea;b.prototype=ha;ha.Parser=b;return new b})();function Qb(a){var b=a.match(/\s*(?:[\S]*)(?:\s+(?:-?(?:\d+(?:\.(?:\d+)?)?|\.\d+)[a-zA-Z]))?(?:\s*,)?/g);D().assert(0<b.length,"srcset has to have at least one source: %s",void 0);var c=[];for(a=0;a<b.length;a++){var d=b[a].trim();","==d.substr(-1)&&(d=d.substr(0,d.length-1).trim());var e=d.split(/\s+/,2);if(0!=e.length&&(1!=e.length||e[0])&&(2!=e.length||e[0]||e[1])){var f=e[0];if(1==e.length||2==e.length&&!e[1])c.push({url:f,width:void 0,dpr:1});else{var k=e[1].toLowerCase(),l=k.substring(k.length-
1);"w"==l?c.push({url:f,width:parseFloat(k),dpr:void 0}):"x"==l&&c.push({url:f,width:void 0,dpr:parseFloat(k)})}}}return new Rb(c)}
function Rb(a){D().assert(0<a.length,"Srcset must have at least one source");this.g=a;var b=!1,c=!1;for(a=0;a<this.g.length;a++){var d=this.g[a];D().assert((d.width||d.dpr)&&(!d.width||!d.dpr),"Either dpr or width must be specified");b=b||!!d.width;c=c||!!d.dpr}D().assert(!b||!c,"Srcset cannot have both width and dpr sources");b?this.g.sort(Sb):this.g.sort(Tb);this.Ca=b;this.ta=c}
Rb.prototype.select=function(a,b){var c=-1;if(this.Ca)a:{for(var c=-Infinity,d=this.g.length-1;0<=d;d--){var e=this.g[d].width/b;if(e>=a){c=1.1*(a-c)<e-a&&1.2>=a/c?d+1:d;break a}c=e}c=0}else if(this.ta){a=-1;c=1E6;for(d=0;d<this.g.length;d++)e=Math.abs((this.g[d].dpr||1)-b),e<c&&(c=e,a=d);c=a}return-1!=c?this.g[c]:this.getLast()};Rb.prototype.getLast=function(){return this.g[this.g.length-1]};Rb.prototype.getSources=function(){return this.g};
Rb.prototype.stringify=function(){for(var a=[],b=0;b<this.g.length;b++){var c=this.g[b];c.width?a.push(c.url+" "+c.width+"w"):c.dpr?a.push(c.url+" "+c.dpr+"x"):a.push(""+c.url)}return a.join(", ")};function Sb(a,b){D().assert(a.width!=b.width,"Duplicate width: %s",a.width);return b.width-a.width}function Tb(a,b){D().assert(a.dpr!=b.dpr,"Duplicate dpr: %s",a.dpr);return b.dpr-a.dpr};var Ub={text:null,"class":{blacklistedValueRegex:"(^|\\W)i-amphtml-"}},Vb={width:null,height:null},Wb={"AMP-BRIGHTCOVE":{"data-account":null,"data-embed":null,"data-player":null,"data-player-id":null,"data-playlist-id":null,"data-video-id":null},"AMP-CAROUSEL":{slide:null},"AMP-IFRAME":{src:null},"AMP-IMG":{alt:null,attribution:null,src:{allowedProtocols:{data:!0,http:!0,https:!0}},srcset:{alternativeName:"src"}},"AMP-LIST":{src:{allowedProtocols:{https:!0}},state:null},"AMP-SELECTOR":{selected:null},
"AMP-SORT":{"sort-by":null,"sort-direction":null,"sort-type":null},"AMP-STATE":{src:{allowedProtocols:{https:!0}}},"AMP-VIDEO":{alt:null,attribution:null,controls:null,loop:null,poster:null,preload:null,src:{allowedProtocols:{https:!0}}},"AMP-YOUTUBE":{"data-videoid":null},A:{href:{allowedProtocols:{ftp:!0,http:!0,https:!0,mailto:!0,"fb-messenger":!0,intent:!0,skype:!0,sms:!0,snapchat:!0,tel:!0,tg:!0,threema:!0,twitter:!0,viber:!0,whatsapp:!0}}},BUTTON:{disabled:null,type:null,value:null},FIELDSET:{disabled:null},
INPUT:{accept:null,accesskey:null,autocomplete:null,checked:null,disabled:null,height:null,inputmode:null,max:null,maxlength:null,min:null,minlength:null,multiple:null,pattern:null,placeholder:null,readonly:null,required:null,selectiondirection:null,size:null,spellcheck:null,step:null,type:{blacklistedValueRegex:"(^|\\s)(button|file|image|password|)(\\s|$)"},value:null,width:null},OPTION:{disabled:null,label:null,selected:null,value:null},OPTGROUP:{disabled:null,label:null},SELECT:{autofocus:null,
disabled:null,multiple:null,required:null,size:null},SOURCE:{src:{allowedProtocols:{https:!0}},type:null},TRACK:{label:null,src:{allowedProtocols:{https:!0}},srclang:null},TEXTAREA:{autocomplete:null,autofocus:null,cols:null,disabled:null,maxlength:null,minlength:null,placeholder:null,readonly:null,required:null,rows:null,selectiondirection:null,selectionend:null,selectionstart:null,spellcheck:null,wrap:null}},Xb={src:!0,srcset:!0,href:!0};function Yb(){}
Yb.prototype.canBind=function(a,b){return void 0!==Zb(a,b)};
Yb.prototype.isResultValid=function(a,b,c){var d=Zb(a,b);d&&d.alternativeName&&(d=Zb(a,d.alternativeName));if(void 0===d)return!1;if(null===d)return!0;if(c&&ta(Xb,b)){var e;if("srcset"===b){var f;try{f=Qb(c)}catch(g){return D().error("amp-bind","Failed to parse srcset: ",g),!1}e=f.getSources().map(function(a){return a.url})}else e=[c];for(a=0;a<e.length;a++)if(!$b(e[a],d))return!1}var k=d.blacklistedValueRegex;if(c&&k){var l=new RegExp(k,"i");if(l.test(c))return!1}return!0};
function $b(a,b){var c=b.allowedProtocols;return c&&a&&(a=/^([^:\/?#.]+):[\s\S]*$/.exec(a),null!==a&&(a=a[1].toLowerCase().trimLeft(),!c.hasOwnProperty(a)))?!1:!0}function Zb(a,b){var c=ta(Ub,b);if(void 0!==c)return c;var d=ta(Vb,b);if(w(a,"AMP-")&&void 0!==d)return d;var e=ta(Wb,a);if(e)return e[b]};function ac(){this.o=[]}ac.prototype.peek=function(){var a=this.o.length;return a?this.o[a-1].item:null};ac.prototype.enqueue=function(a,b){if(isNaN(b))throw Error("Priority must not be NaN.");for(var c=b,d=-1,e=0,f=this.o.length;e<=f;){d=Math.floor((e+f)/2);if(d===this.o.length)break;if(this.o[d].priority<c)e=d+1;else if(0<d&&this.o[d-1].priority>=c)f=d-1;else break}this.o.splice(d,0,{item:a,priority:b})};ac.prototype.dequeue=function(){return this.o.length?this.o.pop().item:null};
aa.Object.defineProperties(ac.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.o.length}}});var bc=/nochunking=1/.test(self.location.hash),cc=Promise.resolve();function dc(a,b){if(bc)cc.then(b);else{var c=ec,d=Xa(a),e=Ya(d);Ta(e,d,"chunk",c);S(a,"chunk").run(b,10)}}function fc(a){this.state="not_run";this.Z=a}function gc(a,b){if("run"!=a.state){a.state="run";try{a.Z(b)}catch(c){throw a.ka(c),c;}}}fc.prototype.T=function(){return this.Z.displayName||this.Z.name};fc.prototype.ka=function(){};fc.prototype.ja=function(){return!1};fc.prototype.na=function(){return!0};
function hc(a,b,c){var d=this;fc.call(this,a);this.j=b;this.G=null;c.then(function(a){d.G=a;d.G.isVisible()&&gc(d,null);d.G.onVisibilityChanged(function(){d.G.isVisible()&&gc(d,null)})})}da(hc,fc);hc.prototype.ka=function(){Fb(self.document)};hc.prototype.ja=function(){return this.G?this.G.isVisible():this.j.document.hidden?!1:!/visibilityState=(hidden|prerender)/.test(this.j.location.hash)};hc.prototype.na=function(){return!!this.G};
function ec(a){var b=this;this.Ea=a;this.j=a.win;this.R=new ac;this.fa=this.ha.bind(this);this.Ba=$a(Ya(a),"viewer");this.j.addEventListener("message",function(a){"amp-macro-task"==a.data&&b.ha(null)})}ec.prototype.run=function(a,b){var c=new fc(a);ic(this,c,b)};ec.prototype.Ia=function(a){a=new hc(a,this.j,this.Ba);ic(this,a,Number.POSITIVE_INFINITY)};function ic(a,b,c){a.R.enqueue(b,c);cc.then(function(){jc(a)})}
function kc(a,b){for(var c=a.R.peek();c&&"not_run"!==c.state;)a.R.dequeue(),c=a.R.peek();c&&b&&a.R.dequeue();return c}ec.prototype.ha=function(a){var b=this,c=kc(this,!0);if(!c)return!1;var d=Date.now();gc(c,a);cc.then(function(){jc(b)});return!0};function lc(a){cc.then(function(){a.fa(null)})}function jc(a){var b=kc(a);b&&(b.ja()?lc(a):b.na()&&a.j.requestIdleCallback?mc(a.j,a.fa):a.j.postMessage("amp-macro-task","*"))}
function mc(a,b){var c=15,d=2E3;function e(k){if(k.timeRemaining()<c){var l=d-(Date.now()-f);0>=l||k.didTimeout?b(k):a.requestIdleCallback(e,{timeout:l})}else b(k)}var f=Date.now();a.requestIdleCallback(e,{timeout:d})};function nc(a,b,c){var d="ww";a=b?a.protocol+"//"+a.host+"/dist":xa;return c?a+"/rtv/"+y().rtvVersion+"/"+d+".js":a+"/"+d+".js"};function pc(a){var b=this;this.j=a;this.Da=Va(a,"xhr");var c=a.location,d=!1,e=!d,f=nc(c,d,e);this.da=null;this.ia=this.Da.fetchText(f,{ampCors:!1}).then(function(a){return a.text()}).then(function(c){c=new a.Blob([c],{type:"text/javascript"});var d=a.URL.createObjectURL(c);b.da=new a.Worker(d);b.da.onmessage=b.ya.bind(b)});this.U={};this.ra=0;this.pa=[a]}
function qc(a,b,c,d){return a.ia.then(function(){return new Promise(function(e,f){var k=a.ra++;a.U[k]={method:b,resolve:e,reject:f};e=d||a.j;f=a.pa.indexOf(e);e=0<=f?f:a.pa.push(e)-1;a.da.postMessage({method:b,args:c,scope:e,id:k})})})}pc.prototype.ya=function(a){var b=a.data;a=b.method;var c=b.returnValue,b=b.id,d=this.U[b];d?(d.resolve(c),delete this.U[b]):qa().error("web-worker","Received unexpected message ("+a+", "+b+") from worker.")};pc.prototype.hasPendingMessages=function(){return 0<Object.keys(this.U).length};
pc.prototype.Ga=function(){return this.ia};var rc=function(){function a(a){var b=(""+a).match(r);return b?new g(m(b[1]),m(b[2]),m(b[3]),m(b[4]),m(b[5]),m(b[6]),m(b[7])):null}function b(a,b,f,k,l,h,m){a=new g(d(a,z),d(b,z),c(f),0<k?k.toString():null,d(l,G),null,c(m));h&&("string"===typeof h?a.setRawQuery(h.replace(/[^?&=0-9A-Za-z_\-~.%]/g,e)):a.setAllParameters(h));return a}function c(a){return"string"==typeof a?encodeURIComponent(a):null}function d(a,b){return"string"==typeof a?encodeURI(a).replace(b,e):null}function e(a){a=a.charCodeAt(0);
return"%"+"0123456789ABCDEF".charAt(a>>4&15)+"0123456789ABCDEF".charAt(a&15)}function f(a){return a.replace(/(^|\/)\.(?:\/|$)/g,"$1").replace(/\/{2,}/g,"/")}function k(a){if(null===a)return null;a=f(a);for(var b=q,c;(c=a.replace(b,"$1"))!=a;a=c);return a}function l(a,b){var c=a.clone(),d=b.hasScheme();d?c.setRawScheme(b.getRawScheme()):d=b.hasCredentials();d?c.setRawCredentials(b.getRawCredentials()):d=b.hasDomain();d?c.setRawDomain(b.getRawDomain()):d=b.hasPort();var e=b.getRawPath(),f=k(e);if(d)c.setPort(b.getPort()),
f=f&&f.replace(p,"");else if(d=!!e){if(47!==f.charCodeAt(0))var t=k(c.getRawPath()||"").replace(p,""),g=t.lastIndexOf("/")+1,f=k((g?t.substring(0,g):"")+k(e)).replace(p,"")}else f=f&&f.replace(p,""),f!==e&&c.setRawPath(f);d?c.setRawPath(f):d=b.hasQuery();d?c.setRawQuery(b.getRawQuery()):d=b.hasFragment();d&&c.setRawFragment(b.getRawFragment());return c}function g(a,b,c,d,e,f,g){this.F=a;this.w=b;this.C=c;this.H=d;this.m=e;this.l=f;this.D=g;this.f=null}function m(a){return"string"==typeof a&&0<a.length?
a:null}var h=/(\/|^)(?:[^./][^/]*|\.{2,}(?:[^./][^/]*)|\.{3,}[^/]*)\/\.\.(?:\/|$)/,q=new RegExp(h),p=/^(?:\.\.\/)*(?:\.\.$)?/;g.prototype.toString=function(){var a=[];null!==this.F&&a.push(this.F,":");null!==this.C&&(a.push("//"),null!==this.w&&a.push(this.w,"@"),a.push(this.C),null!==this.H&&a.push(":",this.H.toString()));null!==this.m&&a.push(this.m);null!==this.l&&a.push("?",this.l);null!==this.D&&a.push("#",this.D);return a.join("")};g.prototype.clone=function(){return new g(this.F,this.w,this.C,
this.H,this.m,this.l,this.D)};g.prototype.getScheme=function(){return this.F&&decodeURIComponent(this.F).toLowerCase()};g.prototype.getRawScheme=function(){return this.F};g.prototype.setScheme=function(a){this.F=d(a,z);return this};g.prototype.setRawScheme=function(a){this.F=a?a:null;return this};g.prototype.hasScheme=function(){return null!==this.F};g.prototype.getCredentials=function(){return this.w&&decodeURIComponent(this.w)};g.prototype.getRawCredentials=function(){return this.w};g.prototype.setCredentials=
function(a){this.w=d(a,z);return this};g.prototype.setRawCredentials=function(a){this.w=a?a:null;return this};g.prototype.hasCredentials=function(){return null!==this.w};g.prototype.getDomain=function(){return this.C&&decodeURIComponent(this.C)};g.prototype.getRawDomain=function(){return this.C};g.prototype.setDomain=function(a){return this.setRawDomain(a&&encodeURIComponent(a))};g.prototype.setRawDomain=function(a){this.C=a?a:null;return this.setRawPath(this.m)};g.prototype.hasDomain=function(){return null!==
this.C};g.prototype.getPort=function(){return this.H&&decodeURIComponent(this.H)};g.prototype.setPort=function(a){if(a){a=Number(a);if(a!==(a&65535))throw Error("Bad port number "+a);this.H=""+a}else this.H=null;return this};g.prototype.hasPort=function(){return null!==this.H};g.prototype.getPath=function(){return this.m&&decodeURIComponent(this.m)};g.prototype.getRawPath=function(){return this.m};g.prototype.setPath=function(a){return this.setRawPath(d(a,G))};g.prototype.setRawPath=function(a){a?
(a=String(a),this.m=!this.C||/^\//.test(a)?a:"/"+a):this.m=null;return this};g.prototype.hasPath=function(){return null!==this.m};g.prototype.getQuery=function(){return this.l&&decodeURIComponent(this.l).replace(/\+/g," ")};g.prototype.getRawQuery=function(){return this.l};g.prototype.setQuery=function(a){this.f=null;this.l=c(a);return this};g.prototype.setRawQuery=function(a){this.f=null;this.l=a?a:null;return this};g.prototype.hasQuery=function(){return null!==this.l};g.prototype.setAllParameters=
function(a){if("object"===typeof a&&!(a instanceof Array)&&(a instanceof Object||"[object Array]"!==Object.prototype.toString.call(a))){var b=[],c=-1,d;for(d in a){var e=a[d];"string"===typeof e&&(b[++c]=d,b[++c]=e)}a=b}this.f=null;for(var f=[],g="",k=0;k<a.length;)d=a[k++],e=a[k++],f.push(g,encodeURIComponent(d.toString())),g="&",e&&f.push("=",encodeURIComponent(e.toString()));this.l=f.join("");return this};g.prototype.P=function(){if(!this.f){var a=this.l;if(a){for(var b=a.split(/[&\?]/),a=[],c=
-1,d=0;d<b.length;++d){var e=b[d].match(/^([^=]*)(?:=(.*))?$/);a[++c]=decodeURIComponent(e[1]).replace(/\+/g," ");a[++c]=decodeURIComponent(e[2]||"").replace(/\+/g," ")}this.f=a}else this.f=[]}};g.prototype.setParameterValues=function(a,b){"string"===typeof b&&(b=[b]);this.P();for(var c=0,d=this.f,e=[],f=0;f<d.length;f+=2)a===d[f]?c<b.length&&e.push(a,b[c++]):e.push(d[f],d[f+1]);for(;c<b.length;)e.push(a,b[c++]);this.setAllParameters(e);return this};g.prototype.removeParameter=function(a){return this.setParameterValues(a,
[])};g.prototype.getAllParameters=function(){this.P();return this.f.slice(0,this.f.length)};g.prototype.getParameterValues=function(a){this.P();for(var b=[],c=0;c<this.f.length;c+=2)a===this.f[c]&&b.push(this.f[c+1]);return b};g.prototype.getParameterMap=function(){this.P();for(var a={},b=0;b<this.f.length;b+=2){var c=this.f[b++],d=this.f[b++];c in a?a[c].push(d):a[c]=[d]}return a};g.prototype.getParameterValue=function(a){this.P();for(var b=0;b<this.f.length;b+=2)if(a===this.f[b])return this.f[b+
1];return null};g.prototype.getFragment=function(){return this.D&&decodeURIComponent(this.D)};g.prototype.getRawFragment=function(){return this.D};g.prototype.setFragment=function(a){this.D=a?encodeURIComponent(a):null;return this};g.prototype.setRawFragment=function(a){this.D=a?a:null;return this};g.prototype.hasFragment=function(){return null!==this.D};var r=/^(?:([^:/?#]+):)?(?:\/\/(?:([^/?#]*)@)?([^/?#:@]*)(?::([0-9]+))?)?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,z=/[#\/\?@]/g,G=/[\#\?]/g;g.parse=a;
g.create=b;g.resolve=l;g.collapse_dots=k;g.utils={mimeTypeOf:function(b){var c=a(b);return/\.html$/.test(c.getPath())?"text/html":"application/javascript"},resolve:function(b,c){return b?l(a(b),a(c)).toString():""+c}};return g}(),Z={atype:{NONE:0,URI:1,URI_FRAGMENT:11,SCRIPT:2,STYLE:3,HTML:12,ID:4,IDREF:5,IDREFS:6,GLOBAL_NAME:7,LOCAL_NAME:8,CLASSES:9,FRAME_TARGET:10,MEDIA_QUERY:13}};Z.atype=Z.atype;
Z.ATTRIBS={"*::class":9,"*::dir":0,"*::draggable":0,"*::hidden":0,"*::id":4,"*::inert":0,"*::itemprop":0,"*::itemref":6,"*::itemscope":0,"*::lang":0,"*::onblur":2,"*::onchange":2,"*::onclick":2,"*::ondblclick":2,"*::onerror":2,"*::onfocus":2,"*::onkeydown":2,"*::onkeypress":2,"*::onkeyup":2,"*::onload":2,"*::onmousedown":2,"*::onmousemove":2,"*::onmouseout":2,"*::onmouseover":2,"*::onmouseup":2,"*::onreset":2,"*::onscroll":2,"*::onselect":2,"*::onsubmit":2,"*::ontouchcancel":2,"*::ontouchend":2,"*::ontouchenter":2,
"*::ontouchleave":2,"*::ontouchmove":2,"*::ontouchstart":2,"*::onunload":2,"*::spellcheck":0,"*::style":3,"*::tabindex":0,"*::title":0,"*::translate":0,"a::accesskey":0,"a::coords":0,"a::href":1,"a::hreflang":0,"a::name":7,"a::onblur":2,"a::onfocus":2,"a::shape":0,"a::target":10,"a::type":0,"area::accesskey":0,"area::alt":0,"area::coords":0,"area::href":1,"area::nohref":0,"area::onblur":2,"area::onfocus":2,"area::shape":0,"area::target":10,"audio::controls":0,"audio::loop":0,"audio::mediagroup":5,
"audio::muted":0,"audio::preload":0,"audio::src":1,"bdo::dir":0,"blockquote::cite":1,"br::clear":0,"button::accesskey":0,"button::disabled":0,"button::name":8,"button::onblur":2,"button::onfocus":2,"button::type":0,"button::value":0,"canvas::height":0,"canvas::width":0,"caption::align":0,"col::align":0,"col::char":0,"col::charoff":0,"col::span":0,"col::valign":0,"col::width":0,"colgroup::align":0,"colgroup::char":0,"colgroup::charoff":0,"colgroup::span":0,"colgroup::valign":0,"colgroup::width":0,
"command::checked":0,"command::command":5,"command::disabled":0,"command::icon":1,"command::label":0,"command::radiogroup":0,"command::type":0,"data::value":0,"del::cite":1,"del::datetime":0,"details::open":0,"dir::compact":0,"div::align":0,"dl::compact":0,"fieldset::disabled":0,"font::color":0,"font::face":0,"font::size":0,"form::accept":0,"form::action":1,"form::autocomplete":0,"form::enctype":0,"form::method":0,"form::name":7,"form::novalidate":0,"form::onreset":2,"form::onsubmit":2,"form::target":10,
"h1::align":0,"h2::align":0,"h3::align":0,"h4::align":0,"h5::align":0,"h6::align":0,"hr::align":0,"hr::noshade":0,"hr::size":0,"hr::width":0,"iframe::align":0,"iframe::frameborder":0,"iframe::height":0,"iframe::marginheight":0,"iframe::marginwidth":0,"iframe::width":0,"img::align":0,"img::alt":0,"img::border":0,"img::height":0,"img::hspace":0,"img::ismap":0,"img::name":7,"img::src":1,"img::usemap":11,"img::vspace":0,"img::width":0,"input::accept":0,"input::accesskey":0,"input::align":0,"input::alt":0,
"input::autocomplete":0,"input::checked":0,"input::disabled":0,"input::inputmode":0,"input::ismap":0,"input::list":5,"input::max":0,"input::maxlength":0,"input::min":0,"input::multiple":0,"input::name":8,"input::onblur":2,"input::onchange":2,"input::onfocus":2,"input::onselect":2,"input::pattern":0,"input::placeholder":0,"input::readonly":0,"input::required":0,"input::size":0,"input::src":1,"input::step":0,"input::type":0,"input::usemap":11,"input::value":0,"ins::cite":1,"ins::datetime":0,"label::accesskey":0,
"label::for":5,"label::onblur":2,"label::onfocus":2,"legend::accesskey":0,"legend::align":0,"li::type":0,"li::value":0,"map::name":7,"menu::compact":0,"menu::label":0,"menu::type":0,"meter::high":0,"meter::low":0,"meter::max":0,"meter::min":0,"meter::optimum":0,"meter::value":0,"ol::compact":0,"ol::reversed":0,"ol::start":0,"ol::type":0,"optgroup::disabled":0,"optgroup::label":0,"option::disabled":0,"option::label":0,"option::selected":0,"option::value":0,"output::for":6,"output::name":8,"p::align":0,
"pre::width":0,"progress::max":0,"progress::min":0,"progress::value":0,"q::cite":1,"select::autocomplete":0,"select::disabled":0,"select::multiple":0,"select::name":8,"select::onblur":2,"select::onchange":2,"select::onfocus":2,"select::required":0,"select::size":0,"source::type":0,"table::align":0,"table::bgcolor":0,"table::border":0,"table::cellpadding":0,"table::cellspacing":0,"table::frame":0,"table::rules":0,"table::summary":0,"table::width":0,"tbody::align":0,"tbody::char":0,"tbody::charoff":0,
"tbody::valign":0,"td::abbr":0,"td::align":0,"td::axis":0,"td::bgcolor":0,"td::char":0,"td::charoff":0,"td::colspan":0,"td::headers":6,"td::height":0,"td::nowrap":0,"td::rowspan":0,"td::scope":0,"td::valign":0,"td::width":0,"textarea::accesskey":0,"textarea::autocomplete":0,"textarea::cols":0,"textarea::disabled":0,"textarea::inputmode":0,"textarea::name":8,"textarea::onblur":2,"textarea::onchange":2,"textarea::onfocus":2,"textarea::onselect":2,"textarea::placeholder":0,"textarea::readonly":0,"textarea::required":0,
"textarea::rows":0,"textarea::wrap":0,"tfoot::align":0,"tfoot::char":0,"tfoot::charoff":0,"tfoot::valign":0,"th::abbr":0,"th::align":0,"th::axis":0,"th::bgcolor":0,"th::char":0,"th::charoff":0,"th::colspan":0,"th::headers":6,"th::height":0,"th::nowrap":0,"th::rowspan":0,"th::scope":0,"th::valign":0,"th::width":0,"thead::align":0,"thead::char":0,"thead::charoff":0,"thead::valign":0,"tr::align":0,"tr::bgcolor":0,"tr::char":0,"tr::charoff":0,"tr::valign":0,"track::default":0,"track::kind":0,"track::label":0,
"track::srclang":0,"ul::compact":0,"ul::type":0,"video::controls":0,"video::height":0,"video::loop":0,"video::mediagroup":5,"video::muted":0,"video::poster":1,"video::preload":0,"video::src":1,"video::width":0};Z.ATTRIBS=Z.ATTRIBS;Z.eflags={OPTIONAL_ENDTAG:1,EMPTY:2,CDATA:4,RCDATA:8,UNSAFE:16,FOLDABLE:32,SCRIPT:64,STYLE:128,VIRTUALIZED:256};Z.eflags=Z.eflags;
Z.ELEMENTS={a:0,abbr:0,acronym:0,address:0,applet:272,area:2,article:0,aside:0,audio:0,b:0,base:274,basefont:274,bdi:0,bdo:0,big:0,blockquote:0,body:305,br:2,button:0,canvas:0,caption:0,center:0,cite:0,code:0,col:2,colgroup:1,command:2,data:0,datalist:0,dd:1,del:0,details:0,dfn:0,dialog:272,dir:0,div:0,dl:0,dt:1,em:0,fieldset:0,figcaption:0,figure:0,font:0,footer:0,form:0,frame:274,frameset:272,h1:0,h2:0,h3:0,h4:0,h5:0,h6:0,head:305,header:0,hgroup:0,hr:2,html:305,i:0,iframe:4,img:2,input:2,ins:0,
isindex:274,kbd:0,keygen:274,label:0,legend:0,li:1,link:274,map:0,mark:0,menu:0,meta:274,meter:0,nav:0,nobr:0,noembed:276,noframes:276,noscript:276,object:272,ol:0,optgroup:0,option:1,output:0,p:1,param:274,pre:0,progress:0,q:0,s:0,samp:0,script:84,section:0,select:0,small:0,source:2,span:0,strike:0,strong:0,style:148,sub:0,summary:0,sup:0,table:0,tbody:1,td:1,textarea:8,tfoot:1,th:1,thead:1,time:0,title:280,tr:1,track:2,tt:0,u:0,ul:0,"var":0,video:0,wbr:2};Z.ELEMENTS=Z.ELEMENTS;
Z.ELEMENT_DOM_INTERFACES={a:"HTMLAnchorElement",abbr:"HTMLElement",acronym:"HTMLElement",address:"HTMLElement",applet:"HTMLAppletElement",area:"HTMLAreaElement",article:"HTMLElement",aside:"HTMLElement",audio:"HTMLAudioElement",b:"HTMLElement",base:"HTMLBaseElement",basefont:"HTMLBaseFontElement",bdi:"HTMLElement",bdo:"HTMLElement",big:"HTMLElement",blockquote:"HTMLQuoteElement",body:"HTMLBodyElement",br:"HTMLBRElement",button:"HTMLButtonElement",canvas:"HTMLCanvasElement",caption:"HTMLTableCaptionElement",
center:"HTMLElement",cite:"HTMLElement",code:"HTMLElement",col:"HTMLTableColElement",colgroup:"HTMLTableColElement",command:"HTMLCommandElement",data:"HTMLElement",datalist:"HTMLDataListElement",dd:"HTMLElement",del:"HTMLModElement",details:"HTMLDetailsElement",dfn:"HTMLElement",dialog:"HTMLDialogElement",dir:"HTMLDirectoryElement",div:"HTMLDivElement",dl:"HTMLDListElement",dt:"HTMLElement",em:"HTMLElement",fieldset:"HTMLFieldSetElement",figcaption:"HTMLElement",figure:"HTMLElement",font:"HTMLFontElement",
footer:"HTMLElement",form:"HTMLFormElement",frame:"HTMLFrameElement",frameset:"HTMLFrameSetElement",h1:"HTMLHeadingElement",h2:"HTMLHeadingElement",h3:"HTMLHeadingElement",h4:"HTMLHeadingElement",h5:"HTMLHeadingElement",h6:"HTMLHeadingElement",head:"HTMLHeadElement",header:"HTMLElement",hgroup:"HTMLElement",hr:"HTMLHRElement",html:"HTMLHtmlElement",i:"HTMLElement",iframe:"HTMLIFrameElement",img:"HTMLImageElement",input:"HTMLInputElement",ins:"HTMLModElement",isindex:"HTMLUnknownElement",kbd:"HTMLElement",
keygen:"HTMLKeygenElement",label:"HTMLLabelElement",legend:"HTMLLegendElement",li:"HTMLLIElement",link:"HTMLLinkElement",map:"HTMLMapElement",mark:"HTMLElement",menu:"HTMLMenuElement",meta:"HTMLMetaElement",meter:"HTMLMeterElement",nav:"HTMLElement",nobr:"HTMLElement",noembed:"HTMLElement",noframes:"HTMLElement",noscript:"HTMLElement",object:"HTMLObjectElement",ol:"HTMLOListElement",optgroup:"HTMLOptGroupElement",option:"HTMLOptionElement",output:"HTMLOutputElement",p:"HTMLParagraphElement",param:"HTMLParamElement",
pre:"HTMLPreElement",progress:"HTMLProgressElement",q:"HTMLQuoteElement",s:"HTMLElement",samp:"HTMLElement",script:"HTMLScriptElement",section:"HTMLElement",select:"HTMLSelectElement",small:"HTMLElement",source:"HTMLSourceElement",span:"HTMLSpanElement",strike:"HTMLElement",strong:"HTMLElement",style:"HTMLStyleElement",sub:"HTMLElement",summary:"HTMLElement",sup:"HTMLElement",table:"HTMLTableElement",tbody:"HTMLTableSectionElement",td:"HTMLTableDataCellElement",textarea:"HTMLTextAreaElement",tfoot:"HTMLTableSectionElement",
th:"HTMLTableHeaderCellElement",thead:"HTMLTableSectionElement",time:"HTMLTimeElement",title:"HTMLTitleElement",tr:"HTMLTableRowElement",track:"HTMLTrackElement",tt:"HTMLElement",u:"HTMLElement",ul:"HTMLUListElement","var":"HTMLElement",video:"HTMLVideoElement",wbr:"HTMLElement"};Z.ELEMENT_DOM_INTERFACES=Z.ELEMENT_DOM_INTERFACES;Z.ueffects={NOT_LOADED:0,SAME_DOCUMENT:1,NEW_DOCUMENT:2};Z.ueffects=Z.ueffects;
Z.URIEFFECTS={"a::href":2,"area::href":2,"audio::src":1,"blockquote::cite":0,"command::icon":1,"del::cite":0,"form::action":2,"img::src":1,"input::src":1,"ins::cite":0,"q::cite":0,"video::poster":1,"video::src":1};Z.URIEFFECTS=Z.URIEFFECTS;Z.ltypes={UNSANDBOXED:2,SANDBOXED:1,DATA:0};Z.ltypes=Z.ltypes;
Z.LOADERTYPES={"a::href":2,"area::href":2,"audio::src":2,"blockquote::cite":2,"command::icon":1,"del::cite":2,"form::action":2,"img::src":1,"input::src":1,"ins::cite":2,"q::cite":2,"video::poster":1,"video::src":2};Z.LOADERTYPES=Z.LOADERTYPES;
(function(a){function b(a){if(A.hasOwnProperty(a))return A[a];var b=a.match(ya);return b?String.fromCharCode(parseInt(b[1],10)):(b=a.match(za))?String.fromCharCode(parseInt(b[1],16)):ba&&X.test(a)?(ba.innerHTML="&"+a+";",b=ba.textContent,A[a]=b):"&"+a+";"}function c(a,c){return b(c)}function d(a){return a.replace(Aa,"")}function e(a){return a.replace(Ba,c)}function f(a){return(""+a).replace(ga,"&amp;").replace(ha,"&lt;").replace(Ea,"&gt;").replace(oc,"&#34;")}function k(a){return a.replace(Da,"&amp;$1").replace(ha,
"&lt;").replace(Ea,"&gt;")}function l(a){var b={cdata:a.cdata||a.cdata,comment:a.comment||a.comment,endDoc:a.endDoc||a.endDoc,endTag:a.endTag||a.endTag,pcdata:a.pcdata||a.pcdata,rcdata:a.rcdata||a.rcdata,startDoc:a.startDoc||a.startDoc,startTag:a.startTag||a.startTag};return function(a,c){var d=b,e=h(a);m(d,e,0,{noMoreGT:!1,noMoreEndComments:!1},c)}}function g(a,b,c,d,e){return function(){m(a,b,c,d,e)}}function m(b,c,d,e,f){try{b.startDoc&&0==d&&b.startDoc(f);for(var n,k,l,h=d,Q=c.length;h<Q;){var m=
c[h++],ca=c[h];switch(m){case "&":Ca.test(ca)?(b.pcdata&&b.pcdata("&"+ca,f,M,g(b,c,h,e,f)),h++):b.pcdata&&b.pcdata("&amp;",f,M,g(b,c,h,e,f));break;case "</":(n=/^([-\w:]+)[^\'\"]*/.exec(ca))?n[0].length===ca.length&&">"===c[h+1]?(h+=2,l=n[1].toLowerCase(),b.endTag&&b.endTag(l,f,M,g(b,c,h,e,f))):h=q(c,h,b,f,M,e):b.pcdata&&b.pcdata("&lt;/",f,M,g(b,c,h,e,f));break;case "<":if(n=/^([-\w:]+)\s*\/?/.exec(ca))if(n[0].length===ca.length&&">"===c[h+1]){h+=2;l=n[1].toLowerCase();b.startTag&&b.startTag(l,[],
f,M,g(b,c,h,e,f));var vb=a.ELEMENTS[l];vb&Sa&&(h=r(c,{name:l,next:h,eflags:vb},b,f,M,e))}else h=p(c,h,b,f,M,e);else b.pcdata&&b.pcdata("&lt;",f,M,g(b,c,h,e,f));break;case "\x3c!--":if(!e.noMoreEndComments){for(k=h+1;k<Q&&(">"!==c[k]||!/--$/.test(c[k-1]));k++);if(k<Q){if(b.comment){var ub=c.slice(h,k).join("");b.comment(ub.substr(0,ub.length-2),f,M,g(b,c,k+1,e,f))}h=k+1}else e.noMoreEndComments=!0}e.noMoreEndComments&&b.pcdata&&b.pcdata("&lt;!--",f,M,g(b,c,h,e,f));break;case "<!":if(/^\w/.test(ca)){if(!e.noMoreGT){for(k=
h+1;k<Q&&">"!==c[k];k++);k<Q?h=k+1:e.noMoreGT=!0}e.noMoreGT&&b.pcdata&&b.pcdata("&lt;!",f,M,g(b,c,h,e,f))}else b.pcdata&&b.pcdata("&lt;!",f,M,g(b,c,h,e,f));break;case "<?":if(!e.noMoreGT){for(k=h+1;k<Q&&">"!==c[k];k++);k<Q?h=k+1:e.noMoreGT=!0}e.noMoreGT&&b.pcdata&&b.pcdata("&lt;?",f,M,g(b,c,h,e,f));break;case ">":b.pcdata&&b.pcdata("&gt;",f,M,g(b,c,h,e,f));break;case "":break;default:b.pcdata&&b.pcdata(m,f,M,g(b,c,h,e,f))}}b.endDoc&&b.endDoc(f)}catch(wb){if(wb!==M)throw wb;}}function h(a){var b=/(<\/|<\!--|<[!?]|[&<>])/g;
a+="";if(sb)return a.split(b);for(var c=[],d=0,e;null!==(e=b.exec(a));)c.push(a.substring(d,e.index)),c.push(e[0]),d=e.index+e[0].length;c.push(a.substring(d));return c}function q(a,b,c,d,e,f){var k=z(a,b);if(!k)return a.length;c.endTag&&c.endTag(k.name,d,e,g(c,a,b,f,d));return k.next}function p(a,b,c,d,e,f){b=z(a,b);if(!b)return a.length;c.startTag&&c.startTag(b.name,b.attrs,d,e,g(c,a,b.next,f,d));return b.eflags&Sa?r(a,b,c,d,e,f):b.next}function r(b,c,d,e,f,h){var n=b.length;U.hasOwnProperty(c.name)||
(U[c.name]=new RegExp("^"+c.name+"(?:[\\s\\/]|$)","i"));for(var l=U[c.name],m=c.next,p=c.next+1;p<n&&("</"!==b[p-1]||!l.test(b[p]));p++);p<n&&--p;var Q=b.slice(m,p).join("");if(c.eflags&a.eflags.CDATA)d.cdata&&d.cdata(Q,e,f,g(d,b,p,h,e));else if(c.eflags&a.eflags.RCDATA)d.rcdata&&d.rcdata(k(Q),e,f,g(d,b,p,h,e));else throw Error("bug");return p}function z(b,c){var d=/^([-\w:]+)/.exec(b[c]),e={};e.name=d[1].toLowerCase();e.eflags=a.ELEMENTS[e.name];var f=b[c].substr(d[0].length);c+=1;for(var k=b.length;c<
k&&">"!==b[c];c++)f+=b[c];if(!(k<=c)){for(var g=[];""!==f;)if(d=rb.exec(f))if(d[4]&&!d[5]||d[6]&&!d[7]){for(var h=d[4]||d[6],n=!1,l=[f,b[c++]];c<k;c++){if(n){if(">"===b[c])break}else 0<=b[c].indexOf(h)&&(n=!0);l.push(b[c])}if(k<=c)break;f=l.join("")}else{var p=d[1].toLowerCase(),m=d[2]?G(d[3]):"";g.push(p,m);f=f.substr(d[0].length)}else f=f.replace(/^[\s\S][^a-z\s]*/,"");e.attrs=g;e.next=c+1;return e}}function G(a){var b=a.charCodeAt(0);if(34===b||39===b)a=a.substr(1,a.length-2);return e(d(a))}function t(b){function c(a,
b){e||b.push(a)}var d,e;return l({startDoc:function(){d=[];e=!1},startTag:function(c,k,g){if(!e&&a.ELEMENTS.hasOwnProperty(c)){var h=a.ELEMENTS[c];if(!(h&a.eflags.FOLDABLE)){var l=b(c,k);if(l){if("object"!==typeof l)throw Error("tagPolicy did not return object (old API?)");if("attribs"in l)k=l.attribs;else throw Error("tagPolicy gave no attribs");var n,p;"tagName"in l?(p=l.tagName,n=a.ELEMENTS[p]):(p=c,n=h);if(h&a.eflags.OPTIONAL_ENDTAG){var m=d[d.length-1];!m||m.orig!==c||m.rep===p&&c===p||g.push("</",
m.rep,">")}h&a.eflags.EMPTY||d.push({orig:c,rep:p});g.push("<",p);for(var q=0,r=k.length;q<r;q+=2){var t=k[q],z=k[q+1];null!==z&&void 0!==z&&g.push(" ",t,'="',f(z),'"')}g.push(">");h&a.eflags.EMPTY&&!(n&a.eflags.EMPTY)&&g.push("</",p,">")}else e=!(h&a.eflags.EMPTY)}}},endTag:function(b,c){if(e)e=!1;else if(a.ELEMENTS.hasOwnProperty(b)){var f=a.ELEMENTS[b];if(!(f&(a.eflags.EMPTY|a.eflags.FOLDABLE))){if(f&a.eflags.OPTIONAL_ENDTAG)for(f=d.length;0<=--f;){var k=d[f].orig;if(k===b)break;if(!(a.ELEMENTS[k]&
a.eflags.OPTIONAL_ENDTAG))return}else for(f=d.length;0<=--f&&d[f].orig!==b;);if(!(0>f)){for(var g=d.length;--g>f;){var h=d[g].rep;a.ELEMENTS[h]&a.eflags.OPTIONAL_ENDTAG||c.push("</",h,">")}f<d.length&&(b=d[f].rep);d.length=f;c.push("</",b,">")}}}},pcdata:c,rcdata:c,cdata:c,endDoc:function(a){for(;d.length;d.length--)a.push("</",d[d.length-1].rep,">")}})}function F(a,b,c,d,e){if(!e)return null;try{var f=rc.parse(""+a);if(f&&(!f.hasScheme()||tb.test(f.getScheme()))){var k=e(f,b,c,d);return k?k.toString():
null}}catch(Nc){}return null}function B(a,b,c,d,f){c||a(b+" removed",{change:"removed",tagName:b});if(d!==f){var e="changed";d&&!f?e="removed":!d&&f&&(e="added");a(b+"."+c+" "+e,{change:e,tagName:b,attribName:c,oldValue:d,newValue:f})}}function I(a,b,c){var d;d=b+"::"+c;if(a.hasOwnProperty(d))return a[d];d="*::"+c;if(a.hasOwnProperty(d))return a[d]}function C(b,c){return I(a.ATTRIBS,b,c)}function K(b,c){return I(a.LOADERTYPES,b,c)}function H(b,c){return I(a.URIEFFECTS,b,c)}function E(b,c,d,f,e){for(var k=
0;k<c.length;k+=2){var g=c[k],h=c[k+1],l=h,p=null,m;if((m=b+"::"+g,a.ATTRIBS.hasOwnProperty(m))||(m="*::"+g,a.ATTRIBS.hasOwnProperty(m)))p=a.ATTRIBS[m];if(null!==p)switch(p){case a.atype.NONE:break;case a.atype.SCRIPT:h=null;e&&B(e,b,g,l,h);break;case a.atype.STYLE:if("undefined"===typeof P){h=null;e&&B(e,b,g,l,h);break}var n=[];P(h,{declaration:function(b,c){var e=b.toLowerCase();x(e,c,d?function(b){return F(b,a.ueffects.SAME_DOCUMENT,a.ltypes.SANDBOXED,{TYPE:"CSS",CSS_PROP:e},d)}:null);c.length&&
n.push(e+": "+c.join(" "))}});h=0<n.length?n.join(" ; "):null;e&&B(e,b,g,l,h);break;case a.atype.ID:case a.atype.IDREF:case a.atype.IDREFS:case a.atype.GLOBAL_NAME:case a.atype.LOCAL_NAME:case a.atype.CLASSES:h=f?f(h):h;e&&B(e,b,g,l,h);break;case a.atype.URI:h=F(h,H(b,g),K(b,g),{TYPE:"MARKUP",XML_ATTR:g,XML_TAG:b},d);e&&B(e,b,g,l,h);break;case a.atype.URI_FRAGMENT:h&&"#"===h.charAt(0)?(h=h.substring(1),h=f?f(h):h,null!==h&&void 0!==h&&(h="#"+h)):h=null;e&&B(e,b,g,l,h);break;default:h=null,e&&B(e,
b,g,l,h)}else h=null,e&&B(e,b,g,l,h);c[k+1]=h}return c}function L(b,c,d){return function(e,f){if(a.ELEMENTS[e]&a.eflags.UNSAFE)d&&B(d,e,void 0,void 0,void 0);else return{attribs:E(e,f,b,c,d)}}}function N(a,b){var c=[];t(b)(a,c);return c.join("")}function O(a,b,c,d){b=L(b,c,d);return N(a,b)}var P,x,u;"undefined"!==typeof window&&(P=window.parseCssDeclarations,x=window.sanitizeCssProperty,u=window.cssSchema);var A={lt:"<",LT:"<",gt:">",GT:">",amp:"&",AMP:"&",quot:'"',apos:"'",nbsp:"\u00a0"},ya=/^#(\d+)$/,
za=/^#x([0-9A-Fa-f]+)$/,X=/^[A-Za-z][A-za-z0-9]+$/,ba="undefined"!==typeof window&&window.document?window.document.createElement("textarea"):null,Aa=/\0/g,Ba=/&(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/g,Ca=/^(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/,ga=/&/g,Da=/&([^a-z#]|#(?:[^0-9x]|x(?:[^0-9a-f]|$)|$)|$)/gi,ha=/[<]/g,Ea=/>/g,oc=/\"/g,rb=/^\s*(\[[-.:\w]+\]|[-.:\w]+)(?:\s*(=)\s*((")[^"]*("|$)|(')[^']*('|$)|(?=[a-z][-\w]*\s*=)|[^"'\s]*))?/i,sb=3==="a,b".split(/(,)/).length,Sa=a.eflags.CDATA|a.eflags.RCDATA,M={},U=
{},tb=/^(?:https?|mailto)$/i,J={};J.escapeAttrib=J.escapeAttrib=f;J.makeHtmlSanitizer=J.makeHtmlSanitizer=t;J.makeSaxParser=J.makeSaxParser=l;J.makeTagPolicy=J.makeTagPolicy=L;J.normalizeRCData=J.normalizeRCData=k;J.sanitize=J.sanitize=O;J.sanitizeAttribs=J.sanitizeAttribs=E;J.sanitizeWithPolicy=J.sanitizeWithPolicy=N;J.unescapeEntities=J.unescapeEntities=e;return J})(Z);function sc(a,b,c){var d=self.location,e=R(c),e=fa(e.search);D().assert(!("__amp_source_origin"in e),"Source origin is not allowed in %s",c);var f=Ma(d);e=d;"string"==typeof e&&(e=R(e));if(Ma(e)){var k=e.pathname.split("/"),l=k[1];D().assert("a"==l||"c"==l||"v"==l,"Unknown path prefix in url %s",e.href);var l=k[2],g="s"==l?"https://"+decodeURIComponent(k[3]):"http://"+decodeURIComponent(l);D().assert(0<g.indexOf("."),"Expected a . in origin %s",g);k.splice(1,"s"==l?3:2);k=g+k.join("/");l=(l=e.search)&&
"?"!=l?(l=l.replace(Ja,"").replace(/^[?&]/,""))?"?"+l:"":"";e=k+l+(e.hash||"")}else e=e.href;e=R(e);if("href"==b&&!w(c,"#"))return Na(c,e);if("src"==b)return"amp-img"==a?tc(c,e,f):Na(c,e);if("srcset"==b){var m;try{m=Qb(c)}catch(h){return D().error("sanitizer","Failed to parse srcset: ",h),c}a=m.getSources();for(b=0;b<a.length;b++)a[b].url=tc(a[b].url,e,f);return m.stringify()}return c}
function tc(a,b,c){a=R(Na(a,b));return"data:"==a.protocol||Ma(a)||!c?a.href:xa+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};var uc=/^(i?-)?amp(html)?-/,vc=sa({"AMP-CAROUSEL":["slide"],"AMP-LIST":["state"],"AMP-SELECTOR":["selected"]});
function wc(a,b){var c=this;this.Y=xc(a.win);D().assert(this.Y,'Experiment "amp-bind" is disabled.');this.ampdoc=a;this.j=a.win;this.ba=b||a.win;this.M=[];this.ca=2E3;this.N=Object.create(null);this.Aa=new Yb;this.V=sa(void 0);this.ma=S(a,"resources");this.G=S(this.ampdoc,"viewer");this.$=Promise.all([fb(this.ba.document),this.G.whenFirstVisible()]).then(function(){var a=c.ba.document.body;return c.aa(a)});this.qa=this.va.bind(this);this.W=null;y().development&&(AMP.printState=this.xa.bind(this))}
v=wc.prototype;v.adoptEmbedWindow=function(a){Qa(a,new wc(this.ampdoc,a))};v.setState=function(a,b,c){var d=this;D().assert(this.Y,'Experiment "amp-bind" is disabled.');try{va(this.V,a)}catch(e){D().error("amp-bind","Failed to merge scope.",e)}return b?Promise.resolve():this.W=this.$.then(function(){return yc(d)}).then(function(a){return zc(d,a,c)})};
v.setStateWithExpression=function(a,b){var c=this;D().assert(this.Y,'Experiment "amp-bind" is disabled.');return this.W=this.$.then(function(){Object.assign(b,c.V);return Ac(c,"bind.evaluateExpression",[a,b])}).then(function(a){var b=a.result;if(a=a.error){var d=D().createError("amp-bind: AMP.setState() failed with error: "+a.message);d.stack=a.stack;W(d)}else return c.setState(b)})};
v.aa=function(a){var b=this,c=Bc(this,a).then(function(){a.addEventListener("amp:template-rendered",b.qa)});y().development&&(c=c.then(function(){return yc(b).then(function(a){return Cc(b,a)})}));return c};function Dc(a){return a.M.reduce(function(a,c){return a+c.boundProperties.length},0)}v.Ja=function(a){this.ca=a};
function Bc(a,b){var c=a.ca-Dc(a);return Ec(a,b,c).then(function(b){var c=b.boundElements,d=b.bindings,k=b.expressionToElements,l=b.limitExceeded;a.M=a.M.concat(c);Object.assign(a.N,k);l&&D().error("amp-bind","Maximum number of bindings reached "+("("+a.ca+"). Additional elements with ")+"bindings will be ignored.");return 0==d.length?{}:Ac(a,"bind.addBindings",[d])}).then(function(b){Object.keys(b).forEach(function(c){var d=a.N[c];if(0<d.length){var e=b[c];c=D().createError('amp-bind: Expression compilation error in "'+
c+'". '+e.message);c.stack=e.stack;W(c,d[0])}})})}function Fc(a,b){Ob(a.M,function(a){return!b.contains(a.element)});var c=[],d;for(d in a.N){var e=a.N[d];Ob(e,function(a){return!b.contains(a)});0==e.length&&(c.push(d),delete a.N[d])}return 0<c.length?Ac(a,"bind.removeBindingsWithExpressionStrings",[c]):Promise.resolve()}
function Ec(a,b,c){function d(){var b=l.currentNode;if(!b)return!0;var d=b.tagName,q=Gc(a,b);f.length+q.length>c&&(q=q.slice(0,c-f.length),g=!0);0<q.length&&e.push({element:b,boundProperties:q});q.forEach(function(a){var c=a,e=c.expressionString;f.push({tagName:d,property:c.property,expressionString:e});k[e]||(k[e]=[]);k[e].push(b)});return!l.nextNode()||g}var e=[],f=[],k=Object.create(null),l=b.ownerDocument.createTreeWalker(b,NodeFilter.SHOW_ELEMENT),g=!1;return new Promise(function(b){function c(h){var l=
!1;if(h&&!h.didTimeout)for(;1<h.timeRemaining()&&!l;)l=d();else{var m=250;for(h=0;h<m&&!l;h++)l=d()}l?b({boundElements:e,bindings:f,expressionToElements:k,limitExceeded:g}):dc(a.ampdoc,c)}dc(a.ampdoc,c)})}
function Gc(a,b){for(var c=[],d=b.attributes,e=0,f=d.length;e<f;e++){var k;a:{var l=a,g=d[e];k=b;var m=k.tagName,h=g.name;if(2<h.length&&"["===h[0]&&"]"===h[h.length-1]){h=h.substr(1,h.length-2);if(l.Aa.canBind(m,h)){k={property:h,expressionString:g.value};break a}l=D().createError("amp-bind: Binding to ["+h+"] on <"+m+"> is not allowed.");W(l,k)}k=null}k&&c.push(k)}return c}
function yc(a){var b=Ac(a,"bind.evaluateBindings",[a.V]);return b.then(function(b){var c=b.results,e=b.errors;Object.keys(e).forEach(function(b){var c=a.N[b];if(0<c.length){var d=e[b];b=D().createError('amp-bind: Expression evaluation error in "'+b+'". '+d.message);b.stack=d.stack;W(b,c[0])}});return c})}
function Cc(a,b){a.M.forEach(function(a){var c=a.element;a.boundProperties.forEach(function(a){var d=b[a.expressionString];if(void 0!==d){a=a.property;var e=vc[c.tagName];if(!e||!e.includes(a)){switch(a){case "text":e=c.textContent;d=String(d);e=e.trim()===d.trim();break;case "class":for(var e=[],l=0;l<c.classList.length;l++){var g=c.classList[l];uc.test(g)||e.push(g)}l=[];Array.isArray(d)?l=d:"string"===typeof d?(g=d.trim(),0<g.length&&(l=g.split(" "))):(g=D().createError('amp-bind: "'+d+'" is not a valid result for [class].'),
W(g,c));a:if(g=l,e.length!==g.length)e=!1;else{for(var l=(Array.isArray(e)?e:ka(e)).sort(),g=(Array.isArray(g)?g:ka(g)).sort(),m=0;m<e.length;m++)if(l[m]!==g[m]){e=!1;break a}e=!0}break;default:e=c.getAttribute(a),e=!0===d?""===e:!1===d?null===e:e===d}e||(d=D().createError("amp-bind: "+("Default value for ["+a+"] does not match first expression ")+("result ("+d+"). This can result in unexpected behavior ")+"after the next state change."),W(d,c))}}})})}
function Hc(a,b){var c=[];a.forEach(function(a){var d=a.previousResult,f=b[a.expressionString];void 0===f||Ic(f,d)||(a.previousResult=f,c.push({boundProperty:a,newValue:f}))});return c}
function zc(a,b,c){var d=[];a.M.forEach(function(e){var f=e.element;if(!c||"AMP-STATE"!==f.tagName){var k=Hc(e.boundProperties,b);0!==k.length&&(e=a.ma.mutateElement(f,function(){var b=sa(void 0),c,d;k.forEach(function(a){var e=a,g=e.boundProperty,e=e.newValue,h;a:{var k=g.property;switch(k){case "text":f.textContent=String(e);break;case "class":h=[];for(k=0;k<f.classList.length;k++){var l=f.classList[k];uc.test(l)&&h.push(l)}Array.isArray(e)||"string"===typeof e?f.className=h.concat(e).join(" "):
null===e?f.className=h.join(" "):(h=D().createError('amp-bind: "'+e+'" is not a valid result for [class].'),W(h,f));break;default:var l="INPUT"==f.tagName&&k in f,m=f.getAttribute(k),q=!1;if("boolean"===typeof e)l&&f[k]!==e&&(f[k]=e,q=!0),e&&""!==m?(f.setAttribute(k,""),q=!0):e||null===m||(f.removeAttribute(k),q=!0);else if(e!==m){try{var I=String(e);h="src"==k||"href"==k||"srcset"==k?sc(f.tagName,k,I):I}catch(K){I=D().createError('amp-bind: "'+e+'" is not a '+("valid result for ["+k+"]"),K),W(I,
f)}void 0!==h&&(f.setAttribute(k,h),l&&(f[k]=h),q=!0)}if(q){h={name:k,value:e};break a}}h=null}var C=h;C&&(b[C.name]=C.value,g=g.property,"width"==g?c="number"===typeof e&&isFinite(e)?Number(e):c:"height"==g&&(d="number"===typeof e&&isFinite(e)?Number(e):d))});void 0===c&&void 0===d||a.ma.changeSize(f,d,c);if("function"===typeof f.mutatedAttributesCallback)try{f.mutatedAttributesCallback(b)}catch(q){var e=D().createError("amp-bind: Applying expression "+("results ("+JSON.stringify(b)+") failed with error"),
q);W(e,f)}}),d.push(e))}});return Promise.all(d)}v.va=function(a){var b=this,c=a.target;Fc(this,c).then(function(){return Bc(b,c)}).then(function(){})};function Ac(a,b,c){var d=a.j;a=a.ba;d.Worker?(Wa(d,"amp-worker",pc),d=Va(d,"amp-worker"),b=qc(d,b,c||[],a)):b=Promise.reject("Worker not supported in window.");return b}
function Ic(a,b){if(a===b)return!0;if(null===a||null===b||typeof a!==typeof b)return!1;if(Array.isArray(a)&&Array.isArray(b)){if(a.length!==b.length)return!1;for(var c=0;c<a.length;c++)if(a[c]!==b[c])return!1;return!0}if("object"===typeof a&&"object"===typeof b){var d=Object.keys(a),e=Object.keys(b);if(d.length!==e.length)return!1;for(c=0;c<d.length;c++){var f=d[c];if(a[f]!==b[f])return!1}return!0}return!1}
v.xa=function(){var a=[],b=JSON.stringify(this.V,function(b,d){if(la(d)){if(a.includes(d))return"[Circular]";a.push(d)}return d});D().info("amp-bind",b)};v.Ha=function(){return this.$};v.Ka=function(){return this.W};
function xc(a){var b;if(!V){V=Object.create(null);if(a.AMP_CONFIG)for(b in a.AMP_CONFIG){var c=a.AMP_CONFIG[b];"number"===typeof c&&0<=c&&1>=c&&(V[b]=Math.random()<c)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(b=a.AMP_CONFIG["allow-doc-opt-in"],c=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var c=c.getAttribute("content").split(","),d=0;d<c.length;d++)-1!=b.indexOf(c[d])&&(V[c[d]]=!0);Object.assign(V,cb(a));
if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length)for(b=a.AMP_CONFIG["allow-url-opt-in"],c=fa(a.location.originalHash||a.location.hash),d=0;d<b.length;d++){var e=c["e-"+b[d]];"1"==e&&(V[b[d]]=!0);"0"==e&&(V[b[d]]=!1)}}b=V;return b["amp-bind"]?!0:(a=a.document.head.querySelector('meta[name="amp-experiment-token"]'))&&"HfmyLgNLmblRg3Alqy164Vywr"===a.getAttribute("content")?!0:!1};function Jc(a){AMP.BaseElement.apply(this,arguments)}da(Jc,AMP.BaseElement);v=Jc.prototype;v.getPriority=function(){return 1};v.isAlwaysFixed=function(){return!0};v.isLayoutSupported=function(){return!0};v.activate=function(){var a=this.T();D().error(a,'Please use AMP.setState() action explicitly, e.g. on="submit-success:AMP.setState({myAmpState: event.response})"')};
v.buildCallback=function(){var a=this;D().assert(xc(this.win),'Experiment "amp-bind" is disabled.');Ab(this.element);this.element.setAttribute("aria-hidden","true");S(this.getAmpDoc(),"viewer").whenFirstVisible().then(function(){return a.aa()})};v.mutatedAttributesCallback=function(a){S(this.getAmpDoc(),"viewer").isVisible()?void 0!==a.src&&Kc(this,!1):(a=this.T(),qa().error(a,"Viewer must be visible before mutation."))};v.renderOutsideViewport=function(){return!0};
v.aa=function(){0<this.element.children.length&&Lc(this);this.element.hasAttribute("src")&&Kc(this,!0)};function Lc(a){var b=a.T(),c=a.element.children;if(1!=c.length)D().error(b,"Should contain exactly one <script> child.");else{var d=c[0];gb(d)?(c=bb(d.textContent,function(a){D().error(b,"Failed to parse state. Is it valid JSON?",a)}),Mc(a,c,!0)):D().error(b,'State should be in a <script> tag with type="application/json".')}}
function Kc(a,b){var c=a.getAmpDoc();Pb(c,a.element).then(function(c){Mc(a,c,b)})}function Mc(a,b,c){if(void 0!==b&&null!==b){var d=D().assert(a.element.id,"<amp-state> must have an id."),e=Object.create(null);e[d]=b;kb(a.element).then(function(a){a.setState(e,c,!c)})}}v.T=function(){return"<amp-state> "+(this.element.getAttribute("id")||"<unknown id>")};(function(a){a.registerServiceForDoc("bind",wc);a.registerElement("amp-state",Jc)})(self.AMP);
})});
//# sourceMappingURL=amp-bind-0.1.js.map

