(self.AMP=self.AMP||[]).push({n:"amp-slides",v:"123456789",f:(function(AMP){var h;function l(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};Date.now();self.log=self.log||{user:null,dev:null};var m=self.log;function n(){if(m.dev)return m.dev;throw Error("failed to call initLogConstructor");};var p,q="Webkit webkit Moz moz ms O o".split(" ");function r(a,b,c){var d;var e=a.style;if(2>b.length||0!=b.lastIndexOf("--",0)){p||(p=Object.create(null));var f=p[b];if(!f){f=b;if(void 0===e[b]){var g=b.charAt(0).toUpperCase()+b.slice(1);b:{for(var k=0;k<q.length;k++){var z=q[k]+g;if(void 0!==e[z]){g=z;break b}}g=""}void 0!==e[g]&&(f=g)}p[b]=f}b=f}b&&(a.style[b]=d?c+d:c)}function t(a,b){for(var c in b)r(a,c,b[c])};function u(a,b,c,d){var e=new v(0,0,a,b,c,d,1,1);return e.solveYValueFromXValue.bind(e)}function v(a,b,c,d,e,f,g,k){this.x0=a;this.y0=b;this.x1=c;this.y1=d;this.x2=e;this.y2=f;this.x3=g;this.y3=k}h=v.prototype;h.solveYValueFromXValue=function(a){return this.getPointY(this.solvePositionFromXValue(a))};
h.solvePositionFromXValue=function(a){var b=1E-6,c=(a-this.x0)/(this.x3-this.x0);if(0>=c)return 0;if(1<=c)return 1;for(var d=0,e=1,f=0,g=0;8>g;g++){var f=this.getPointX(c),k=(this.getPointX(c+b)-f)/b;if(Math.abs(f-a)<b)return c;if(Math.abs(k)<b)break;else f<a?d=c:e=c,c-=(f-a)/k}for(g=0;Math.abs(f-a)>b&&8>g;g++)f<a?(d=c,c=(c+e)/2):(e=c,c=(c+d)/2),f=this.getPointX(c);return c};
h.getPointX=function(a){if(0==a)return this.x0;if(1==a)return this.x3;var b=this.lerp(this.x0,this.x1,a),c=this.lerp(this.x1,this.x2,a),d=this.lerp(this.x2,this.x3,a),b=this.lerp(b,c,a),c=this.lerp(c,d,a);return this.lerp(b,c,a)};h.getPointY=function(a){if(0==a)return this.y0;if(1==a)return this.y3;var b=this.lerp(this.y0,this.y1,a),c=this.lerp(this.y1,this.y2,a),d=this.lerp(this.y2,this.y3,a),b=this.lerp(b,c,a),c=this.lerp(c,d,a);return this.lerp(b,c,a)};h.lerp=function(a,b,c){return a+c*(b-a)};
var w=u(.25,.1,.25,1),x=u(.42,0,1,1),y=u(0,0,.58,1),A=u(.42,0,.58,1),B={linear:function(a){return a},ease:w,"ease-in":x,"ease-out":y,"ease-in-out":A};function C(a){if(!a)return null;if("string"==typeof a){if(-1!=a.indexOf("cubic-bezier")){var b=a.match(/cubic-bezier\((.+)\)/);if(b&&(b=b[1].split(",").map(parseFloat),4==b.length)){for(var c=0;4>c;c++)if(isNaN(b[c]))return null;return u(b[0],b[1],b[2],b[3])}return null}return B[a]}return a};function D(){}function E(a,b){this.f=a;if(!(a=b)){a=self;a=a.__AMP_TOP||a;var c=a.services;c||(c=a.services={});a=c.vsync;a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));a=a.obj}this.g=a;this.l=null;this.a=[]}function F(a,b){var c="ease-out";return(new E(a)).setCurve(c).add(0,b,1).start(200)}E.prototype.setCurve=function(a){a&&(this.l=C(a));return this};E.prototype.add=function(a,b,c,d){this.a.push({delay:a,func:b,duration:c,curve:C(d)});return this};
E.prototype.start=function(a){var b=new G(this.g,this.f,this.a,this.l,a);a=b;a.o=Date.now();a.j=!0;a.g.canAnimate(a.f)?a.u(a.s):(n().warn("Animation","cannot animate"),H(a,!1,0));return b};
function G(a,b,c,d,e){var f=this;this.g=a;this.f=b;this.a=[];for(b=0;b<c.length;b++){var g=c[b];this.a.push({delay:g.delay,func:g.func,duration:g.duration,curve:g.curve||d,started:!1,completed:!1})}this.w=e;this.F=this.D=this.o=0;this.j=!1;this.s={};this.m=new Promise(function(a,b){f.B=a;f.A=b});this.u=this.g.createAnimTask(this.f,{mutate:this.C.bind(this)})}G.prototype.then=function(a,b){return a||b?this.m.then(a,b):this.m};G.prototype.thenAlways=function(a){a=a||D;return this.then(a,a)};
G.prototype.halt=function(a){H(this,!1,a||0)};function H(a,b,c){if(a.j){a.j=!1;if(0!=c){1<a.a.length&&a.a.sort(function(a,b){return a.delay+a.duration-(b.delay+b.duration)});try{if(0<c)for(var d=0;d<a.a.length;d++)a.a[d].func(1,!0);else for(d=a.a.length-1;0<=d;d--)a.a[d].func(0,!1)}catch(e){n().error("Animation","completion failed: "+e,e),b=!1}}b?a.B():a.A()}}
G.prototype.C=function(){if(this.j){for(var a=Date.now(),b=Math.min((a-this.o)/this.w,1),c=0;c<this.a.length;c++){var d=this.a[c];!d.started&&b>=d.delay&&(d.started=!0)}for(c=0;c<this.a.length;c++)if(d=this.a[c],d.started&&!d.completed)a:{var e,f;if(0<d.duration){if(f=e=Math.min((b-d.delay)/d.duration,1),d.curve&&1!=f)try{f=d.curve(e)}catch(g){n().error("Animation","step curve failed: "+g,g);H(this,!1,0);break a}}else f=e=1;1==e&&(d.completed=!0);try{d.func(f,d.completed)}catch(g){n().error("Animation",
"step mutate failed: "+g,g),H(this,!1,0)}}1==b?H(this,!0,0):this.g.canAnimate(this.f)?this.u(this.s):(n().warn("Animation","cancel animation"),H(this,!1,0))}};function I(a){return function(b,c){for(var d=0;d<a.length;d++){var e=a[d];e(b,c)}}}function J(a,b){return function(c,d){for(var e in b)r(a,e,b[e](c,d))}}function K(a,b){return function(c){return a+(b-a)*c}}function L(a){return function(b){b=a(b);return"string"==typeof b?"translateX("+b+")":"translateX("+b+"px)"}}function M(){var a=K(1,.98);return function(b){return"scale("+a(b)+")"}};function N(a){AMP.BaseElement.apply(this,arguments)}l(N,AMP.BaseElement);h=N.prototype;h.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a};
h.buildCallback=function(){var a=this;this.b=this.getRealChildren();this.b.forEach(function(b,c){a.setAsOwner(b);r(b,"display",0<c?"none":"block");a.applyFillContent(b)});this.c=0;this.i=this.element.ownerDocument.createElement("button");this.i.textContent="\u276e";t(this.i,{opacity:.6,position:"absolute",zIndex:10,left:"16px",top:"50%",padding:"8px",fontSize:"24px",marginTop:"-20px",pointerEvents:"all"});this.i.onclick=function(){a.go(-1,!0)};this.element.appendChild(this.i);this.h=this.element.ownerDocument.createElement("button");
this.h.textContent="\u276f";t(this.h,{opacity:.6,position:"absolute",zIndex:10,right:"16px",top:"50%",padding:"8px",fontSize:"24px",marginTop:"-20px",pointerEvents:"all"});this.h.onclick=function(){a.go(1,!0)};this.element.appendChild(this.h)};h.prerenderAllowed=function(){return!0};h.isRelayoutNeeded=function(){return!0};h.layoutCallback=function(){this.scheduleLayout(this.b[this.c]);O(this,1);return Promise.resolve()};h.viewportCallback=function(a){this.updateInViewport(this.b[this.c],a)};
h.go=function(a,b){var c=this,d=P(this,a);if(d!=this.c){var e=this.b[d],f=this.b[this.c];this.c=d;Q(this,e,a);b?(r(f,"zIndex",0),F(this.element,I([J(e,{transform:L(K(a*this.element.offsetWidth,0)),opacity:K(.8,1)}),J(f,{transform:M(),opacity:K(1,.4)})])).thenAlways(function(){R(c,f,e);O(c,a)})):R(this,f,e)}};function Q(a,b,c){var d=a.element.offsetWidth;c*=d;t(b,{transform:"string"==typeof c?"translateX("+c+")":"translateX("+(c+"px")+")",zIndex:1,display:"block"});a.scheduleLayout(b)}
function R(a,b,c){t(b,{display:"none",zIndex:0,transform:"",transition:"",opacity:1});t(c,{display:"block",zIndex:0,transform:"",transition:"",opacity:1});a.scheduleLayout(c);a.updateInViewport(b,!1);a.updateInViewport(c,!0)}function P(a,b){b=a.c+b;0>b?b=a.b.length+b:b>=a.b.length&&(b%=a.b.length);return b}function O(a,b){var c=P(a,b);c!=a.c&&a.schedulePreload(a.b[c])}AMP.registerElement("amp-slides",N);
})});
//# sourceMappingURL=amp-slides-0.1.js.map

