(self.AMP=self.AMP||[]).push({n:"amp-video",v:"123456789",f:(function(AMP){var f;(function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a})(this);function m(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};var p=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function q(a){var b=Object.create(null);if(!a)return b;for(var c;c=p.exec(a);){var d=decodeURIComponent(c[1]).trim(),e=c[2]?decodeURIComponent(c[2]).trim():"";b[d]=e}return b};var r="";
function t(a){var b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;if(c.context&&c.context.mode)c=c.context.mode;else{var d=q(c.location.originalHash||c.location.hash),e=q(c.location.search);r||(r=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"01123456789");c={localDev:!1,development:!("1"!=d.development&&!c.AMP_DEV_MODE),examiner:"2"==d.development,filter:d.filter,minified:!0,lite:void 0!=e.amp_lite,test:!1,log:d.log,version:"123456789",rtvVersion:r}}c=b.AMP_MODE=c}return c}
;Date.now();self.log=self.log||{user:null,dev:null};var u=self.log;function v(){if(u.user)return u.user;throw Error("failed to call initLogConstructor");};var w,x;
function y(a){if("string"==typeof a){w||(w=self.document.createElement("a"),x=self.UrlCache||(self.UrlCache=Object.create(null)));var b=x[a];if(b)a=b;else{b=w;b.href=a;b.protocol||(b.href=b.href);var c={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:"0"==b.port?"":b.port,pathname:b.pathname,search:b.search,hash:b.hash,origin:null};"/"!==c.pathname[0]&&(c.pathname="/"+c.pathname);if("http:"==c.protocol&&80==c.port||"https:"==c.protocol&&443==c.port)c.port="",c.host=c.hostname;c.origin=
b.origin&&"null"!=b.origin?b.origin:"data:"!=c.protocol&&c.host?c.protocol+"//"+c.host:c.href;a=x[a]=c}}(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}function z(a,b){var c;c=void 0===c?"source":c;v().assert(null!=a,"%s %s must be available",b,c);var d=a;v().assert(y(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)};function A(a,b){a=a.__AMP_TOP||a;return B(a,b)}function C(a,b){a=D(a);a=E(a);return B(a,b)}function D(a){return a.nodeType?A((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function E(a){a=D(a);return a.isSingleDoc()?a.win:a}function B(a,b){var c=F(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function F(a){var b=a.services;b||(b=a.services={});return b};var G,H="Webkit webkit Moz moz ms O o".split(" ");function I(a){var b={position:"fixed",top:"0",width:"0",height:"0",opacity:"0"},c;for(c in b){var d=a,e=b[c],g;g=d.style;var h=c;if(2>h.length?0:0==h.lastIndexOf("--",0))g=h;else{G||(G=Object.create(null));var k=G[h];if(!k){k=h;if(void 0===g[h]){var l;l=h;l=l.charAt(0).toUpperCase()+l.slice(1);b:{for(var n=0;n<H.length;n++){var K=H[n]+l;if(void 0!==g[K]){l=K;break b}}l=""}void 0!==g[l]&&(k=l)}G[h]=k}g=k}g&&(d.style[g]=e)}};function J(a,b,c){function d(a){try{return h(a)}catch(n){throw self.reportError(n),n;}}var e=void 0,g=a,h=c,k=e||!1;g.addEventListener(b,d,k);return function(){g&&g.removeEventListener(b,d,k);d=g=h=null}};function L(a,b,c){return J(a,b,c)}function M(a,b){var c=b,d=J(a,"load",function(a){try{c(a)}finally{c=null,d()}});return d}function N(a){var b,c,d=new Promise(function(b){c=M(a,b)});d.then(c,c);b&&b(c);return d};function O(a){this.c=a;this.b=null;this.u=!1}O.prototype.register=function(a){var b=a;b.registerAction("play",b.play.bind(b,!1),3);b.registerAction("pause",b.pause.bind(b),1);b.registerAction("mute",b.mute.bind(b),1);b.registerAction("unmute",b.unmute.bind(b),3);if(a.supportsPlatform()){this.b=this.b||[];var c=new P(this.c,a);Q(this,c);this.b.push(c)}};
function Q(a,b){if(b.video.element.hasAttribute("autoplay")&&(L(b.video.element,"amp:video:visibility",function(){b.updateVisibility()}),L(b.video.element,"reloaded",function(){b.updateVisibility();b.j=!0;b.f&&b.g&&R(b)}),!a.u)){var c=function(){for(var b=0;b<a.b.length;b++)a.b[b].updateVisibility()},d=C(a.c,"viewport");d.onScroll(c);d.onChanged(c);a.u=!0}}function S(a,b){for(var c=0;c<a.b.length;c++)if(a.b[c].video===b)return a.b[c];return null}
O.prototype.getPlayingState=function(a){return S(this,a).getPlayingState()};O.prototype.userInteractedWithAutoPlay=function(a){return S(this,a).userInteractedWithAutoPlay()};
function P(a,b){var c=this;this.c=a;this.video=b;this.B=null;this.f=this.h=this.j=!1;this.m=A(a.win,"vsync");this.o=T.bind(null,a.win,t(a.win).lite);a=b.element;this.g=a.hasAttribute("autoplay");this.s=this.i=!1;N(a).then(function(){c.updateVisibility();c.j=!0;c.f&&c.g&&R(c)});L(this.video.element,"pause",this.w.bind(this));L(this.video.element,"play",this.A.bind(this));this.updateVisibility();this.g&&U(this)}f=P.prototype;f.A=function(){this.h=!0};f.w=function(){this.h=!1};
function U(a){a.video.isInteractive()&&a.video.hideControls();a.o().then(function(b){!b&&a.video.isInteractive()?a.video.showControls():(a.video.mute(),a.video.isInteractive()&&V(a))})}
function V(a){function b(b){a.m.mutate(function(){d.classList.toggle("amp-video-eq-play",b)})}function c(){this.i=!0;this.video.showControls();this.video.unmute();g();h();k();d.remove();e.remove()}a.video.hideControls();var d=aa(a),e=ba(a);a.m.mutate(function(){a.video.element.appendChild(d);a.video.element.appendChild(e)});var g=L(e,"click",c.bind(a)),h=L(a.video.element,"pause",b.bind(a,!1)),k=L(a.video.element,"play",b.bind(a,!0))}
function R(a){!a.i&&C(a.c,"viewer").isVisible()&&a.o().then(function(b){b&&(a.f?(a.video.play(!0),a.s=!0):a.video.pause())})}
function aa(a){var b=a.c.win.document,c=b.createElement("i-amphtml-video-eq");c.classList.add("amp-video-eq");for(var d=1;4>=d;d++){var e=b.createElement("div");e.classList.add("amp-video-eq-col");for(var g=1;2>=g;g++){var h=b.createElement("div");h.classList.add("amp-video-eq-"+d+"-"+g);e.appendChild(h)}c.appendChild(e)}var k=A(a.c.win,"platform");k.isIos()&&c.setAttribute("unpausable","");return c}
function ba(a){a=a.c.win.document.createElement("i-amphtml-video-mask");a.classList.add("i-amphtml-fill-content");return a}f.updateVisibility=function(){function a(){c.f!=d&&c.j&&c.g&&R(c)}function b(){if(c.video.isInViewport()){var a=c.video.element.getIntersectionChangeEntry(),b=a.intersectionRatio,d="number"===typeof b&&isFinite(b)?100*a.intersectionRatio:0;c.f=75<=d}else c.f=!1}var c=this,d=this.f;this.m.run({measure:b,mutate:a})};
f.getPlayingState=function(){return this.h?this.h&&this.s&&!this.i?"playing_auto":"playing_manual":"paused"};f.userInteractedWithAutoPlay=function(){return this.i};var W=null;
function T(a,b){if(W)return W;if(b)return W=Promise.resolve(!1);var c=a.document.createElement("video");c.setAttribute("muted","");c.setAttribute("playsinline","");c.setAttribute("webkit-playsinline","");c.muted=!0;c.playsinline=!0;c.webkitPlaysinline=!0;c.setAttribute("height","0");c.setAttribute("width","0");I(c);try{var d=c.play();d&&d.catch&&d.catch(function(){})}catch(e){}return W=Promise.resolve(!c.paused)};var X=["poster","controls","aria-label","aria-describedby","aria-labelledby"],Y=["src","loop","preload"],ca=X.concat(Y);function Z(a){AMP.BaseElement.call(this,a);this.a=null;this.l=!1}m(Z,AMP.BaseElement);f=Z.prototype;f.preconnectCallback=function(a){var b=this.element.getAttribute("src");if(!b){var c=this.element.getElementsByTagName("source")[0]||null;c&&(b=c.getAttribute("src"))}var d=b;d&&(z(d,this.element),this.preconnect.url(d,a))};
f.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a};
f.buildCallback=function(){this.a=this.element.ownerDocument.createElement("video");var a=this.element.getAttribute("poster");!a&&t().development&&console.error('No "poster" attribute has been provided for amp-video.');this.a.setAttribute("playsinline","");this.a.setAttribute("webkit-playsinline","");this.a.setAttribute("preload","none");this.propagateAttributes(X,this.a,!0);da(this);this.applyFillContent(this.a,!0);this.element.appendChild(this.a);var b=D(this.element),c=E(b),d=F(c),e=d["video-manager"];
e||(e=d["video-manager"]={obj:null,promise:null,resolve:null,context:null,ctor:null});e.ctor||e.obj||(e.ctor=O,e.context=b,e.resolve&&B(c,"video-manager"));C(this.element,"video-manager").register(this)};f.mutatedAttributesCallback=function(a){if(this.a){a.src&&z(this.element.getAttribute("src"),this.element);var b=ca.filter(function(b){return void 0!==a[b]});this.propagateAttributes(b,this.a,!0);a.src&&this.element.dispatchCustomEvent("reloaded")}};
f.viewportCallback=function(a){this.element.dispatchCustomEvent("amp:video:visibility",{visible:a})};f.layoutCallback=function(){var a=this;this.a=this.a;if(!this.a.play)return this.toggleFallback(!0),Promise.resolve();this.element.getAttribute("src")&&z(this.element.getAttribute("src"),this.element);this.propagateAttributes(Y,this.a,!0);this.getRealChildNodes().forEach(function(b){a.a!==b&&(b.getAttribute&&b.getAttribute("src")&&z(b.getAttribute("src"),b),a.a.appendChild(b))});return this.loadPromise(this.a).then(function(){a.element.dispatchCustomEvent("load")})};
function da(a){var b=a.a;a.forwardEvents(["play","pause"],b);L(b,"volumechange",function(){a.l!=a.a.muted&&(a.l=a.a.muted,a.element.dispatchCustomEvent(a.l?"muted":"unmuted"))})}f.pauseCallback=function(){this.a&&this.a.pause()};f.supportsPlatform=function(){return!!this.a.play};f.isInteractive=function(){return this.element.hasAttribute("controls")};f.play=function(){var a=this.a.play();a&&a.catch&&a.catch(function(){})};f.pause=function(){this.a.pause()};f.mute=function(){this.a.muted=!0};
f.unmute=function(){this.a.muted=!1};f.showControls=function(){this.a.controls=!0};f.hideControls=function(){this.a.controls=!1};AMP.registerElement("amp-video",Z);
})});
//# sourceMappingURL=amp-video-0.1.js.map

