(self.AMP=self.AMP||[]).push({n:"amp-3q-player",v:"123456789",f:(function(AMP){var f;(function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a})(this);function m(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var g=Object.getOwnPropertyDescriptor(b,d);g&&Object.defineProperty(a,d,g)}else a[d]=b[d]};var p=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function q(a){var b=Object.create(null);if(!a)return b;for(var c;c=p.exec(a);){var d=decodeURIComponent(c[1]).trim(),g=c[2]?decodeURIComponent(c[2]).trim():"";b[d]=g}return b};var r="";
function t(a){var b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;if(c.context&&c.context.mode)c=c.context.mode;else{var d=q(c.location.originalHash||c.location.hash),g=q(c.location.search);r||(r=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"01123456789");c={localDev:!1,development:!("1"!=d.development&&!c.AMP_DEV_MODE),examiner:"2"==d.development,filter:d.filter,minified:!0,lite:void 0!=g.amp_lite,test:!1,log:d.log,version:"123456789",rtvVersion:r}}c=b.AMP_MODE=c}return c}
;var u=Object.prototype.toString;Date.now();self.log=self.log||{user:null,dev:null};var v=self.log;function w(a,b){a=a.__AMP_TOP||a;return x(a,b)}function y(a){var b=z,c=A(a),d=B(c);a=d;var g=C(a),e=g["video-manager"];e||(e=g["video-manager"]={obj:null,promise:null,resolve:null,context:null,ctor:null});e.ctor||e.obj||(e.ctor=b,e.context=c,e.resolve&&x(a,"video-manager"))}function D(a,b){a=A(a);a=B(a);return x(a,b)}function A(a){return a.nodeType?w((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function B(a){a=A(a);return a.isSingleDoc()?a.win:a}
function x(a,b){var c=C(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function C(a){var b=a.services;b||(b=a.services={});return b};function E(a){a.parentElement&&a.parentElement.removeChild(a)};var F,H="Webkit webkit Moz moz ms O o".split(" ");function I(a){var b={position:"fixed",top:"0",width:"0",height:"0",opacity:"0"},c;for(c in b){var d=a,g=b[c],e;e=d.style;var h=c;if(2>h.length?0:0==h.lastIndexOf("--",0))e=h;else{F||(F=Object.create(null));var k=F[h];if(!k){k=h;if(void 0===e[h]){var l;l=h;l=l.charAt(0).toUpperCase()+l.slice(1);b:{for(var n=0;n<H.length;n++){var G=H[n]+l;if(void 0!==e[G]){l=G;break b}}l=""}void 0!==e[l]&&(k=l)}F[h]=k}e=k}e&&(d.style[e]=g)}};function J(a,b,c){function d(a){try{return h(a)}catch(n){throw self.reportError(n),n;}}var g=void 0,e=a,h=c,k=g||!1;e.addEventListener(b,d,k);return function(){e&&e.removeEventListener(b,d,k);d=e=h=null}};function K(a,b,c){return J(a,b,c)}function L(a,b){var c=b,d=J(a,"load",function(a){try{c(a)}finally{c=null,d()}});return d}function M(a){var b,c,d=new Promise(function(b){c=L(a,b)});d.then(c,c);b&&b(c);return d};function z(a){this.c=a;this.b=null;this.A=!1}z.prototype.register=function(a){var b=a;b.registerAction("play",b.play.bind(b,!1),3);b.registerAction("pause",b.pause.bind(b),1);b.registerAction("mute",b.mute.bind(b),1);b.registerAction("unmute",b.unmute.bind(b),3);if(a.supportsPlatform()){this.b=this.b||[];var c=new N(this.c,a);O(this,c);this.b.push(c)}};
function O(a,b){if(b.video.element.hasAttribute("autoplay")&&(K(b.video.element,"amp:video:visibility",function(){b.updateVisibility()}),K(b.video.element,"reloaded",function(){b.updateVisibility();b.l=!0;b.f&&b.g&&P(b)}),!a.A)){var c=function(){for(var b=0;b<a.b.length;b++)a.b[b].updateVisibility()},d=D(a.c,"viewport");d.onScroll(c);d.onChanged(c);a.A=!0}}function Q(a,b){for(var c=0;c<a.b.length;c++)if(a.b[c].video===b)return a.b[c];return null}
z.prototype.getPlayingState=function(a){return Q(this,a).getPlayingState()};z.prototype.userInteractedWithAutoPlay=function(a){return Q(this,a).userInteractedWithAutoPlay()};
function N(a,b){var c=this;this.c=a;this.video=b;this.F=null;this.f=this.h=this.l=!1;this.s=w(a.win,"vsync");this.u=R.bind(null,a.win,t(a.win).lite);a=b.element;this.g=a.hasAttribute("autoplay");this.w=this.j=!1;M(a).then(function(){c.updateVisibility();c.l=!0;c.f&&c.g&&P(c)});K(this.video.element,"pause",this.C.bind(this));K(this.video.element,"play",this.D.bind(this));this.updateVisibility();this.g&&S(this)}f=N.prototype;f.D=function(){this.h=!0};f.C=function(){this.h=!1};
function S(a){a.video.isInteractive()&&a.video.hideControls();a.u().then(function(b){!b&&a.video.isInteractive()?a.video.showControls():(a.video.mute(),a.video.isInteractive()&&T(a))})}
function T(a){function b(b){a.s.mutate(function(){d.classList.toggle("amp-video-eq-play",b)})}function c(){this.j=!0;this.video.showControls();this.video.unmute();e();h();k();d.remove();g.remove()}a.video.hideControls();var d=U(a),g=V(a);a.s.mutate(function(){a.video.element.appendChild(d);a.video.element.appendChild(g)});var e=K(g,"click",c.bind(a)),h=K(a.video.element,"pause",b.bind(a,!1)),k=K(a.video.element,"play",b.bind(a,!0))}
function P(a){!a.j&&D(a.c,"viewer").isVisible()&&a.u().then(function(b){b&&(a.f?(a.video.play(!0),a.w=!0):a.video.pause())})}
function U(a){var b=a.c.win.document,c=b.createElement("i-amphtml-video-eq");c.classList.add("amp-video-eq");for(var d=1;4>=d;d++){var g=b.createElement("div");g.classList.add("amp-video-eq-col");for(var e=1;2>=e;e++){var h=b.createElement("div");h.classList.add("amp-video-eq-"+d+"-"+e);g.appendChild(h)}c.appendChild(g)}var k=w(a.c.win,"platform");k.isIos()&&c.setAttribute("unpausable","");return c}
function V(a){a=a.c.win.document.createElement("i-amphtml-video-mask");a.classList.add("i-amphtml-fill-content");return a}f.updateVisibility=function(){function a(){c.f!=d&&c.l&&c.g&&P(c)}function b(){if(c.video.isInViewport()){var a=c.video.element.getIntersectionChangeEntry(),b=a.intersectionRatio,d="number"===typeof b&&isFinite(b)?100*a.intersectionRatio:0;c.f=75<=d}else c.f=!1}var c=this,d=this.f;this.s.run({measure:b,mutate:a})};
f.getPlayingState=function(){return this.h?this.h&&this.w&&!this.j?"playing_auto":"playing_manual":"paused"};f.userInteractedWithAutoPlay=function(){return this.j};var W=null;
function R(a,b){if(W)return W;if(b)return W=Promise.resolve(!1);var c=a.document.createElement("video");c.setAttribute("muted","");c.setAttribute("playsinline","");c.setAttribute("webkit-playsinline","");c.muted=!0;c.playsinline=!0;c.webkitPlaysinline=!0;c.setAttribute("height","0");c.setAttribute("width","0");I(c);try{var d=c.play();d&&d.catch&&d.catch(function(){})}catch(g){}return W=Promise.resolve(!c.paused)};function X(a){AMP.BaseElement.call(this,a);this.dataId=this.m=this.i=this.o=this.a=null}m(X,AMP.BaseElement);f=X.prototype;f.preconnectCallback=function(a){this.preconnect.url("https://playout.3qsdn.com",a)};
f.buildCallback=function(){var a=this,b;if(v.user)b=v.user;else throw Error("failed to call initLogConstructor");this.dataId=b.assert(this.element.getAttribute("data-id"),"The data-id attribute is required for <amp-3q-player> %s",this.element);this.i=new Promise(function(b){a.m=b});y(this.element);D(this.element,"video-manager").register(this)};
f.layoutCallback=function(){var a=this,b=this.element.ownerDocument.createElement("iframe");b.setAttribute("frameborder","0");b.setAttribute("allowfullscreen","true");this.a=b;this.o=K(this.win,"message",this.B.bind(this));this.applyFillContent(b,!0);b.src="https://playout.3qsdn.com/"+encodeURIComponent(this.dataId)+"?autoplay=false&amp=true";this.element.appendChild(b);return this.loadPromise(this.a).then(function(){return a.i})};
f.unlayoutCallback=function(){var a=this;this.a&&(E(this.a),this.a=null);this.o&&this.o();this.i=new Promise(function(b){a.m=b});return!0};f.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a};f.viewportCallback=function(a){this.element.dispatchCustomEvent("amp:video:visibility",{visible:a})};f.pauseCallback=function(){this.a&&this.pause()};
f.B=function(a){if(!a.source||a.source==this.a.contentWindow){var b;if("[object Object]"===u.call(a.data))b=a.data;else a:{try{b=JSON.parse(a.data);break a}catch(c){}b=void 0}a=b;if(void 0!==a)switch(a.data){case "ready":this.element.dispatchCustomEvent("load");this.m();break;case "playing":this.element.dispatchCustomEvent("play");break;case "paused":this.element.dispatchCustomEvent("pause");break;case "muted":this.element.dispatchCustomEvent("muted");break;case "unmuted":this.element.dispatchCustomEvent("unmuted")}}};
function Y(a,b){a.i.then(function(){a.a&&a.a.contentWindow&&a.a.contentWindow.postMessage(b,"*")})}f.play=function(){Y(this,"play2")};f.pause=function(){Y(this,"pause")};f.mute=function(){Y(this,"mute")};f.unmute=function(){Y(this,"unmute")};f.supportsPlatform=function(){return!0};f.isInteractive=function(){return!0};f.showControls=function(){Y(this,"showControlbar")};f.hideControls=function(){Y(this,"hideControlbar")};AMP.registerElement("amp-3q-player",X);
})});
//# sourceMappingURL=amp-3q-player-0.1.js.map

