(self.AMP=self.AMP||[]).push({n:"amp-youtube",v:"123456789",f:(function(AMP){var g;(function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global?global:a})(this);function m(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,d);f&&Object.defineProperty(a,d,f)}else a[d]=b[d]}function p(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var q=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function r(a){var b=Object.create(null);if(!a)return b;for(var c;c=q.exec(a);){var d=decodeURIComponent(c[1]).trim(),f=c[2]?decodeURIComponent(c[2]).trim():"";b[d]=f}return b};var t="";
function u(a){var b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;if(c.context&&c.context.mode)c=c.context.mode;else{var d=r(c.location.originalHash||c.location.hash),f=r(c.location.search);t||(t=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"01123456789");c={localDev:!1,development:!("1"!=d.development&&!c.AMP_DEV_MODE),examiner:"2"==d.development,filter:d.filter,minified:!0,lite:void 0!=f.amp_lite,test:!1,log:d.log,version:"123456789",rtvVersion:t}}c=b.AMP_MODE=c}return c}
;var v=Object.prototype.toString;Date.now();self.log=self.log||{user:null,dev:null};var w=self.log;function x(){if(w.user)return w.user;throw Error("failed to call initLogConstructor");};function y(a){var b=Object.create(null);a&&Object.assign(b,a);return b};function z(a,b){a=a.__AMP_TOP||a;return A(a,b)}function B(a){var b=C,c=D(a),d=E(c);a=d;var f=F(a),e=f["video-manager"];e||(e=f["video-manager"]={obj:null,promise:null,resolve:null,context:null,ctor:null});e.ctor||e.obj||(e.ctor=b,e.context=c,e.resolve&&A(a,"video-manager"))}function G(a,b){a=D(a);a=E(a);return A(a,b)}function D(a){return a.nodeType?z((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function E(a){a=D(a);return a.isSingleDoc()?a.win:a}
function A(a,b){var c=F(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function F(a){var b=a.services;b||(b=a.services={});return b};function H(a){a.parentElement&&a.parentElement.removeChild(a)}function I(a){var b,c,d=b||function(a){return a},f=a.dataset;a=Object.create(null);var e=c?c:/^param(.+)/,h;for(h in f){var k=h.match(e);if(k){var l=k[1][0].toLowerCase()+k[1].substr(1);a[d(l)]=f[h]}}return a};var J,K="Webkit webkit Moz moz ms O o".split(" ");function M(a,b){for(var c in b){var d=a,f=b[c],e;e=d.style;var h=c;if(p(h,"--"))e=h;else{J||(J=y());var k=J[h];if(!k){k=h;if(void 0===e[h]){var l;l=h;l=l.charAt(0).toUpperCase()+l.slice(1);b:{for(var n=0;n<K.length;n++){var L=K[n]+l;if(void 0!==e[L]){l=L;break b}}l=""}void 0!==e[l]&&(k=l)}J[h]=k}e=k}e&&(d.style[e]=f)}};function N(a,b,c){function d(a){try{return h(a)}catch(n){throw self.reportError(n),n;}}var f=void 0,e=a,h=c,k=f||!1;e.addEventListener(b,d,k);return function(){e&&e.removeEventListener(b,d,k);d=e=h=null}};function O(a,b,c){return N(a,b,c)}function P(a,b){var c=b,d=N(a,"load",function(a){try{c(a)}finally{c=null,d()}});return d}function Q(a){var b,c,d=new Promise(function(b){c=P(a,b)});d.then(c,c);b&&b(c);return d};function C(a){this.c=a;this.b=null;this.F=!1}C.prototype.register=function(a){var b=a;b.registerAction("play",b.play.bind(b,!1),3);b.registerAction("pause",b.pause.bind(b),1);b.registerAction("mute",b.mute.bind(b),1);b.registerAction("unmute",b.unmute.bind(b),3);if(a.supportsPlatform()){this.b=this.b||[];var c=new R(this.c,a);S(this,c);this.b.push(c)}};
function S(a,b){if(b.video.element.hasAttribute("autoplay")&&(O(b.video.element,"amp:video:visibility",function(){b.updateVisibility()}),O(b.video.element,"reloaded",function(){b.updateVisibility();b.m=!0;b.f&&b.i&&T(b)}),!a.F)){var c=function(){for(var b=0;b<a.b.length;b++)a.b[b].updateVisibility()},d=G(a.c,"viewport");d.onScroll(c);d.onChanged(c);a.F=!0}}function U(a,b){for(var c=0;c<a.b.length;c++)if(a.b[c].video===b)return a.b[c];return null}
C.prototype.getPlayingState=function(a){return U(this,a).getPlayingState()};C.prototype.userInteractedWithAutoPlay=function(a){return U(this,a).userInteractedWithAutoPlay()};
function R(a,b){var c=this;this.c=a;this.video=b;this.J=null;this.f=this.j=this.m=!1;this.B=z(a.win,"vsync");this.C=aa.bind(null,a.win,u(a.win).lite);a=b.element;this.i=a.hasAttribute("autoplay");this.D=this.l=!1;Q(a).then(function(){c.updateVisibility();c.m=!0;c.f&&c.i&&T(c)});O(this.video.element,"pause",this.H.bind(this));O(this.video.element,"play",this.I.bind(this));this.updateVisibility();this.i&&ba(this)}g=R.prototype;g.I=function(){this.j=!0};g.H=function(){this.j=!1};
function ba(a){a.video.isInteractive()&&a.video.hideControls();a.C().then(function(b){!b&&a.video.isInteractive()?a.video.showControls():(a.video.mute(),a.video.isInteractive()&&ca(a))})}
function ca(a){function b(b){a.B.mutate(function(){d.classList.toggle("amp-video-eq-play",b)})}function c(){this.l=!0;this.video.showControls();this.video.unmute();e();h();k();d.remove();f.remove()}a.video.hideControls();var d=da(a),f=ea(a);a.B.mutate(function(){a.video.element.appendChild(d);a.video.element.appendChild(f)});var e=O(f,"click",c.bind(a)),h=O(a.video.element,"pause",b.bind(a,!1)),k=O(a.video.element,"play",b.bind(a,!0))}
function T(a){!a.l&&G(a.c,"viewer").isVisible()&&a.C().then(function(b){b&&(a.f?(a.video.play(!0),a.D=!0):a.video.pause())})}
function da(a){var b=a.c.win.document,c=b.createElement("i-amphtml-video-eq");c.classList.add("amp-video-eq");for(var d=1;4>=d;d++){var f=b.createElement("div");f.classList.add("amp-video-eq-col");for(var e=1;2>=e;e++){var h=b.createElement("div");h.classList.add("amp-video-eq-"+d+"-"+e);f.appendChild(h)}c.appendChild(f)}var k=z(a.c.win,"platform");k.isIos()&&c.setAttribute("unpausable","");return c}
function ea(a){a=a.c.win.document.createElement("i-amphtml-video-mask");a.classList.add("i-amphtml-fill-content");return a}g.updateVisibility=function(){function a(){c.f!=d&&c.m&&c.i&&T(c)}function b(){if(c.video.isInViewport()){var a=c.video.element.getIntersectionChangeEntry(),b=a.intersectionRatio,d="number"===typeof b&&isFinite(b)?100*a.intersectionRatio:0;c.f=75<=d}else c.f=!1}var c=this,d=this.f;this.B.run({measure:b,mutate:a})};
g.getPlayingState=function(){return this.j?this.j&&this.D&&!this.l?"playing_auto":"playing_manual":"paused"};g.userInteractedWithAutoPlay=function(){return this.l};var V=null;
function aa(a,b){if(V)return V;if(b)return V=Promise.resolve(!1);var c=a.document.createElement("video");c.setAttribute("muted","");c.setAttribute("playsinline","");c.setAttribute("webkit-playsinline","");c.muted=!0;c.playsinline=!0;c.webkitPlaysinline=!0;c.setAttribute("height","0");c.setAttribute("width","0");M(c,{position:"fixed",top:"0",width:"0",height:"0",opacity:"0"});try{var d=c.play();d&&d.catch&&d.catch(function(){})}catch(f){}return V=Promise.resolve(!c.paused)};function W(a){AMP.BaseElement.call(this,a);this.g=-1;this.h=null;this.o=!1;this.w=this.u=this.s=this.A=this.a=null}m(W,AMP.BaseElement);g=W.prototype;g.preconnectCallback=function(a){this.preconnect.url(X(this));this.preconnect.url("https://s.ytimg.com",a);this.preconnect.url("https://i.ytimg.com",a)};g.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a};g.renderOutsideViewport=function(){return.75};
g.viewportCallback=function(a){this.element.dispatchCustomEvent("amp:video:visibility",{visible:a})};g.buildCallback=function(){var a=this;this.h=Y(this);this.s=new Promise(function(b){a.u=b});this.getPlaceholder()||fa(this);B(this.element);G(this.element,"video-manager").register(this)};
function X(a){if(a.A)return a.A;var b="https://www.youtube.com/embed/"+encodeURIComponent(a.h||"")+"?enablejsapi=1",c=I(a.element);"autoplay"in c&&(delete c.autoplay,x().error("AMP-YOUTUBE","Use autoplay attribute instead of data-param-autoplay"));"playsinline"in c||(c.playsinline="1");var d=a.element.hasAttribute("autoplay");d&&("iv_load_policy"in c||(c.iv_load_policy="3"),c.playsinline="1");var f=[],e;for(e in c){var h=c[e];if(null!=h)if(Array.isArray(h))for(var k=0;k<h.length;k++){var l=h[k];f.push(encodeURIComponent(e)+
"="+encodeURIComponent(l))}else f.push(encodeURIComponent(e)+"="+encodeURIComponent(h))}if(c=f.join("&"))b=b.split("#",2),e=b[0].split("?",2),c=e[0]+(e[1]?"?"+e[1]+"&"+c:"?"+c),b=c+=b[1]?"#"+b[1]:"";return a.A=b}
g.layoutCallback=function(){var a=this,b=this.element.ownerDocument.createElement("iframe"),c=X(this);b.setAttribute("frameborder","0");b.setAttribute("allowfullscreen","true");b.src=c;this.applyFillContent(b);this.a=b;this.w=O(this.win,"message",this.G.bind(this));this.element.appendChild(this.a);var d=this.loadPromise(this.a).then(function(){a.a.contentWindow.postMessage(JSON.stringify(y({event:"listening"})),"*");a.element.dispatchCustomEvent("load")});this.u(d);return d};
g.unlayoutCallback=function(){var a=this;this.a&&(H(this.a),this.a=null);this.w&&this.w();this.g=2;this.s=new Promise(function(b){a.u=b});return!0};g.pauseCallback=function(){this.a&&this.a.contentWindow&&1==this.g&&this.pause()};g.mutatedAttributesCallback=function(a){void 0!==a["data-videoid"]&&(this.h=Y(this),this.a&&Z(this,"loadVideoById",[this.h]))};
function Y(a){return x().assert(a.element.getAttribute("data-videoid"),"The data-videoid attribute is required for <amp-youtube> %s",a.element)}function Z(a,b,c){a.s.then(function(){if(a.a&&a.a.contentWindow){var d=JSON.stringify(y({event:"command",func:b,args:c||""}));a.a.contentWindow.postMessage(d,"*")}})}
g.G=function(a){if("https://www.youtube.com"==a.origin&&a.source==this.a.contentWindow&&a.data&&("[object Object]"===v.call(a.data)||p(a.data,"{"))){var b;if("[object Object]"===v.call(a.data))b=a.data;else a:{try{b=JSON.parse(a.data);break a}catch(c){}b=void 0}a=b;void 0!==a&&("infoDelivery"==a.event&&a.info&&void 0!==a.info.playerState?(this.g=a.info.playerState,2==this.g||0==this.g?this.element.dispatchCustomEvent("pause"):1==this.g&&this.element.dispatchCustomEvent("play")):"infoDelivery"==a.event&&
a.info&&void 0!==a.info.muted&&this.o!=a.info.muted&&(this.o=a.info.muted,this.element.dispatchCustomEvent(this.o?"muted":"unmuted")))}};
function fa(a){var b=a.element.ownerDocument.createElement("img"),c=a.h||"";M(b,{"object-fit":"cover",visibility:"hidden"});b.src="https://i.ytimg.com/vi/"+encodeURIComponent(c)+"/sddefault.jpg#404_is_fine";b.setAttribute("placeholder","");b.setAttribute("referrerpolicy","origin");a.applyFillContent(b);a.element.appendChild(b);a.loadPromise(b).then(function(){if(120==b.naturalWidth&&90==b.naturalHeight)throw Error("sddefault.jpg is not found");}).catch(function(){b.src="https://i.ytimg.com/vi/"+encodeURIComponent(c)+
"/hqdefault.jpg";return a.loadPromise(b)}).then(function(){M(b,{visibility:""})})}g.supportsPlatform=function(){return!0};g.isInteractive=function(){return!0};g.play=function(){Z(this,"playVideo")};g.pause=function(){Z(this,"pauseVideo")};g.mute=function(){Z(this,"mute")};g.unmute=function(){Z(this,"unMute")};g.showControls=function(){};g.hideControls=function(){};AMP.registerElement("amp-youtube",W);
})});
//# sourceMappingURL=amp-youtube-0.1.js.map

