(self.AMP=self.AMP||[]).push({n:"amp-fx-parallax",v:"123456789",f:(function(AMP){var k=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function l(a){if(!a)return[];for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return b};Date.now();self.log=self.log||{user:null,dev:null};var m=self.log;function p(a,b){a=a.__AMP_TOP||a;return q(a,b)}function r(a){a=t(a);a=u(a);return q(a,"viewport")}function t(a){return a.nodeType?p((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function u(a){a=t(a);return a.isSingleDoc()?a.win:a}function q(a,b){var c=w(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function w(a){var b=a.services;b||(b=a.services={});return b};var x=null;Promise.resolve();function y(a){a:{var b;b:{try{b=a.document.cookie;break b}catch(g){}b=void 0}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var c=a[b].trim(),d=c.indexOf("=");if(-1!=d&&"AMP_EXP"==decodeURIComponent(c.substring(0,d).trim())){a=decodeURIComponent(c.substring(d+1).trim());break a}}a=null}var f=a,e=f?f.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<e.length;b++)0!=e[b].length&&("-"==e[b][0]?a[e[b].substr(1)]=!1:a[e[b]]=!0);return a};function z(){this.a=null}z.prototype.add=function(a){var b=this;this.a||(this.a=[]);this.a.push(a);return function(){b.remove(a)}};z.prototype.remove=function(a){this.a&&(a=this.a.indexOf(a),-1<a&&this.a.splice(a,1))};z.prototype.removeAll=function(){this.a&&(this.a.length=0)};z.prototype.fire=function(a){if(this.a)for(var b=this.a,c=0;c<b.length;c++)(0,b[c])(a)};z.prototype.getHandlerCount=function(){return this.a?this.a.length:0};var B,C="Webkit webkit Moz moz ms O o".split(" ");function D(a){return"loading"!=a.readyState&&"uninitialized"!=a.readyState};function E(a){this.c=new z;this.h=0;F(this,a.win)}function F(a,b){var c=b.document,d=r(c),f=p(b,"vsync"),e=l(c.querySelectorAll("[amp-fx-parallax]")).map(function(b){return new G(b,a.f)}),g=a.j.bind(a,e,d);d.onScroll(function(){return f.mutate(g)});g()}E.prototype.j=function(a,b){var c=this,d=b.getScrollTop(),f=this.h,e=f-d;a.forEach(function(a){a.shouldUpdate(b)&&(a.update(e),c.h=d)});this.c.fire(d)};E.prototype.f=function(a){return"translate3d(0,"+a.toFixed(2)+"px,0)"};E.prototype.l=function(a){this.c.add(a)};
E.prototype.m=function(a){this.c.remove(a)};function G(a,b){var c=a.getAttribute("amp-fx-parallax");this.g=a;this.f=b;this.i=(c?parseFloat(c):.5)-1;this.b=0}
G.prototype.update=function(a){this.b+=a*this.i;a=this.g;var b={transform:this.f(this.b)},c;for(c in b){var d=a,f=b[c],e;e=d.style;var g=c;if(2>g.length?0:0==g.lastIndexOf("--",0))e=g;else{B||(B=Object.create(null));var n=B[g];if(!n){n=g;if(void 0===e[g]){var h;h=g;h=h.charAt(0).toUpperCase()+h.slice(1);b:{for(var v=0;v<C.length;v++){var A=C[v]+h;if(void 0!==e[A]){h=A;break b}}h=""}void 0!==e[h]&&(n=h)}B[g]=n}e=n}e&&(d.style[e]=f)}};
G.prototype.shouldUpdate=function(a){var b=a.getRect(),c=a.getLayoutRect(this.g);c.top-=b.top;c.bottom=c.top+c.height;a=c;return 0<=a.bottom&&a.top<=b.height};var H=p(AMP.win,"ampdoc").getAmpDoc();
(function(a,b){var c=D,d=c(a);if(d)b(a);else{var f=function(){c(a)&&(d||(d=!0,b(a)),a.removeEventListener("readystatechange",f))};a.addEventListener("readystatechange",f)}})(H.win.document,function(){var a=H.getRootNode(),b;var c=AMP.win;if(!x){x=Object.create(null);if(c.AMP_CONFIG)for(b in c.AMP_CONFIG){var d=c.AMP_CONFIG[b];"number"===typeof d&&0<=d&&1>=d&&(x[b]=Math.random()<d)}if(c.AMP_CONFIG&&Array.isArray(c.AMP_CONFIG["allow-doc-opt-in"])&&0<c.AMP_CONFIG["allow-doc-opt-in"].length&&(b=c.AMP_CONFIG["allow-doc-opt-in"],
d=c.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var d=d.getAttribute("content").split(","),f=0;f<d.length;f++)-1!=b.indexOf(d[f])&&(x[d[f]]=!0);Object.assign(x,y(c));if(c.AMP_CONFIG&&Array.isArray(c.AMP_CONFIG["allow-url-opt-in"])&&0<c.AMP_CONFIG["allow-url-opt-in"].length){b=c.AMP_CONFIG["allow-url-opt-in"];d=c.location.originalHash||c.location.hash;c=Object.create(null);if(d)for(var e;e=k.exec(d);)f=decodeURIComponent(e[1]).trim(),e=e[2]?decodeURIComponent(e[2]).trim():
"",c[f]=e;for(d=0;d<b.length;d++)f=c["e-"+b[d]],"1"==f&&(x[b[d]]=!0),"0"==f&&(x[b[d]]=!1)}}b=x;b=!!b["amp-fx-parallax"];if(m.user)c=m.user;else throw Error("failed to call initLogConstructor");c.assert(b,'Experiment "amp-fx-parallax" is disabled.');a=t(a);b=u(a);c=w(b);(d=c["amp-fx-parallax"])||(d=c["amp-fx-parallax"]={obj:null,promise:null,resolve:null,context:null,ctor:null});d.ctor||d.obj||(d.ctor=E,d.context=a,d.resolve&&q(b,"amp-fx-parallax"));q(b,"amp-fx-parallax")});
})});
//# sourceMappingURL=amp-fx-parallax-0.1.js.map

