(self.AMP=self.AMP||[]).push({n:"amp-ad-network-adsense-impl",v:"123456789",f:(function(AMP){var h;function q(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}function aa(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c}function t(a,b){return b.length>a.length?!1:0==a.lastIndexOf(b,0)};var ba=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function v(a){var b=Object.create(null);if(!a)return b;for(var c;c=ba.exec(a);){var d=decodeURIComponent(c[1]).trim(),e=c[2]?decodeURIComponent(c[2]).trim():"";b[d]=e}return b};var ca="";
function w(a){var b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;if(c.context&&c.context.mode)c=c.context.mode;else{var d=v(c.location.originalHash||c.location.hash),e=v(c.location.search);ca||(ca=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"01123456789");c={localDev:!1,development:!("1"!=d.development&&!c.AMP_DEV_MODE),examiner:"2"==d.development,filter:d.filter,minified:!0,lite:void 0!=e.amp_lite,test:!1,log:d.log,version:"123456789",rtvVersion:ca}}c=b.AMP_MODE=c}return c}
;var da=Object.prototype.toString;function ea(a){return"[object Object]"===da.call(a)}function fa(a){var b=ga,c;for(c in b)if(b[c]===a)return!0;return!1};Date.now();function ha(a){var b=a.message,c=String(Math.random());a.message=c;if(a.message===c)return a.message=b,a;var b=Error(a.message),d;for(d in a)b[d]=a[d];b.stack=a.stack;return b}function ia(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];e instanceof Error&&!b?b=ha(e):(c&&(c+=" "),c+=e)}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}function ja(a){var b=ia.apply(null,arguments);setTimeout(function(){self.reportError(b);throw b;})}
self.log=self.log||{user:null,dev:null};var ka=self.log;function y(){if(ka.user)return ka.user;throw Error("failed to call initLogConstructor");}function z(){if(ka.dev)return ka.dev;throw Error("failed to call initLogConstructor");};function B(a){var b=Object.create(null);a&&Object.assign(b,a);return b};function la(a){return"undefined"!==typeof TextDecoder?Promise.resolve((new TextDecoder("utf-8")).decode(a)):new Promise(function(b,c){var d=new FileReader;d.onerror=function(){c(d.error)};d.onloadend=function(){b(d.result)};d.readAsText(new Blob([a]))})}function ma(a){for(var b=new Uint8Array(a.length),c=0;c<a.length;c++){var d=a.charCodeAt(c);b[c]=d}return b};var C=self.AMP_CONFIG||{},na=C.thirdPartyFrameHost||"ampproject.net",oa=C.cdnUrl||"https://cdn.ampproject.org",pa=("string"==typeof C.cdnProxyRegex?new RegExp(C.cdnProxyRegex):C.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org/,qa=/^https?:\/\/localhost(:\d+)?$/;var ra,sa,ta=["javascript:","data:","vbscript:"];
function D(a,b){ra||(ra=self.document.createElement("a"),sa=self.UrlCache||(self.UrlCache=Object.create(null)));var c=sa[a];if(c)return c;var d=ra;d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=d.origin&&
"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;var f=e,g=f;return b?g:sa[a]=g}function ua(a,b,c){if(!b)return a;var d=a.split("#",2),e=d[0].split("?",2),f=e[0]+(e[1]?c?"?"+b+"&"+e[1]:"?"+e[1]+"&"+b:"?"+b);return f+=d[1]?"#"+d[1]:""}
function va(a){var b=[],c;for(c in a){var d=a[c];if(null!=d)if(Array.isArray(d))for(var e=0;e<d.length;e++){var f=d[e];b.push(encodeURIComponent(c)+"="+encodeURIComponent(f))}else e=d,b.push(encodeURIComponent(c)+"="+encodeURIComponent(e))}return b.join("&")}function wa(a){"string"==typeof a&&(a=D(a));return"https:"==a.protocol||"localhost"==a.hostname||aa(a.hostname,".localhost")}function xa(a){"string"==typeof a&&(a=D(a));return pa.test(a.origin)}
function ya(a){if(!a)return!0;"string"==typeof a&&(a=D(a));return!ta.includes(a.protocol)};function za(a){a=G(a);return Aa(a,"performance")?H(a,"performance"):null}function Da(a){if(a.nodeType){var b=Ea((a.ownerDocument||a).defaultView);if(b)return b}return I(a,"url-replace")}function Fa(a,b){var c=G(a);Ea(a);Ga(a,a,function(){return b});H(a,"url-replace")}function Ea(a){var b=G(a);return a!=b&&Aa(a,"url-replace")?H(a,"url-replace"):null}function K(a,b){a=G(a);return H(a,b)}function I(a,b){a=Ha(a);a=Ia(a);return H(a,b)}function Ja(a,b){return Ka(Ia(a),b)}
function La(a,b){return Ma(Ia(a),b)}function G(a){return a.__AMP_TOP||a}function Ha(a){return a.nodeType?K((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function Ia(a){a=Ha(a);return a.isSingleDoc()?a.win:a}function H(a,b){Aa(a,b);var c=L(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function Ga(a,b,c){var d=L(a),e=d["url-replace"];e||(e=d["url-replace"]={obj:null,promise:null,resolve:null,context:null,ctor:null});e.ctor||e.obj||(e.ctor=c,e.context=b,e.resolve&&H(a,"url-replace"))}function Ka(a,b){var c=Ma(a,b);if(c)return c;var d,e=new Promise(function(a){d=a});L(a)[b]={obj:null,promise:e,resolve:d,context:null,ctor:null};return e}function Ma(a,b){var c=L(a)[b];if(c){if(c.promise)return c.promise;H(a,b);return c.promise=Promise.resolve(c.obj)}return null}
function L(a){var b=a.services;b||(b=a.services={});return b}function Na(a){a=L(a);var b={},c;for(c in a)if(b.id=c,Object.prototype.hasOwnProperty.call(a,b.id)){var d=a[b.id];d.obj?Oa(b.id,d.obj):d.promise&&d.promise.then(function(a){return function(b){return Oa(a.id,b)}}(b));b={id:b.id}}}function Oa(a,b){if("function"==typeof b.dispose)try{b.dispose()}catch(c){z().error("SERVICE","failed to dispose service",a,c)}}function Aa(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};var M=null;Promise.resolve();function O(a,b){var c=Pa(a);return!!c[b]}
function Pa(a){if(M)return M;M=Object.create(null);if(a.AMP_CONFIG)for(var b in a.AMP_CONFIG){var c=a.AMP_CONFIG[b];"number"===typeof c&&0<=c&&1>=c&&(M[b]=Math.random()<c)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length){var d=a.AMP_CONFIG["allow-doc-opt-in"];if(b=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')){var e=b.getAttribute("content").split(",");for(b=0;b<e.length;b++)-1!=d.indexOf(e[b])&&(M[e[b]]=!0)}}Object.assign(M,
Qa(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){b=a.AMP_CONFIG["allow-url-opt-in"];var f=a.location.originalHash||a.location.hash;a=v(f);for(var g=0;g<b.length;g++){var k=a["e-"+b[g]];"1"==k&&(M[b[g]]=!0);"0"==k&&(M[b[g]]=!1)}}return M}
function Qa(a){a:{var b;b:{try{b=a.document.cookie;break b}catch(g){}b=void 0}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var c=a[b].trim(),d=c.indexOf("=");if(-1!=d&&"AMP_EXP"==decodeURIComponent(c.substring(0,d).trim())){a=decodeURIComponent(c.substring(d+1).trim());break a}}a=null}var e=a,f=e?e.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<f.length;b++)0!=f[b].length&&("-"==f[b][0]?a[f[b].substr(1)]=!1:a[f[b]]=!0);return a}
function Ra(a,b){a.experimentBranches=a.experimentBranches||{};for(var c in b)if(b.hasOwnProperty(c)&&!a.experimentBranches.hasOwnProperty(c))if(!b[c].isTrafficEligible||!b[c].isTrafficEligible(a))a.experimentBranches[c]=null;else if(!a.experimentBranches[c]&&O(a,c)){var d=b[c].branches,e=d;a.experimentBranches[c]=e[Math.floor(Math.random()*e.length)]||null}};var Sa={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","`":"&#x60;"},Ta=/(&|<|>|"|'|`)/g;function Ua(a,b,c){a=a.createElement(b);for(var d in c)a.setAttribute(d,c[d]);return a}function Va(a,b){for(var c,d=a;d&&d!==c;d=d.parentElement)if(b(d))return d;return null}function Wa(a){var b="A";if(a.closest)return a.closest(b);b=b.toUpperCase();return Va(a,function(a){return a.tagName==b})}var Xa;function Ya(a){return a?a.replace(Ta,Za):a}function Za(a){return Sa[a]};function $a(a){return a.ampExtendedElements?!!a.ampExtendedElements["amp-analytics"]:!1}function ab(a){return bb(a,"amp-analytics-instrumentation",void 0).then(function(a){return y().assert(a,"Service %s was requested to be provided through %s, but %s is not loaded in the current page. To fix this problem load the JavaScript file for %s in this page.","amp-analytics-instrumentation","amp-analytics","amp-analytics","amp-analytics")})}
function bb(a,b,c){var d=Ha(a),e=La(a,b);return e?e:Promise.resolve().then(function(){return!c&&$a(d.win)?Ja(a,b):d.whenBodyAvailable().then(function(){return c?La(a,b):$a(d.win)?Ja(a,b):null})})};function cb(a){return I(a,"documentInfo").get()}function P(a){return K(a,"extensions")}function Q(a){return I(a,"viewer")};function db(a){var b="AMP_ECID_GOOGLE",c="_ga",d=bb(a,"cid").then(function(a){if(a)return a.get({scope:b,createCookieIfNotPresent:!0,cookieName:c},Promise.resolve(void 0)).catch(function(a){z().error("AD-CID",a)})});return K(a.win,"timer").timeoutPromise(1E3,d,"cid timeout").catch(function(a){z().warn("AD-CID",a)})};var eb={"-":"+",_:"/",".":"="};function fb(a){var b=atob(a.replace(/[-_.]/g,function(a){return eb[a]}));return ma(b)};function gb(a){for(var b=a.length,c=5381,d=0;d<b;d++)c=33*c^a.charCodeAt(d);return String(c>>>0)};function hb(a){for(var b=[],c=0;a&&1==a.nodeType&&25>c;){var d="";a.id&&(d="/"+a.id);var e=a.nodeName.toLowerCase();b.push(""+e+d+ib(a));c++;a=a.parentElement}return b.join()}function ib(a){for(var b=a.nodeName,c=0,d=0,e=a.previousElementSibling;e&&25>d&&100>c;)e.nodeName==b&&d++,c++,e=e.previousElementSibling;return 25>d&&100>c?"."+d:""};var jb={"AMP-CAROUSEL":"ac","AMP-FX-FLYING-CARPET":"fc","AMP-LIGHTBOX":"lb","AMP-STICKY-AD":"sa"};function kb(a){var b=a.crypto&&(a.crypto.subtle||a.crypto.webkitSubtle);return b&&(xa(a.location)||!1||!1)}function lb(a){var b=a.element.getAttribute("type"),c=a.win;return("doubleclick"==b||"adsense"==b)&&O(c,"a4aProfilingRate")}
function mb(a,b){var c=a.element,d=a.win;d.ampAdGoogleIfiCounter=d.ampAdGoogleIfiCounter||1;for(var e=a.getPageLayoutBox(),f=d,g=0;f!=f.parent&&100>g;)f=f.parent,g++;for(var k=g,l={},f=c.parentElement,m=0;f&&20>m;f=f.parentElement,m++)g=f.tagName.toUpperCase(),jb[g]&&(l[jb[g]]=!0);var n=l[jb["AMP-FX-FLYING-CARPET"]]||l[jb["AMP-STICKY-AD"]]?"1":"0",r=c.getAttribute("data-experiment-id");b&&(r=ob(b,r));var u=Object.keys(l);return{ifi:d.ampAdGoogleIfiCounter++,adf:gb(hb(c)),nhd:k,eid:r,adx:e.left,ady:e.top,
oid:"2",pfx:n,rc:a.fromResumeCallback?1:null,act:u.length?u.join():null}}
function pb(a,b,c){var d;d=void 0===d?"html":d;var e=Q(b).getReferrerUrl();return db(b).then(function(b){return e.then(function(e){var f=cb(a.document);a.gaGlobal=a.gaGlobal||{cid:b,hid:f.pageViewId};var g=a.screen,m=I(a.document,"viewport"),n=m.getRect(),r=m.getSize(),u=qb(a,b),p=n.width,x=n.height,E=g?g.availWidth:null,F=g?g.availHeight:null,J=g?g.colorDepth:null,Ba=g?g.width:null,g=g?g.height:null,Ca=-(new Date).getTimezoneOffset(),T;try{T=a.history.length}catch(nb){T=0}return{is_amp:"3",amp_v:"123456789",
d_imp:"1",c:u,dt:c,output:d,biw:p,bih:x,u_aw:E,u_ah:F,u_cd:J,u_w:Ba,u_h:g,u_tz:Ca,u_his:T,isw:a!=a.top?r.width:null,ish:a!=a.top?r.height:null,art:a.AMP_CONFIG&&a.AMP_CONFIG.canary?"2":null,url:f.canonicalUrl,top:a!=a.top?rb(a):null,loc:a.location.href==f.canonicalUrl?null:a.location.href,ref:e}})})}
function sb(a,b,c,d){var e=mb(a,d);return pb(a.win,a.getAmpDoc(),b).then(function(a){Object.assign(c,e,a);var d=c,f={name:"trunc",value:"1"},l=[],f=f&&null!=f.value&&""!==f.value?encodeURIComponent(f.name)+"="+encodeURIComponent(String(f.value)):null,m=4040;f&&(m-=f.length+1);for(var n=Object.keys(d),r=0;r<n.length;r++){var u=n[r],p=d[u];if(null!=p&&""!==p){var u=encodeURIComponent(u)+"=",p=encodeURIComponent(String(p)),x=u.length+p.length+1;if(x>m){(d=p.substr(0,m-u.length-1).replace(/%\w?$/,""))&&
l.push(u+d);f&&l.push(f);break}l.push(u+p);m-=x}}l=(l.length?"https://googleads.g.doubleclick.net/pagead/ads?"+l.join("&"):"https://googleads.g.doubleclick.net/pagead/ads")+"&dtd=";d=Date.now()-b;return l+(1E6<=d?"M":0<=d?d:"-M")})}
function tb(a,b){var c=null,d=null;try{if(b.has("X-AmpAdSignature")&&(c=fb(b.get("X-AmpAdSignature"))),b.has("X-CreativeSize")){var e=b.get("X-CreativeSize");/[0-9]+x[0-9]+/.test(e);var f=e.split("x").map(function(a){return Number(a)}),d={width:f[0],height:f[1]}}}finally{return Promise.resolve({creative:a,signature:c,size:d})}}
function rb(a){var b=a.location.ancestorOrigins;if(b){var c=a.location.origin,d=b[b.length-1];if(c==d)return a.top.location.href;var e=ub(a);return e==a||c==b[b.length-2]?e.document.referrer:d}try{return a.top.location.href}catch(f){}a=ub(a);try{return a.document.referrer}catch(f){}return null}function ub(a){for(var b=0;a.parent!=a.parent.parent&&100>b;)a=a.parent,b++;return a}
function qb(a,b){if(!a.ampAdPageCorrelator){var c;c=b;var d=cb(a.document).pageViewId,d=Number(d||0);c=c?d+c.replace(/\D/g,"")%1E6*1E6:Math.floor(4503599627370496*Math.random());a.ampAdPageCorrelator=c}return a.ampAdPageCorrelator}
function vb(a){if(!a.has("X-AmpAnalytics"))return null;try{var b=JSON.parse(a.get("X-AmpAnalytics"));Array.isArray(b.url);var c=b.url;if(!c.length)return null;for(var d={transport:{beacon:!1,xhrpost:!1},triggers:{continuousVisible:{on:"visible",visibilitySpec:{selector:"amp-ad",selectionMethod:"closest",visiblePercentageMin:50,continuousTimeMin:1E3}},continuousVisibleIniLoad:{on:"ini-load",selector:"amp-ad",selectionMethod:"closest"},continuousVisibleRenderStart:{on:"render-start",selector:"amp-ad",
selectionMethod:"closest"}}},e=B(void 0),f=1;f<=c.length;f++)e["visibility"+f]=""+c[f-1];d.requests=e;d.triggers.continuousVisible.request=Object.keys(e);return d}catch(g){z().error("AMP-A4A","Invalid analytics",g,a.get("X-AmpAnalytics"))}return null}function ob(a,b){var c=a.filter(function(a){return Number(a)}).join(",");b=b||"";return b+(b&&c?",":"")+c};function wb(a,b,c,d,e,f,g){if(!kb(a))return!1;var k=xb(a,b,c,d.control,d.experiment,f.control,f.experiment,g?g.control:null,g?g.experiment:null),l={};l[c]={isTrafficEligible:function(){return!0},branches:[e.control,e.experiment]};Ra(a,l);if(O(a,c)){var m=a.experimentBranches[c];if(m){yb(m,b);var n=za(a);n&&n.addEnabledExperiment(c+"-"+m)}k?yb("2088461",b):yb("2088462",b);var r=m==e.experiment||m==d.experiment||m==f.experiment||"117152632"==m;return r==!zb(a,b)}return zb(a,b)}
function xb(a,b,c,d,e,f,g,k,l){var m="117152632",n=Q(b).getParam("exp")||v(a.location.search).exp;if(!n)return!1;var r=(b=/(^|,)(a4a:[^,]*)/.exec(n))&&b[2];if(!r)return!1;b=r.split(":",2)[1];var u={"-1":m,0:null,1:d,2:e,3:f,4:g,5:k,6:l};if(u.hasOwnProperty(b)){b=u[b];a.experimentBranches=a.experimentBranches||{};var p=!!b,x=O(a,c),p=!(void 0!==p?!p:x);p!=x&&(Pa(a)[c]=p);a.experimentBranches[c]=b;return!0}z().warn("A4A-CONFIG","Unknown a4a URL parameter: ",r," expected one of -1 (manual), 0 (not in experiment), 1 (control branch), or 2 (a4a experiment branch)");
return!1}function Ab(a){return a?a.split(","):[]}function R(a,b){return Ab(a.getAttribute("data-experiment-id")).some(function(a){return a===b})}function zb(a,b){switch(b.getAttribute("type")){case "adsense":return O(a,"a4aFastFetchAdSenseLaunched");case "doubleclick":return O(a,"a4aFastFetchDoubleclickLaunched");default:return!1}}function Bb(a){return a.every(function(a){return!isNaN(parseInt(a,10))})}
function yb(a,b){var c=b.getAttribute("data-experiment-id");c&&Bb(Ab(c))?b.setAttribute("data-experiment-id",ob([a],c)):b.setAttribute("data-experiment-id",a)};var Cb={control:"117152652",experiment:"117152653"},Db={control:"117152654",experiment:"117152655"},Eb={control:"2092617",experiment:"2092618"},Fb={control:"117152670",experiment:"117152671"},Gb={control:"2092615",experiment:"2092616"};var Hb={control:"117152662",experiment:"117152663"},Ib={control:"117152664",experiment:"117152665"},Jb={control:"2092619",experiment:"2092620"},Kb={control:"117152680",experiment:"117152681"},Lb={control:"2092613",experiment:"2092614"},Mb={control:"21060540",experiment:"21060541"};B({adsense:function(a,b){var c,d;O(a,"a4aFastFetchAdSenseLaunched")?(c=Eb,d=Gb):(c=Cb,d=Fb);return!!b.getAttribute("data-ad-client")&&wb(a,b,"expAdsenseA4A",c,d,Db)},doubleclick:function(a,b){if(b.hasAttribute("useSameDomainRenderingUntilDeprecated"))return!1;var c=b.hasAttribute("data-use-beta-a4a-implementation"),d,e;O(a,"a4aFastFetchDoubleclickLaunched")?(d=Jb,e=Lb):(d=Hb,e=Kb);var f=wb(a,b,"expDoubleclickA4A",d,e,Ib,Mb)||c&&(xa(a.location)||!1||!1);f&&c&&!R(b,"117152632")&&b.setAttribute("data-experiment-id",
"2077831");return f},triplelift:function(a,b){var c;return!!b.getAttribute("data-use-a4a")&&!!(c=b.getAttribute("src"))&&0==c.indexOf("https://ib.3lift.com/")},cloudflare:function(){return!0},gmossp:function(a,b){a=b.getAttribute("src");return!!b.getAttribute("data-use-a4a")&&!!a&&t(a,"https://sp.gmossp-sp.jp")}});
var Nb={google:"https://cdn.ampproject.org/amp-ad-verifying-keyset.json","google-dev":"https://cdn.ampproject.org/amp-ad-verifying-keyset-dev.json",cloudflare:"https://amp.cloudflare.com/amp-ad-verifying-keyset.json","cloudflare-dev":"https://amp.cloudflare.com/amp-ad-verifying-keyset-dev.json"};function Ob(a,b){if(!(a.defaultPrevented||0!=a.buttons&&1!=a.buttons||a.ctrlKey||a.altKey||a.shiftKey||a.metaKey)){var c=Pb(a);if(c&&c.eventualUrl&&!1!==a.isTrusted){var d=encodeURIComponent,e;e=c.a.href;var f=encodeURIComponent("amp")+"="+encodeURIComponent("1");e=ua(e,f,!0);var g="click="+d(e);e=c.eventualUrl;e=-1==c.eventualUrl.indexOf("#")?e+("#"+g):e+("&"+g);d=c.a.ownerDocument.defaultView;(f=d.location.ancestorOrigins)&&"http://localhost:8000"==f[f.length-1]&&(e=e.replace(D(c.eventualUrl).host+
"/c/","http://localhost:8000/max/"));a.preventDefault();if(b)b(e);else{a=e;e=(c.a.target||"_top").toLowerCase();if(d.location.ancestorOrigins)if(f=d.location.ancestorOrigins,2>f.length||-1==f[f.length-1].indexOf(".google."))f=null;else{var k=f[f.length-2],l;(l=xa(k))||(l=k,"string"==typeof l&&(l=D(l)),l=qa.test(l.origin));if(l){l=d;for(var m=0;m<f.length-1;m++)l=l.parent;f={win:l,origin:k}}else f=null}else f=null;if(f)f.win.postMessage("a2a;"+JSON.stringify(B({url:a})),f.origin);else{var n;try{n=
d.open(a,e,void 0)}catch(r){z().error("DOM","Failed to open url on target: ",e,r)}n||"_top"==e||d.open(a,"_top")}}}}}function Pb(a){if(a=Va(a.target,function(a){return"A"==a.tagName&&a.href}))return{eventualUrl:Qb(a),a:a}}function Qb(a){var b=a.getAttribute("data-url-param-name")||"adurl",c=v(a.search)[b];if(c&&xa(c)&&t(D(c).pathname,"/c/"))return c};function Rb(){this.f=null}h=Rb.prototype;h.add=function(a){var b=this;this.f||(this.f=[]);this.f.push(a);return function(){b.remove(a)}};h.remove=function(a){this.f&&(a=this.f.indexOf(a),-1<a&&this.f.splice(a,1))};h.removeAll=function(){this.f&&(this.f.length=0)};h.fire=function(a){if(this.f)for(var b=this.f,c=0;c<b.length;c++)(0,b[c])(a)};h.getHandlerCount=function(){return this.f?this.f.length:0};var Xb,Yb="Webkit webkit Moz moz ms O o".split(" ");function S(a,b,c){var d;var e=a.style;if(!t(b,"--")){Xb||(Xb=B());var f=Xb[b];if(!f){f=b;if(void 0===e[b]){var g=b.charAt(0).toUpperCase()+b.slice(1);b:{for(var k=0;k<Yb.length;k++){var l=Yb[k]+g;if(void 0!==e[l]){g=l;break b}}g=""}void 0!==e[g]&&(f=g)}Xb[b]=f}b=f}b&&(a.style[b]=d?c+d:c)}function U(a,b){for(var c in b)S(a,c,b[c])}function Zb(a,b){var c={};b.forEach(function(a){c[a]=null});U(a,c)};function $b(a,b,c){function d(a){try{return g(a)}catch(m){throw self.reportError(m),m;}}var e=void 0,f=a,g=c,k=e||!1;f.addEventListener(b,d,k);return function(){f&&f.removeEventListener(b,d,k);d=f=g=null}};function ac(a,b,c){var d=c,e=$b(a,b,function(a){try{d(a)}finally{d=null,e()}});return e}function bc(a){var b,c;if(a.complete||"complete"==a.readyState||a.document&&"complete"==a.document.readyState)return Promise.resolve(a);var d=new Promise(function(d,f){var e=a.tagName;b="AUDIO"===e||"VIDEO"===e?ac(a,"loadstart",d):ac(a,"load",d);e&&(c=ac(a,"error",f))});return d.then(function(){c&&c();return a},function(){b&&b();var c=a;c&&c.src&&(c=c.src);throw y().createError("Failed to load:",c);})};self.AMPErrors=self.AMPErrors||[];function cc(a){a=parseFloat(a);return"number"===typeof a&&isFinite(a)?a:void 0};var dc={"AMP-FX-FLYING-CARPET":!0,"AMP-LIGHTBOX":!0,"AMP-STICKY-AD":!0};function ec(a){var b;b=void 0===b?1:b;return new Promise(function(c,d){function e(a){l.length<=g&&l.push(a);l.length>g&&d(l)}function f(a){k.length<b&&k.push(a);k.length==b&&c(k)}b=Math.max(b,0);var g=a.length-b;0>g&&d(Error("not enough promises to resolve"));0==a.length&&c([]);for(var k=[],l=[],m=0;m<a.length;m++)Promise.resolve(a[m]).then(f,e)})};function fc(a,b,c){var d=gc(a,b,c);return""===d?bc(a).then(function(){return gc(a,b,c)}):Promise.resolve(d)}function gc(a,b,c){var d=a.performance&&a.performance.timing;if(d&&0!=d.navigationStart&&(a=void 0===c?d[b]:d[c]-d[b],"number"===typeof a&&isFinite(a)))return 0>a?"":a}function hc(a,b){var c=a.performance&&a.performance.navigation;if(c&&void 0!==c[b])return c[b]}function ic(){this.J=void 0;this.i=Object.create(null);this.S=!1}h=ic.prototype;h.initialize=function(){};
h.get=function(a){this.S||(this.initialize(),this.S=!0);return this.i[a]};h.set=function(a,b){a.indexOf("RETURN");this.i[a]=this.i[a]||{sync:void 0,async:void 0};this.i[a].sync=b;this.J=void 0;return this};h.setAsync=function(a,b){a.indexOf("RETURN");this.i[a]=this.i[a]||{sync:void 0,async:void 0};this.i[a].async=b;this.J=void 0;return this};h.setBoth=function(a,b,c){return this.set(a,b).setAsync(a,c)};
h.getExpr=function(a){var b=this;this.S||(this.initialize(),this.S=!0);var c=a?Object.keys(a):null;if(c&&0<c.length){var d=Object.keys(this.i);c.forEach(function(a){void 0===b.i[a]&&d.push(a)});return jc(d)}this.J||(this.J=jc(Object.keys(this.i)));return this.J};function jc(a){a.sort(function(a,b){return b.length-a.length});var b=a.join("|");return new RegExp("\\$?("+b+")(?:\\(([0-9a-zA-Z-_.,]+)\\))?","g")};var kc="RANDOM COUNTER CANONICAL_URL CANONICAL_HOST CANONICAL_HOSTNAME CANONICAL_PATH DOCUMENT_REFERRER TITLE AMPDOC_URL AMPDOC_HOST AMPDOC_HOSTNAME SOURCE_URL SOURCE_HOST SOURCE_HOSTNAME SOURCE_PATH PAGE_VIEW_ID CLIENT_ID VARIANT VARIANTS SHARE_TRACKING_INCOMING SHARE_TRACKING_OUTGOING TIMESTAMP TIMEZONE SCROLL_TOP SCROLL_LEFT SCROLL_HEIGHT SCROLL_WIDTH VIEWPORT_HEIGHT VIEWPORT_WIDTH SCREEN_WIDTH SCREEN_HEIGHT AVAILABLE_SCREEN_HEIGHT AVAILABLE_SCREEN_WIDTH SCREEN_COLOR_DEPTH DOCUMENT_CHARSET BROWSER_LANGUAGE VIEWER TOTAL_ENGAGED_TIME AMP_VERSION".split(" ");
function lc(a,b){ic.call(this);this.ja=Da(a).getVariableSource();this.L=b}q(lc,ic);
lc.prototype.initialize=function(){var a=this;this.set("AD_NAV_TIMING",function(b,c){y().assert(b,"The first argument to AD_NAV_TIMING, the start attribute name, is required");return gc(a.L,b,c)}).setAsync("AD_NAV_TIMING",function(b,c){y().assert(b,"The first argument to AD_NAV_TIMING, the start attribute name, is required");return fc(a.L,b,c)});this.set("AD_NAV_TYPE",function(){return hc(a.L,"type")});this.set("AD_NAV_REDIRECT_COUNT",function(){return hc(a.L,"redirectCount")});for(var b=0;b<kc.length;b++){var c=
kc[b],d=this.ja.get(c);this.set(c,d.sync).setAsync(c,d.async)}};function mc(a,b,c){var d,e=Date.now(),f=b.getAttribute("width"),g=b.getAttribute("height");d=d?d:B(void 0);d.width=cc(f);d.height=cc(g);var k=a.location.href;"about:srcdoc"==k&&(k=a.parent.location.href);var l=cb(b),m=Q(b),f=m.getUnconfirmedReferrerUrl(),n=b.getPageLayoutBox(),g=l.sourceUrl,r=l.canonicalUrl,u=l.pageViewId,p={href:k},x=b.tagName,E={localDev:!1,development:w(void 0).development,filter:w(void 0).filter,minified:!0,lite:w(void 0).lite,test:!1,log:w(void 0).log,version:w(void 0).version,
rtvVersion:w(void 0).rtvVersion},F=a;d._context=B({ampcontextVersion:"123456789",ampcontextFilepath:oa+"/123456789/ampcontext-v0.js",sourceUrl:g,referrer:f,canonicalUrl:r,pageViewId:u,location:p,startTime:e,tagName:x,mode:E,canary:!(!F.AMP_CONFIG||!F.AMP_CONFIG.canary),hidden:!m.isVisible(),initialLayoutRect:n?{left:n.left,top:n.top,width:n.width,height:n.height}:null,initialIntersection:b.getIntersectionChangeEntry(),domFingerprint:gb(hb(b)),experimentToggles:Pa(a),
sentinel:c});var J=b.getAttribute("src");J&&(d.src=J);return d};function nc(a){this.N=K(a,"crypto")}nc.prototype.isAvailable=function(){return this.N.isPkcsAvailable()};nc.prototype.importPublicKey=function(a,b){var c=this;return this.N.importPkcsKey(b).then(function(d){if("string"!=typeof b.n||"string"!=typeof b.e)throw Error("missing fields in JSON Web Key");var e=fb(b.n),f=fb(b.e),g=oc(e),k=oc(f),l=new Uint8Array(g.length+k.length);l.set(g);l.set(k,g.length);return c.N.sha1(l).then(function(b){return{serviceName:a,cryptoKey:d,hash:new Uint8Array(b,0,4)}})})};
nc.prototype.verifySignature=function(a,b,c){if(!(5<b.length&&0==b[0]&&pc(b,c.hash)))return Promise.resolve(!1);var d=new Uint8Array(a.length+1);d.set(a);d[a.length]=0;return this.N.verifyPkcs(c.cryptoKey,b.subarray(5),d)};function oc(a){var b=new Uint8Array(4+a.length);b[0]=a.length>>24&255;b[1]=a.length>>16&255;b[2]=a.length>>8&255;b[3]=a.length&255;b.set(a,4);return b}function pc(a,b){if(!a||!b)return!1;for(var c=0;4>c;c++)if(a[c+1]!==b[c])return!1;return!0};function qc(a,b){void 0===a["3pla"]&&(a["3pla"]=0);a["3pla"]++;K(a,"timer").timeoutPromise(1E3,b).catch(function(){}).then(function(){a["3pla"]--})};function rc(a,b){b.document.documentElement.addEventListener("click",sc.bind(null,a),!0)}function sc(a,b){var c=Wa(b.target);if(c&&c.href){var d=c.getAttribute("data-a4a-orig-href")||c.getAttribute("href");if(d){var e={CLICK_X:function(){return b.pageX},CLICK_Y:function(){return b.pageY}},f=Da(a).expandSync(d,e,void 0,{CLICK_X:!0,CLICK_Y:!0});f!=d&&(c.getAttribute("data-a4a-orig-href")||c.setAttribute("data-a4a-orig-href",d),c.setAttribute("href",f))}}};function tc(){this.u=B();this.g=null}h=tc.prototype;h.get=function(a){return this.u[a]||null};h.whenSignal=function(a){var b=this.g&&this.g[a];if(!b){var c=this.u[a];if(null!=c)b={promise:"number"==typeof c?Promise.resolve(c):Promise.reject(c)};else var d,e,b={promise:new Promise(function(a,b){d=a;e=b}),resolve:d,reject:e};this.g||(this.g=B());this.g[a]=b}return b.promise};
h.signal=function(a,b){if(null==this.u[a]){var c=b||Date.now();this.u[a]=c;(a=this.g&&this.g[a])&&a.resolve&&(a.resolve(c),a.resolve=void 0,a.reject=void 0)}};h.rejectSignal=function(a,b){null==this.u[a]&&(this.u[a]=b,(a=this.g&&this.g[a])&&a.reject&&(a.reject(b),a.resolve=void 0,a.reject=void 0))};h.reset=function(a){this.u[a]&&delete this.u[a];var b=this.g&&this.g[a];b&&!b.resolve&&delete this.g[a]};function uc(a,b){return{left:0,top:0,width:a,height:b,bottom:0+b,right:0+a}};var vc=["AMP-AD","AMP-ANALYTICS","AMP-PIXEL"],wc;function xc(a,b){yc(a,b)}
function zc(a,b,c,d){var e=G(a.ownerDocument.defaultView),f=P(e);S(a,"visibility","hidden");a.setAttribute("referrerpolicy","unsafe-url");c.extensionIds&&c.extensionIds.forEach(function(a){return f.loadExtension(a)});var g=Ac(c);a.onload=function(){a.readyState="complete"};var k;void 0===wc&&(wc="srcdoc"in HTMLIFrameElement.prototype);if(wc)a.srcdoc=g,k=bc(a),b.appendChild(a);else{a.src="about:blank";b.appendChild(a);var l=a.contentWindow.document;l.open();l.write(g);k=bc(a.contentWindow);l.close()}var m;
m=Bc(a)?Promise.resolve():new Promise(function(b){var c=e.setInterval(function(){Bc(a)&&(b(),e.clearInterval(c))},5);k.catch(function(a){ja(a)}).then(function(){b();e.clearInterval(c)})});return m.then(function(){var b=new Cc(a,c,k);a.__AMP_EMBED__=b;f.installExtensionsInChildWindow(a.contentWindow,c.extensionIds||[],d);Dc(b);return b})}function Bc(a){a=a.contentWindow&&a.contentWindow.document;return!!(a&&"loading"!=a.readyState&&"uninitialized"!=a.readyState&&a.body&&a.body.firstChild)}
function Ac(a){var b=a.html,c=b.toUpperCase(),d=c.indexOf("<HEAD");-1!=d&&(d=c.indexOf(">",d+1)+1);-1==d&&(d=c.indexOf("<BODY"));-1==d&&(d=c.indexOf("<HTML"),-1!=d&&(d=c.indexOf(">",d+1)+1));var e=[];0<d&&e.push(b.substring(0,d));e.push('<base href="'+Ya(a.url)+'">');a.fonts&&a.fonts.forEach(function(a){e.push('<link href="'+Ya(a)+'" rel="stylesheet" type="text/css">')});0<d?e.push(b.substring(d)):e.push(b);return e.join("")}
function Cc(a,b,c){this.iframe=a;this.win=a.contentWindow;this.spec=b;this.host=b.host||null;this.ka=Date.now();this.W=!1;this.ga=new Rb;this.K=this.host?this.host.signals():new tc;this.ma=Promise.all([c,this.whenReady()])}h=Cc.prototype;h.destroy=function(){I(this.iframe,"resources").removeForChildWindow(this.win);Na(this.win)};h.getStartTime=function(){return this.ka};h.getUrl=function(){return this.spec.url};h.signals=function(){return this.K};h.whenReady=function(){return this.K.whenSignal("render-start")};
h.whenWindowLoaded=function(){return this.ma};h.whenIniLoaded=function(){return this.K.whenSignal("ini-load")};function Dc(a){a.host?a.host.renderStarted():a.K.signal("render-start");S(a.iframe,"visibility","");a.win.document&&a.win.document.body&&U(a.win.document.body,{opacity:1,visibility:"visible",animation:"none"});var b;b=a.host?a.host.getLayoutBox():uc(a.win.innerWidth,a.win.innerHeight);Promise.all([a.whenReady(),Ec(a.iframe,a.win,b)]).then(function(){a.K.signal("ini-load")})}h.isVisible=function(){return this.W};
h.onVisibilityChanged=function(a){return this.ga.add(a)};function yc(a,b){a.W!=b&&(a.W=b,a.ga.fire(a.W))}h.getBodyElement=function(){return(this.iframe.contentDocument||this.iframe.contentWindow.document).body};h.getVsync=function(){return K(this.win,"vsync")};h.getResources=function(){return I(this.iframe,"resources")};
function Fc(a,b,c){return b.mutate&&!b.measure?a.getResources().mutateElement(a.iframe,function(){b.mutate(c)}):new Promise(function(d){a.getVsync().measure(function(){b.measure(c);if(!b.mutate)return d();Fc(a,{mutate:b.mutate},c).then(d)})})}
h.enterFullOverlayMode=function(){var a=this,b=this.getBodyElement(),c=this.getFixedContainer();return Fc(this,{measure:function(b){var c=a.iframe.getBoundingClientRect(),d=a.win.innerWidth,g=a.win.innerHeight;b.fixedContainerStyle={position:"absolute",top:c.top+"px",right:d-c.right+"px",left:c.left+"px",bottom:g-c.bottom+"px",width:c.width+"px",height:c.height+"px"}},mutate:function(d){S(b,"background","transparent");U(a.iframe,{position:"fixed",left:0,right:0,top:0,bottom:0,width:"100vw",height:"100vh"});
U(c,d.fixedContainerStyle)}},{})};h.leaveFullOverlayMode=function(){var a=this,b=this.getBodyElement(),c=this.getFixedContainer();return Fc(this,{mutate:function(){Zb(b,["background"]);Zb(a.iframe,"position left right top bottom width height".split(" "));Zb(c,"position top right left bottom width height".split(" "))}})};
h.getFixedContainer=function(){var a;a=this.getBodyElement();if(null==Xa)try{a.ownerDocument.querySelector(":scope"),Xa=!0}catch(c){Xa=!1}if(Xa)a=a.querySelector(":scope > amp-ad-banner");else{a.classList.add("i-amphtml-scoped");var b=a.querySelector(".i-amphtml-scoped > amp-ad-banner");a.classList.remove("i-amphtml-scoped");a=b}return a};
function Ec(a,b,c){return I(a,"resources").getResourcesInRect(b,c).then(function(a){var b=[];a.forEach(function(a){vc.includes(a.element.tagName)||b.push(a.loadedOnce())});return Promise.all(b)})};function Gc(a){var b="nameframe",c=b||"frame";return"https://d-"+Hc(a)+("."+na+"/123456789/")+(c+".html")}function Hc(a){var b;if(a.crypto&&a.crypto.getRandomValues){var c=new Uint32Array(2);a.crypto.getRandomValues(c);b=String(c[0])+c[1]}else b=String(a.Math.random()).substr(2)+"0";return b}function Ic(){for(var a=window,b=0,c=a;c&&c!=c.parent;c=c.parent)b++;return String(b)+"-"+Hc(a)};function Jc(a,b){this.ampdoc=a;this.aa=b}h=Jc.prototype;h.expandSync=function(a,b,c,d){return this.expandUrlSync(a,b,c,d)};h.expandAsync=function(a,b,c){return this.expandUrlAsync(a,b,c)};h.expandStringSync=function(a,b,c,d){return V(this,a,b,c,!0,d)};h.expandStringAsync=function(a,b){return V(this,a,b)};h.expandUrlSync=function(a,b,c,d){return Kc(a,V(this,a,b,c,!0,d))};h.expandUrlAsync=function(a,b,c){return V(this,a,b,void 0,void 0,c).then(function(b){return Kc(a,b)})};
h.expandInputValueAsync=function(a){return Lc(this,a,!1)};h.expandInputValueSync=function(a){return Lc(this,a,!0)};function Lc(a,b,c){"INPUT"==b.tagName&&(b.getAttribute("type")||"").toLowerCase();var d=Mc(b);if(!d)return c?b.value:Promise.resolve(b.value);void 0===b["amp-original-value"]&&(b["amp-original-value"]=b.value);a=V(a,b["amp-original-value"]||b.value,void 0,void 0,c,d);return c?b.value=a:a.then(function(a){return b.value=a})}
function Mc(a,b){if(a=a.getAttribute("data-amp-replace")){var c={};a.trim().split(/\s+/).forEach(function(a){!b||b&&b.hasOwnProperty(a)?c[a]=!0:b&&y().warn("URL","Ignoring unsupported replacement",a)});return c}}
h.maybeExpandLink=function(a){var b={CLIENT_ID:!0,QUERY_PARAM:!0},c=a.getAttribute("data-amp-addparams"),d=Mc(a,b);if(d||c){var e=a["amp-original-href"]||a.getAttribute("href"),f=D(e);null==a["amp-original-href"]&&(a["amp-original-href"]=e);if(c)var g=v(c),e=ua(e,va(g));if(d){a:if(g=cb(this.ampdoc),f.origin==D(g.canonicalUrl).origin||f.origin==D(g.sourceUrl).origin)f=!0;else{if((g=this.ampdoc.getRootNode().querySelector("meta[name=amp-link-variable-allowed-origin]"))&&g.hasAttribute("content"))for(var g=
g.getAttribute("content").trim().split(/\s+/),k=0;k<g.length;k++)if(f.origin==D(g[k]).origin){f=!0;break a}f=!1}var l=f;l?e=this.expandSync(e,void 0,void 0,d):y().warn("URL","Ignoring link replacement",e," because the link does not go to the document's source, canonical, or whitelisted origin.")}return a.href=e}};
function V(a,b,c,d,e,f){var g=a.aa.getExpr(c),k,l=b.replace(g,function(b,g,r){var m=[];"string"==typeof r&&(m=r.split(","));if(f&&!f[g])return b;var p;if(c&&g in c)p=c[g];else if(p=a.aa.get(g))if(e){if(p=p.sync,!p)return y().error("UrlReplacements","ignoring async replacement key: ",g),""}else p=p.async||p.sync;var n;try{n="function"==typeof p?p.apply(null,m):p}catch(F){e&&(n=""),ja(F)}if(n&&n.then){if(e)return y().error("UrlReplacements","ignoring promise value for key: ",g),"";var E=n.catch(function(a){ja(a)}).then(function(a){l=
l.replace(b,null==a?"":encodeURIComponent(a));d&&(d[b]=a)});k=k?k.then(function(){return E}):E;return b}d&&(d[b]=n);return null==n?"":encodeURIComponent(n)});k&&(k=k.then(function(){return l}));return e?l:k||Promise.resolve(l)}h.collectVars=function(a,b){var c=Object.create(null);return V(this,a,b,c).then(function(){return c})};
function Kc(a,b){var c=D(b,!0).protocol,d=D(a,!0).protocol;if(c!=d)return y().error("UrlReplacements","Illegal replacement of the protocol: ",a),a;y().assert(ya(b),"The replacement url has invalid protocol: %s",b);return b}h.getVariableSource=function(){return this.aa};var ga={CLIENT_CACHE:"client_cache",SAFEFRAME:"safeframe",NAMEFRAME:"nameframe"},Nc={frameborder:"0",allowfullscreen:"",allowtransparency:"",scrolling:"no",marginwidth:"0",marginheight:"0"},Oc={adSlotCleared:"-1",urlBuilt:"1",adRequestStart:"2",adRequestEnd:"3",extractCreativeAndSignature:"4",adResponseValidateStart:"5",renderFriendlyStart:"6",renderCrossDomainStart:"7",renderFriendlyEnd:"8",renderCrossDomainEnd:"9",preAdThrottle:"10",renderSafeFrameStart:"11",throttled3p:"12",adResponseValidateEnd:"13",
xDomIframeLoaded:"14",friendlyIframeLoaded:"15",adSlotCollapsed:"16",adSlotUnhidden:"17",layoutAdPromiseDelay:"18",signatureVerifySuccess:"19",networkError:"20",friendlyIframeIniLoad:"21",visHalf:"22",visHalfIniLoad:"23",firstVisible:"24",visLoadAndOneSec:"25",iniLoad:"26",resumeCallback:"27",visIniLoad:"29"};function Pc(a,b,c){return function(d){for(var e=[],f=0;f<arguments.length;++f)e[f-0]=arguments[f];try{return a.apply(b,e)}catch(g){if(c)try{return e.unshift(g),c.apply(b,e)}catch(k){}}}}
function W(a){var b=this;AMP.BaseElement.call(this,a);this.C=null;this.T=0;this.j=this.uiHandler=this.m=this.l=this.config=null;this.pa=this.getVsync();this.Y=!1;this.U=new nc(this.win);this.H=null;this.F={width:this.element.getAttribute("width"),height:this.element.getAttribute("height")};this.A=null;this.G=K(this.win,"platform").isIos()?"safeframe":null;this.P=this.win.performance&&this.win.performance.now?this.win.performance.now.bind(this.win.performance):Date.now;this.b=Pc(this.emitLifecycleEvent,
this,function(a,d){z().error("amp-a4a",b.element.getAttribute("type"),"Error on emitLifecycleEvent",a,d)});this.sentinel=Ic();this.X=!1;this.iframe=null;this.fromResumeCallback=!1;a=(this.element.getAttribute("type")||"notype").toLowerCase();this.ca="adsense"==a&&R(this.element,"117152655")||"doubleclick"==a&&R(this.element,"117152665");this.$="1-0-9"}q(W,AMP.BaseElement);h=W.prototype;h.getPriority=function(){return 2};
h.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a};h.buildCallback=function(){this.uiHandler=new AMP.AmpAdUIHandler(this);if(!this.win.ampA4aValidationKeys){var a=Qc(this);this.win.ampA4aValidationKeys=a}};
h.renderOutsideViewport=function(){if(!this.Y&&this.win["3pla"])return this.b("throttled3p"),!1;var a;var b=this.element.getAttribute("data-loading-strategy");null==b?a=null:"prefer-viewability-over-views"==b||""==b?a=1.25:(a="Value of data-loading-strategy should be a float number in range of [0, 3], but got "+b,b=y().assertNumber(parseFloat(b),a),y().assert(0<=b&&3>=b,a),a=b);var c=a;return null!==c?c:AMP.BaseElement.prototype.renderOutsideViewport.call(this)};h.isValidElement=function(){return!0};
h.getPreconnectUrls=function(){return[]};h.getPrefetchUrls=function(){return[]};h.isAmpAdElement=function(){return"AMP-AD"==this.element.tagName||"AMP-EMBED"==this.element.tagName};h.preconnectCallback=function(){var a=this;this.preconnect.preload(Rc(this));this.preconnect.preload(Gc(this.win));var b=this.getPreconnectUrls();b&&b.forEach(function(b){a.preconnect.url(b,!0)})};
h.resumeCallback=function(){if(!this.m){this.b("resumeCallback");this.fromResumeCallback=!0;var a=this.getResource();if(a.hasBeenMeasured()&&!a.isMeasureRequested())this.onLayoutMeasure()}};h.getResource=function(){return this.element.getResources().getResourceForElement(this.element)};h.hasAdPromise=function(){return!!this.C};
function Sc(a){if(!a.U.isAvailable())return!1;var b=a.getIntersectionElementLayoutBox();if(0==b.height||0==b.width)return!1;var b=a.win,c=!1,d=0,e=a.element;do{if(dc[e.tagName])d++,c=!1;else{var f=(b.getComputedStyle(e)||B()).position;"fixed"!=f&&"sticky"!=f||(c=!0)}e=e.parentElement}while(e&&"BODY"!=e.tagName);return!c&&1>=d?a.isValidElement()?!0:(y().warn("amp-a4a",a.element.getAttribute("type"),"Amp ad element ignored as invalid",a.element),!1):(y().warn("amp-a4a","<"+a.element.tagName+"> is not allowed to be "+
("placed in elements with position:fixed: "+a.element)),!1)}
h.onLayoutMeasure=function(){var a=this;if(this.j)this.j.onLayoutMeasure();if(!this.C&&Sc(this)){++this.T;var b=this.verifyStillCurrent();this.C=Q(this.getAmpDoc()).whenFirstVisible().then(function(){b();if(a.ca&&!a.getResource().renderOutsideViewport())return a.getResource().whenWithinRenderOutsideViewport()}).then(function(){b();a.ca&&z().info("amp-a4a","ad request being built");return a.getAdUrl()}).then(function(c){b();a.l=c;a.b("urlBuilt");return c&&a.sendXhrRequest(c)}).then(function(c){b();
a.b("adRequestEnd");if(!c)return null;if(!c.arrayBuffer||204==c.status)return a.forceCollapse(),Promise.reject("NO-CONTENT-RESPONSE");var d=c.headers.get("X-AmpAdRender")||a.G;(a.G=d)&&!fa(d)&&z().error("AMP-A4A","cross-origin render mode header "+d);var e=c.headers.get("X-AmpSafeFrameVersion");/^[0-9-]+$/.test(e)&&"1-0-9"!=e&&(a.$=e,a.preconnect.preload(Rc(a)));return c.arrayBuffer().then(function(b){return 0==b.byteLength?(a.forceCollapse(),Promise.reject("NO-CONTENT-RESPONSE")):{bytes:b,headers:c.headers}})}).then(function(c){b();
c&&a.b("extractCreativeAndSignature");return c&&a.extractCreativeAndSignature(c.bytes,c.headers)}).then(function(c){b();if(!c)return Promise.resolve();a.F=c.size||a.F;"client_cache"!=a.G&&c.creative&&(a.H=c.creative);if(!c.signature)return Promise.resolve();a.b("adResponseValidateStart");return Tc(a,c.creative,c.signature).then(function(b){if(b)return b;y().error("amp-a4a",a.element.getAttribute("type"),"Unable to validate AMP creative against key providers");a.win.ampA4aValidationKeys=Qc(a);return Tc(a,
c.creative,c.signature)})}).then(function(c){b();a.Y=!!c;return c&&la(c)}).then(function(c){b();var d;if(!c||!(d=Uc(a,c)))return null;a.updatePriority(0);var e=P(a.win);d.customElementExtensions.forEach(function(a){return e.loadExtension(a)});return d}).catch(function(b){if("NO-CONTENT-RESPONSE"==b)return{minifiedCreative:"",customElementExtensions:[],customStylesheets:[]};Vc(a,b);return null})}};
function Tc(a,b,c){var d=a.win.ampA4aValidationKeys,e=!1;return ec(d.map(function(d){return d.then(function(d){return e?Promise.reject("noop"):ec(d.keys.map(function(d){return d.then(function(d){if(e)return Promise.reject("noop");if(!d)return Promise.reject("Promise resolved to null key.");var f=a.P();return a.U.verifySignature(new Uint8Array(b),c,d).then(function(g){if(g)return e=!0,a.b("signatureVerifySuccess",{"met.delta.AD_SLOT_ID":Math.round(a.P()-f),"signingServiceName.AD_SLOT_ID":d.serviceName}),
b;d&&5<c.length&&0==c[0]&&pc(c,d.hash)&&y().error("amp-a4a",a.element.getAttribute("type"),"Key failed to validate creative's signature",d.serviceName,d.cryptoKey);return Promise.reject(d.serviceName+" key failed to verify")},function(b){z().error("amp-a4a",a.element.getAttribute("type"),d.serviceName,b,a.element)})})})).then(function(a){return a[0]},function(){return Promise.reject("All keys for "+d.serviceName+" failed to verify")})})})).then(function(b){a.b("adResponseValidateEnd");return b[0]},
function(){a.b("adResponseValidateEnd");return Promise.reject("No validation service could verify this key")})}
function Vc(a,b,c){var d=b;if(d&&("string"==typeof d?t(d,"CANCELLED"):"string"==typeof d.message&&t(d.message,"CANCELLED")))throw b;b=b&&b.message?ha(b):Error("unknown error "+b);c&&(b.ignoreStack=c);d=a.element.getAttribute("type")||"notype";0!=b.message.indexOf("amp-a4a: "+d+":")&&(b.message="amp-a4a: "+d+": "+b.message);d=b;a=a.l;if(!(!a||d.args&&d.args.au)){var e=a.indexOf("?");-1!=e&&((d.args||(d.args={})).au=a.substring(e+1,e+251))}w().development||w().log?y().error("amp-a4a",b):(y().warn("amp-a4a",
b),.01>Math.random()&&z().expectedError("amp-a4a",b))}
h.layoutCallback=function(){var a=this;if(!this.C)return Sc(this)&&z().error("amp-a4a","Null promise in layoutCallback"),Promise.resolve();this.b("preAdThrottle");var b=this.P(),c=this.verifyStillCurrent();return this.C.then(function(d){c();var e=a.P()-b;a.b("layoutAdPromiseDelay",{layoutAdPromiseDelay:Math.round(e),isAmpCreative:!!d});return a.X?Promise.resolve():a.iframe?(a.b("iframeAlreadyExists"),Promise.resolve()):d?Wc(a,d).catch(function(b){c();y().error("amp-a4a",a.element.getAttribute("type"),
"Error injecting creative in friendly frame",b);Vc(a,b);return Xc(a)}):Xc(a)}).catch(function(b){Vc(a,b);throw Error("CANCELLED");})};h.attemptChangeSize=function(a,b){this.A=this.A||this.getLayoutBox();return AMP.BaseElement.prototype.attemptChangeSize.call(this,a,b).catch(function(){})};
h.unlayoutCallback=function(){var a=this;if(this.m)return!1;this.T++;this.b("adSlotCleared");this.uiHandler.applyUnlayoutUI();this.A&&AMP.BaseElement.prototype.attemptChangeSize.call(this,this.A.height,this.A.width).then(function(){a.A=null}).catch(function(a){z().warn("amp-a4a","unable to revert to original size",a)});this.X=!1;this.m&&(this.m.destroy(),this.m=null);this.iframe&&this.iframe.parentElement&&(this.iframe.parentElement.removeChild(this.iframe),this.iframe=null);this.H=this.l=this.C=
null;this.fromResumeCallback=this.Y=!1;this.G=K(this.win,"platform").isIos()?"safeframe":null;this.j&&(this.j.freeXOriginIframe(),this.j=null);return!0};h.viewportCallback=function(a){this.m&&yc(this.m,a);this.j&&this.j.viewportCallback(a)};h.createPlaceholderCallback=function(){return this.uiHandler.createPlaceholder()};h.getAdUrl=function(){throw Error("getAdUrl not implemented!");};h.resetAdUrl=function(){this.l=null};
h.verifyStillCurrent=function(){var a=this,b=this.T;return function(){if(b!=a.T)throw Error("CANCELLED");}};h.extractCreativeAndSignature=function(){throw Error("extractCreativeAndSignature not implemented!");};h.forceCollapse=function(){this.A=this.A||this.getLayoutBox();this.uiHandler.applyNoContentUI();this.X=!0};h.onCreativeRender=function(a){a&&this.b("renderFriendlyEnd")};
h.onCrossDomainIframeCreated=function(a){z().info("amp-a4a",this.element.getAttribute("type"),"onCrossDomainIframeCreated "+a)};h.sendXhrRequest=function(a){var b=this;this.b("adRequestStart");var c={mode:"cors",method:"GET",credentials:"include"};return K(this.win,"xhr").fetch(a,c).catch(function(){b.b("networkError");return null})};h.getSigningServiceNames=function(){return["google"]};
function Qc(a){return a.U.isAvailable()?a.getSigningServiceNames().map(function(b){aa(b,"-dev");var c=Nb[b],d=b;if(c)return Q(a.getAmpDoc()).whenFirstVisible().then(function(){return K(a.win,"xhr").fetchJson(c,{mode:"cors",method:"GET",ampCors:!1,credentials:"omit"}).then(function(a){return a.json()}).then(function(b){var c={serviceName:d};ea(b)&&Array.isArray(b.keys)&&b.keys.every(ea)?c.keys=b.keys:(y().error("amp-a4a",a.element.getAttribute("type"),"Invalid response from signing server "+d,a.element),
c.keys=[]);return c})}).then(function(b){return{serviceName:b.serviceName,keys:b.keys.map(function(c){return a.U.importPublicKey(b.serviceName,c).catch(function(c){y().error("amp-a4a",a.element.getAttribute("type"),"error importing keys for: "+b.serviceName,c,a.element);return null})})}}).catch(function(b){y().error("amp-a4a",a.element.getAttribute("type"),b,a.element);return{serviceName:d,keys:[]}});b="Signing service '"+b+"' does not exist.";y().error("amp-a4a",a.element.getAttribute("type"),b,
a.element);return Promise.resolve({serviceName:d,keys:[]})}):[]}
function Xc(a){if("true"==a.element.getAttribute("disable3pfallback"))return y().warn("amp-a4a",a.element.getAttribute("type"),"fallback to 3p disabled"),Promise.resolve(!1);Vc(a,Error("fallback to 3p"),!0);var b=a.G,c=Promise.resolve(!1);if("safeframe"!=b&&"nameframe"!=b||!a.H)if(a.l){var b=a.l,d=a.element,e;e=void 0===e?"source":e;y().assert(null!=b,"%s %s must be available",d,e);y().assert(wa(b)||/^(\/\/)/.test(b),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',d,
e,b);e=a.l;a.b("renderCrossDomainStart");c=Yc(a,{src:K(a.win,"xhr").getCorsUrl(a.win,e),name:JSON.stringify(mc(a.win,a.element,a.sentinel))})}else y().warn("amp-a4a",a.element.getAttribute("type"),"No creative or URL available -- A4A can't render any ad");else c=Zc(a,a.H),a.H=null;qc(a.win,c);return c}
function Wc(a,b){a.b("renderFriendlyStart");a.iframe=Ua(a.element.ownerDocument,"iframe",{height:a.F.height,width:a.F.width,frameborder:"0",allowfullscreen:"",allowtransparency:"",scrolling:"no"});a.applyFillContent(a.iframe);var c=[];b.customStylesheets&&b.customStylesheets.forEach(function(a){(a=a.href)&&c.push(a)});var d=a.verifyStillCurrent();return zc(a.iframe,a.element,{host:a.element,url:a.l,html:b.minifiedCreative,extensionIds:b.customElementExtensions||[],fonts:c},function(b){var c=a.getAmpDoc(),
d=new lc(a.getAmpDoc(),b);Fa(b,new Jc(c,d))}).then(function(b){d();a.m=b;xc(b,a.isInViewport());var c=b.iframe.contentDocument||b.win.document;S(c.body,"visibility","visible");rc(a.getAmpDoc(),b.win);$c(a,b.win);fc(b.win,"navigationStart","loadEventEnd").then(function(b){d();a.b("friendlyIframeLoaded",{"navStartToLoadEndDelta.AD_SLOT_ID":Math.round(b)})}).catch(function(b){z().error("amp-a4a",a.element.getAttribute("type"),"getTimingDataAsync for renderFriendlyEnd failed: ",b)});Pc(a.onCreativeRender,
a,function(b){z().error("amp-a4a",a.element.getAttribute("type"),"Error executing onCreativeRender",b)})(!0);return b.whenIniLoaded()}).then(function(){d();a.b("friendlyIframeIniLoad")})}
function Yc(a,b){var c=Object.assign(b,{height:a.F.height,width:a.F.width});a.sentinel&&(c["data-amp-3p-sentinel"]=a.sentinel);a.iframe=Ua(a.element.ownerDocument,"iframe",Object.assign(c,Nc));a.j=new AMP.AmpAdXOriginIframeHandler(a);var d=a.j.init(a.iframe,!0);Pc(a.onCreativeRender,a,function(b){z().error("amp-a4a",a.element.getAttribute("type"),"Error executing onCreativeRender",b)})(!1);return d}
function Zc(a,b){var c=a.G;a.b("renderSafeFrameStart");var d=a.verifyStillCurrent();return la(b).then(function(b){d();var e,g="";switch(c){case "safeframe":e=Rc(a)+"?n=0";break;case "nameframe":e=Gc(a.win);break;default:return y().error("A4A","A4A received unrecognized cross-domain name attribute iframe rendering mode request: %s.  Unable to render a creative for slot %s.",c,a.element.getAttribute("id")),Promise.reject("Unrecognized rendering mode request")}var k=mc(a.win,a.element,a.sentinel);"nameframe"==
c?(k.creative=b,g=JSON.stringify(k)):"safeframe"==c&&(k=JSON.stringify(k),g=a.$+";"+b.length+";"+b+(""+k));return Yc(a,{src:e,name:g})})}
function Uc(a,b){var c='<script type="application/json" amp-ad-metadata>',d=b.lastIndexOf('<script type="application/json" amp-ad-metadata>');0>d&&(c="<script type=application/json amp-ad-metadata>",d=b.lastIndexOf("<script type=application/json amp-ad-metadata>"));if(0>d)return z().warn("amp-a4a",a.element.getAttribute("type"),"Could not locate start index for amp meta data in: %s",b),null;var e=b.lastIndexOf("\x3c/script>");if(0>e)return z().warn("amp-a4a",a.element.getAttribute("type"),"Could not locate closing script tag for amp meta data in: %s",
b),null;try{var f=JSON.parse(b.slice(d+c.length,e)),g=f.ampRuntimeUtf16CharOffsets;if(!Array.isArray(g)||2!=g.length||"number"!==typeof g[0]||"number"!==typeof g[1])throw Error("Invalid runtime offsets");var k={};if(f.customElementExtensions){if(k.customElementExtensions=f.customElementExtensions,!Array.isArray(k.customElementExtensions))throw Error("Invalid extensions",k.customElementExtensions);}else k.customElementExtensions=[];if(f.customStylesheets){k.customStylesheets=f.customStylesheets;var l=
"Invalid custom stylesheets";if(!Array.isArray(k.customStylesheets))throw Error(l);k.customStylesheets.forEach(function(a){if(!ea(a)||!a.href||"string"!==typeof a.href||!/^https:\/\//i.test(a.href))throw Error(l);})}k.minifiedCreative=b.slice(0,g[0])+b.slice(g[1],d)+b.slice(e+9);return k}catch(m){return z().warn("amp-a4a",a.element.getAttribute("type"),"Invalid amp metadata: %s",b.slice(d+48,e)),null}}
function $c(a,b){O(a.win,"alp-for-a4a")&&b.document.documentElement.addEventListener("click",function(b){Ob(b,function(b){Q(a.getAmpDoc()).navigateTo(b,"a4a")})})}function Rc(a){return"https://tpc.googlesyndication.com/safeframe/"+(a.$+"/html/container.html")}h.collapsedCallback=function(){this.b("adSlotCollapsed")};h.emitLifecycleEvent=function(){};function ad(a){var b=!0;if(b=void 0===b?!1:b){var c=Ha(a);P(c.win).loadExtension("amp-analytics")}return ab(a)}function bd(a,b){var c=!0,c=void 0===c?!1:c,d=a.ownerDocument,e=Ua(d,"amp-analytics",{sandbox:"true",trigger:"immediate"}),f=Ua(d,"script",{type:"application/json"});f.textContent=JSON.stringify(b);e.appendChild(f);e.CONFIG=b;c?P(a.ownerDocument.defaultView).loadExtension("amp-analytics"):bb(a,"amp-analytics-instrumentation").then(function(){});a.appendChild(e);return e};function cd(){this.O=Object(null)}h=cd.prototype;h.addPingsForVisibility=function(){};h.sendPing=function(){};h.setPingParameter=function(a,b){null!=a&&""!==a&&null!==b&&void 0!==b&&""!==b&&(this.O[a]=String(b))};h.setPingParameters=function(a){for(var b in a)a.hasOwnProperty(b)&&this.setPingParameter(b,a[b])};h.reset=function(){this.O=Object(null)};h.getInitTime=function(){};h.getDeltaTime=function(){};
function Z(a,b,c,d){var e=this;this.O=Object(null);this.L=a;this.na=b;this.da=c;this.fa=d;this.ha=qb(a);this.oa=this.da+"."+this.fa;var f=gc(a,"navigationStart")||Date.now();this.R="number"==typeof f?f:Number(f);this.getDeltaTime=a.performance&&a.performance.now.bind(a.performance)||function(){return Date.now()-e.R};this.ea="https://csi.gstatic.com/csi";this.la=Da(b);this.ba=Q(b)}q(Z,cd);Z.prototype.setPingAddress=function(a){this.ea=a};
Z.prototype.sendPing=function(a){var b=Oc[a]||9999,c=Math.round(this.getDeltaTime()),d=va(this.O);""!=d&&(d=this.la.expandStringSync(d,{AD_SLOT_NAMESPACE:this.da,AD_SLOT_ID:this.fa,AD_SLOT_TIME_TO_EVENT:c,AD_SLOT_EVENT_NAME:a,AD_SLOT_EVENT_ID:b,AD_PAGE_CORRELATOR:this.ha,AD_PAGE_VISIBLE:this.ba.isVisible()?1:0,AD_PAGE_FIRST_VISIBLE_TIME:Math.round(this.ba.getFirstVisibleTime()-this.R),AD_PAGE_LAST_VISIBLE_TIME:Math.round(this.ba.getLastVisibleTime()-this.R)}));if(a=d?this.ea+"?"+d:"")(new Image).src=
a,z().info("PING",a)};Z.prototype.getInitTime=function(){return this.R};
Z.prototype.addPingsForVisibility=function(a){var b=this;ad(a).then(function(c){var d=a.signals(),e=Promise.race([d.whenSignal("ini-load"),d.whenSignal("load-end")]),f=c.getAnalyticsRoot(a).getVisibilityManager();f.listenElement(a,{visiblePercentageMin:50},null,null,function(){b.sendPing("visHalf")});f.listenElement(a,{visiblePercentageMin:50},e,null,function(){b.sendPing("visHalfIniLoad")});f.listenElement(a,{visiblePercentageMin:1},null,null,function(){b.sendPing("firstVisible")});e.then(function(){b.sendPing("iniLoad")});
f.listenElement(a,{waitFor:"ini-load"},e,null,function(){b.sendPing("visIniLoad")});f.listenElement(a,{visiblePercentageMin:1,waitFor:"ini-load",totalTimeMin:1E3},e,null,function(){b.sendPing("visLoadAndOneSec")})})};var dd={a4aProfilingRate:{isTrafficEligible:function(){return!0},branches:["unused","unused"]}};
function ed(a){var b=Ab(a.element.getAttribute("data-experiment-id")),c={},d=(c[Cb.experiment]=1,c[Fb.experiment]=1,c[Eb.experiment]=1,c[Gb.experiment]=1,c[Hb.experiment]=1,c[Kb.experiment]=1,c[Jb.experiment]=1,c[Lb.experiment]=1,c),c={},e=(c[Cb.control]=1,c[Fb.control]=1,c[Eb.control]=1,c[Gb.control]=1,c[Hb.control]=1,c[Kb.control]=1,c[Jb.control]=1,c[Lb.control]=1,c);return b.some(function(a){return a in d})||R(a.element,"117152632")}
function fd(a,b){var c="X-AmpAdRender",d="rm.AD_SLOT_ID",e="qqid.AD_SLOT_ID",f=Object(null);f[e]=a.get("X-QQID");f[d]=a.get(c);b.setPingParameters(f)};var gd={isTrafficEligible:function(a){return!!a.document.querySelector("AMP-AUTO-ADS")},branches:["3782001","3782002"]};function hd(){this.I=[]}hd.prototype.addNewSlot=function(a,b,c){var d={pv:2,prevFmts:""};this.I.forEach(function(a){d.prevFmts+=(d.prevFmts?",":"")+a.format;a.client==c&&(d.pv=1)});this.I.push({id:b,format:a,client:c});return d};hd.prototype.removeSlot=function(a){this.I=this.I.filter(function(b){return b.id!=a})};hd.prototype.reset=function(){this.I=[]};var id={visible:"1",hidden:"2",prerender:"3",unloaded:"5"},jd=new hd;function kd(a){W.call(this,a);this.o=this.o||this.initLifecycleReporter();this.D=this.V=null;this.ia=P(this.win);this.Z=this.M=this.B=null}q(kd,W);h=kd.prototype;h.isValidElement=function(){return!!this.element.getAttribute("data-ad-client")&&kb(this.win)&&this.isAmpAdElement()};
h.getAdUrl=function(){var a=Date.now(),b=this.win,c=this.element.getAttribute("data-ad-client"),c=c.toLowerCase();"ca-"!=c.substring(0,3)&&(c="ca-"+c);var d=Q(this.getAmpDoc()).getVisibilityState(),e=this.element.getAttribute("data-adtest")||R(this.element,"117152632"),f=Number(this.element.getAttribute("width")),g=Number(this.element.getAttribute("height"));this.B=O(this.win,"as-use-attr-for-format")&&!isNaN(f)&&0<f&&!isNaN(g)&&0<g?{width:f,height:g}:this.getIntersectionElementLayoutBox();var f=
this.B.width+"x"+this.B.height,g=this.element.getAttribute("data-amp-slot-index"),k=this.element,k=(k.getAttribute("data-ad-slot")||"")+":"+f+":"+hb(k),l=gb(k);this.V=g+l;var m=jd.addNewSlot(f,this.V,c),n=this.getViewport().getSize(),g=c,k=this.B.width,r=this.B.height,u=b.SVGElement&&b.document.createElementNS?"1":null,p=this.element.getAttribute("data-ad-host"),x=this.element.getAttribute("data-tag-origin"),E=m.pv,F=this.element.getAttribute("data-ad-channel"),J=id[d]||"0",Ba=b.WebGLRenderingContext?
"1":"0",Ca=this.sentinel,T=(this.win.getComputedStyle(this.element)||B())["font-family"],nb=m.prevFmts||null,N,A=this.win,X,Y,Sb,Tb,Ub;try{N=A.screenX,X=A.screenY}catch(Vb){}try{Y=A.outerWidth,Sb=A.outerHeight}catch(Vb){}try{Tb=n.width,Ub=n.height}catch(Vb){}N=[A.screenLeft,A.screenTop,N,X,A.screen?A.screen.availWidth:void 0,A.screen?A.screen.availTop:void 0,Y,Sb,Tb,Ub].join();N={client:g,format:f,w:k,h:r,adtest:e?"on":null,adk:l,bc:u,ctypes:null,host:p,to:x,pv:E,channel:F,vis:J,wgl:Ba,asnt:Ca,dff:T,
prev_fmts:nb,brdim:N};X=[];Y=this.win;Ra(Y,{"amp-auto-ads-adsense-holdout":gd});var Wb=Y.experimentBranches["amp-auto-ads-adsense-holdout"]||null;Wb&&X.push(Wb);return sb(this,a,N,X)};h.extractCreativeAndSignature=function(a,b){var c=this;fd(b,this.o);this.D=vb(b);this.Z=b.get("X-QQID");this.D&&this.ia.loadExtension("amp-analytics");return tb(a,b).then(function(a){a.size=c.B;return Promise.resolve(a)})};h.emitLifecycleEvent=function(a,b){b&&this.o.setPingParameters(b);this.o.sendPing(a)};
h.initLifecycleReporter=function(){var a=this.element.getAttribute("data-amp-slot-index");Ra(this.win,dd);a=lb(this)&&ed(this)?new Z(this.win,this.element,"a4a",Number(a)):new cd;a.setPingParameters({s:"AD_SLOT_NAMESPACE",dt:"NAV_TIMING(navigationStart)",v:"2",c:"AD_PAGE_CORRELATOR",rls:"AMP_VERSION",v_h:"VIEWPORT_HEIGHT",s_t:"SCROLL_TOP",slotId:"AD_SLOT_ID",stageName:"AD_SLOT_EVENT_NAME",stageIdx:"AD_SLOT_EVENT_ID","met.AD_SLOT_NAMESPACE.AD_SLOT_ID":"AD_SLOT_EVENT_NAME.AD_SLOT_TIME_TO_EVENT","e.AD_SLOT_ID":this.element.getAttribute("data-experiment-id"),
"adt.AD_SLOT_ID":this.element.getAttribute("type"),"met.AD_SLOT_NAMESPACE":"firstVisibleTime.AD_PAGE_FIRST_VISIBLE_TIME,lastVisibleTime.AD_PAGE_LAST_VISIBLE_TIME"});return a};
h.onCreativeRender=function(a){W.prototype.onCreativeRender.call(this,a);if(this.D){if(lb(this)){var b=this.element,c=this.D,d=this.Z,e=this.o.getDeltaTime(),f=this.o.getInitTime(),g=qb(this.win),k=Number(b.getAttribute("data-amp-slot-index")),l=encodeURIComponent(b.getAttribute("data-experiment-id")),b=b.getAttribute("type"),d="https://csi.gstatic.com/csi?s=a4a"+("&c="+g+"&slotId="+k+"&qqid."+k+"="+d)+("&dt="+f)+("null"!=l?"&e."+k+"="+l:"")+("&rls=123456789&adt."+k+"="+b),e=Math.round(e);
a=a?"Friendly":"CrossDomain";c.requests.iniLoadCsi=d+("&met.a4a."+k+"=iniLoadCsi"+a+"."+e);c.requests.renderStartCsi=d+("&met.a4a."+k+"=renderStartCsi"+a+"."+e);c.triggers.continuousVisibleIniLoad.request="iniLoadCsi";c.triggers.continuousVisibleRenderStart.request="renderStartCsi";c.requests.visibilityCsi=d+("&met.a4a."+k+"=visibilityCsi."+e);c.triggers.continuousVisible.request.push("visibilityCsi")}this.M=bd(this.element,this.D)}this.o.addPingsForVisibility(this.element);U(this.iframe,{width:this.B.width+
"px",height:this.B.height+"px"})};h.unlayoutCallback=function(){W.prototype.unlayoutCallback.call(this);this.element.setAttribute("data-amp-slot-index",this.win.ampAdSlotIdCounter++);this.o=this.initLifecycleReporter();this.V&&jd.removeSlot(this.V);if(this.M){var a=this.M;a.parentElement&&a.parentElement.removeChild(a);this.M=null}this.Z=this.D=null};h.getPreconnectUrls=function(){return["https://googleads.g.doubleclick.net"]};AMP.registerElement("amp-ad-network-adsense-impl",kd);
})});
//# sourceMappingURL=amp-ad-network-adsense-impl-0.1.js.map

