(self.AMP=self.AMP||[]).push({n:"amp-access-laterpay",v:"123456789",f:(function(AMP){var g=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function l(a){var b=Object.create(null);if(!a)return b;for(var c;c=g.exec(a);){var d=decodeURIComponent(c[1]).trim(),e=c[2]?decodeURIComponent(c[2]).trim():"";b[d]=e}return b};var m="";
function n(){var a,b=a||self,c;if(b.AMP_MODE)c=b.AMP_MODE;else{c=b;if(c.context&&c.context.mode)c=c.context.mode;else{var d=l(c.location.originalHash||c.location.hash),e=l(c.location.search);m||(m=c.AMP_CONFIG&&c.AMP_CONFIG.v?c.AMP_CONFIG.v:"01123456789");c={localDev:!1,development:!("1"!=d.development&&!c.AMP_DEV_MODE),examiner:"2"==d.development,filter:d.filter,minified:!0,lite:void 0!=e.amp_lite,test:!1,log:d.log,version:"123456789",rtvVersion:m}}c=b.AMP_MODE=c}return c}
;Date.now();self.log=self.log||{user:null,dev:null};var p=self.log;function q(){if(p.user)return p.user;throw Error("failed to call initLogConstructor");};function r(a,b){a=a.__AMP_TOP||a;return t(a,b)}function u(a){a=v(a);a=w(a);return t(a,"viewport")}function v(a){return a.nodeType?r((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function w(a){a=v(a);return a.isSingleDoc()?a.win:a}function t(a,b){var c=x(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}
function y(a){var b=z(a);if(b)return b;var c,d=new Promise(function(a){c=a});x(a).access={obj:null,promise:d,resolve:c,context:null,ctor:null};return d}function z(a){var b=x(a).access;if(b){if(b.promise)return b.promise;t(a,"access");return b.promise=Promise.resolve(b.obj)}return null}function x(a){var b=a.services;b||(b=a.services={});return b};function A(a){return a.ampExtendedElements?!!a.ampExtendedElements["amp-access"]:!1}function B(a){return C(a).then(function(a){return q().assert(a,"Service %s was requested to be provided through %s, but %s is not loaded in the current page. To fix this problem load the JavaScript file for %s in this page.","access","amp-access","amp-access","amp-access")})}
function C(a){var b=v(a),c=z(w(a));return c?c:Promise.resolve().then(function(){return A(b.win)?y(w(a)):b.whenBodyAvailable().then(function(){return A(b.win)?y(w(a)):null})})};function D(a,b){var c="@media (min-width:420px){.amp-access-laterpay{width:420px}}\n.amp-access-laterpay ul{width:100%;margin:0;padding:0;margin-bottom:40px}\n.amp-access-laterpay li{list-style:none;margin-bottom:20px}\n.amp-access-laterpay label,.amp-access-laterpay li{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex}\n.amp-access-laterpay label{padding-right:10px}\n.amp-access-laterpay input{width:20px}\n.amp-access-laterpay-container{padding:16px;padding-right:24px;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-box-align:center;-webkit-align-items:center;-ms-flex-align:center;align-items:center;border-radius:12px;box-shadow:0 0 10px -1px rgba(0,0,0,.25)}\n.amp-access-laterpay-badge{text-align:center;color:#999}\n.amp-access-laterpay-badge a{color:#8db444}\n.amp-access-laterpay-header{font-size:1.2em;margin-bottom:40px}\n.amp-access-laterpay-metadata{width:92%}\n.amp-access-laterpay-title{font-size:1.1em;margin:0;padding:0}\n.amp-access-laterpay-description{font-size:0.9em;margin:0;padding:0}\n.amp-access-laterpay-price-container{margin-top:0;margin-left:auto}\n.amp-access-laterpay-price{font-size:1.5em}\n.amp-access-laterpay-currency{font-size:0.7em}\n.amp-access-laterpay-purchase-button{font-size:1.1em;padding:0.5em 0.8em;background-color:#8db444;border-radius:4px;border:0;color:#fff;width:70%}\n.amp-access-laterpay-already-purchased-link-container{font-size:0.9em}\n/*# sourceURL=/extensions/amp-access-laterpay/0.1/amp-access-laterpay.css*/",
d=!1,e="amp-access-laterpay",f=E(a,a.head,c,d||!1,e||null);if(F(a,f))b(f);else var h=setInterval(function(){F(a,f)&&(clearInterval(h),b(f))},4)}
function E(a,b,c,d,e){if(d&&b.runtimeStyleElement)return b.runtimeStyleElement;if(b.parentElement&&b.parentElement.hasAttribute("i-amphtml-layout")&&(d||e&&"amp-custom"!=e)){var f=d?b.querySelector("style[amp-runtime]"):b.querySelector("style[amp-extension="+e+"]");if(f)return d&&(b.runtimeStyleElement=f),f}a=a.createElement("style");a.textContent=c;var h=null;d?(a.setAttribute("amp-runtime",""),b.runtimeStyleElement=a):"amp-custom"==e?(a.setAttribute("amp-custom",""),h=b.lastChild):(a.setAttribute("amp-extension",
e||""),h=b.runtimeStyleElement);c=b;var k=h;k?k.nextSibling?c.insertBefore(a,k.nextSibling):c.appendChild(a):c.insertBefore(a,c.firstChild);return a}function F(a,b){var c=a.styleSheets;for(a=0;a<c.length;a++){var d=c[a];if(d.ownerNode==b)return!0}return!1};function G(a,b,c){function d(a){try{return h(a)}catch(H){throw self.reportError(H),H;}}var e=void 0,f=a,h=c,k=e||!1;f.addEventListener(b,d,k);return function(){f&&f.removeEventListener(b,d,k);d=f=h=null}};function I(a,b,c){return G(a,b,c)};/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
var M={strictStyling:!1,scopeRules:function(a,b,c){var d="";a&&Array.prototype.forEach.call(a,function(a){if(a.selectorText&&a.style&&void 0!==a.style.cssText)d+=this.scopeSelector(a.selectorText,b,this.strictStyling,c)+" {\n\t",d+=this.propertiesFromRule(a)+"\n}\n\n";else if(a.type===CSSRule.MEDIA_RULE)d+="@media "+a.media.mediaText+" {\n",d+=this.scopeRules(a.cssRules,b),d+="\n}\n\n";else try{a.cssText&&(d+=a.cssText+"\n\n")}catch(f){a.type===CSSRule.KEYFRAMES_RULE&&a.cssRules&&(d+=this.ieSafeCssTextFromKeyFrameRule(a))}},
this);return d},ieSafeCssTextFromKeyFrameRule:function(a){var b="@keyframes "+a.name+" {";Array.prototype.forEach.call(a.cssRules,function(a){b+=" "+a.keyText+" {"+a.style.cssText+"}"});return b+=" }"},scopeSelector:function(a,b,c,d){var e=[],f=a.split(",");f.forEach(function(a){a=a.trim();d&&(a=d(a));this.selectorNeedsScoping(a,b)&&(a=c&&!a.match(J)?this.applyStrictSelectorScope(a,b):this.applySelectorScope(a,b));e.push(a)},this);return e.join(", ")},selectorNeedsScoping:function(a,b){if(Array.isArray(b))return!0;
var c=this.makeScopeMatcher(b);return!a.match(c)},makeScopeMatcher:function(a){a=a.replace(/\[/g,"\\[").replace(/\]/g,"\\]");return new RegExp("^("+a+")"+K,"m")},applySelectorScope:function(a,b){return Array.isArray(b)?this.applySelectorScopeList(a,b):this.applySimpleSelectorScope(a,b)},applySelectorScopeList:function(a,b){for(var c=[],d=0,e;e=b[d];d++)c.push(this.applySimpleSelectorScope(a,e));return c.join(", ")},applySimpleSelectorScope:function(a,b){return a.match(L)?(a=a.replace(J,b),a.replace(L,
b+" ")):b+" "+a},applyStrictSelectorScope:function(a,b){b=b.replace(/\[is=([^\]]*)\]/g,"$1");var c=[" ",">","+","~"],d=a,e="["+b+"]";c.forEach(function(a){d=d.split(a).map(function(a){var b=a.trim().replace(L,"");b&&0>c.indexOf(b)&&0>b.indexOf(e)&&(a=b.replace(/([^:]*)(:*)(.*)/,"$1"+e+"$2$3"));return a}).join(a)});return d},propertiesFromRule:function(a){var b=a.style.cssText;a.style.content&&!a.style.content.match(/['"]+|attr/)&&(b=b.replace(/content:[^;]*;/g,"content: '"+a.style.content+"';"));
a=a.style;for(var c in a)"initial"===a[c]&&(b+=c+": initial; ");return b}},K="([>\\s~+[.,{:][\\s\\S]*)?$",J="-shadowcsshost-no-combinator",L=/-shadowcsshost/gim;var N;function O(a){return!!a&&-1!==a.toString().indexOf("[native code]")};var P=/[^\.\-\_0-9a-zA-Z]/,Q=/[^\-\_0-9a-zA-Z]/;
function aa(a){var b=a.ownerDocument,c;void 0===N&&(O(self.document.registerElement)||O(self.Object.getOwnPropertyDescriptor(self,"customElements").get)?(c=Element,c=c.prototype.attachShadow?"v1":c.prototype.createShadowRoot?"v0":"none"):c="none",N=c);if("none"!=N)c="@media (min-width:420px){.amp-access-laterpay{width:420px}}\n.amp-access-laterpay ul{width:100%;margin:0;padding:0;margin-bottom:40px}\n.amp-access-laterpay li{list-style:none;margin-bottom:20px}\n.amp-access-laterpay label,.amp-access-laterpay li{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex}\n.amp-access-laterpay label{padding-right:10px}\n.amp-access-laterpay input{width:20px}\n.amp-access-laterpay-container{padding:16px;padding-right:24px;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-box-align:center;-webkit-align-items:center;-ms-flex-align:center;align-items:center;border-radius:12px;box-shadow:0 0 10px -1px rgba(0,0,0,.25)}\n.amp-access-laterpay-badge{text-align:center;color:#999}\n.amp-access-laterpay-badge a{color:#8db444}\n.amp-access-laterpay-header{font-size:1.2em;margin-bottom:40px}\n.amp-access-laterpay-metadata{width:92%}\n.amp-access-laterpay-title{font-size:1.1em;margin:0;padding:0}\n.amp-access-laterpay-description{font-size:0.9em;margin:0;padding:0}\n.amp-access-laterpay-price-container{margin-top:0;margin-left:auto}\n.amp-access-laterpay-price{font-size:1.5em}\n.amp-access-laterpay-currency{font-size:0.7em}\n.amp-access-laterpay-purchase-button{font-size:1.1em;padding:0.5em 0.8em;background-color:#8db444;border-radius:4px;border:0;color:#fff;width:70%}\n.amp-access-laterpay-already-purchased-link-container{font-size:0.9em}\n/*# sourceURL=/extensions/amp-access-laterpay/0.1/amp-access-laterpay.css*/";else{c=
a.id;var d=a.ownerDocument,e=null;try{e=R(d.implementation.createHTMLDocument(""))}catch(f){}if(!e)try{e=R(d)}catch(f){}c=e?M.scopeRules.call(M,e,"#"+c,ba):"@media (min-width:420px){.amp-access-laterpay{width:420px}}\n.amp-access-laterpay ul{width:100%;margin:0;padding:0;margin-bottom:40px}\n.amp-access-laterpay li{list-style:none;margin-bottom:20px}\n.amp-access-laterpay label,.amp-access-laterpay li{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex}\n.amp-access-laterpay label{padding-right:10px}\n.amp-access-laterpay input{width:20px}\n.amp-access-laterpay-container{padding:16px;padding-right:24px;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-box-align:center;-webkit-align-items:center;-ms-flex-align:center;align-items:center;border-radius:12px;box-shadow:0 0 10px -1px rgba(0,0,0,.25)}\n.amp-access-laterpay-badge{text-align:center;color:#999}\n.amp-access-laterpay-badge a{color:#8db444}\n.amp-access-laterpay-header{font-size:1.2em;margin-bottom:40px}\n.amp-access-laterpay-metadata{width:92%}\n.amp-access-laterpay-title{font-size:1.1em;margin:0;padding:0}\n.amp-access-laterpay-description{font-size:0.9em;margin:0;padding:0}\n.amp-access-laterpay-price-container{margin-top:0;margin-left:auto}\n.amp-access-laterpay-price{font-size:1.5em}\n.amp-access-laterpay-currency{font-size:0.7em}\n.amp-access-laterpay-purchase-button{font-size:1.1em;padding:0.5em 0.8em;background-color:#8db444;border-radius:4px;border:0;color:#fff;width:70%}\n.amp-access-laterpay-already-purchased-link-container{font-size:0.9em}\n/*# sourceURL=/extensions/amp-access-laterpay/0.1/amp-access-laterpay.css*/"}E(b,
a,c,!1,"amp-access-laterpay")}function ba(a){return a.replace(/(html|body)/g,ca)}function ca(a,b,c,d){var e=d.charAt(c-1),f=d.charAt(c+a.length);return e&&!P.test(e)||f&&!Q.test(f)?a:"amp-"+a}
function R(a){var b=a.createElement("style");b.textContent="@media (min-width:420px){.amp-access-laterpay{width:420px}}\n.amp-access-laterpay ul{width:100%;margin:0;padding:0;margin-bottom:40px}\n.amp-access-laterpay li{list-style:none;margin-bottom:20px}\n.amp-access-laterpay label,.amp-access-laterpay li{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex}\n.amp-access-laterpay label{padding-right:10px}\n.amp-access-laterpay input{width:20px}\n.amp-access-laterpay-container{padding:16px;padding-right:24px;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-box-align:center;-webkit-align-items:center;-ms-flex-align:center;align-items:center;border-radius:12px;box-shadow:0 0 10px -1px rgba(0,0,0,.25)}\n.amp-access-laterpay-badge{text-align:center;color:#999}\n.amp-access-laterpay-badge a{color:#8db444}\n.amp-access-laterpay-header{font-size:1.2em;margin-bottom:40px}\n.amp-access-laterpay-metadata{width:92%}\n.amp-access-laterpay-title{font-size:1.1em;margin:0;padding:0}\n.amp-access-laterpay-description{font-size:0.9em;margin:0;padding:0}\n.amp-access-laterpay-price-container{margin-top:0;margin-left:auto}\n.amp-access-laterpay-price{font-size:1.5em}\n.amp-access-laterpay-currency{font-size:0.7em}\n.amp-access-laterpay-purchase-button{font-size:1.1em;padding:0.5em 0.8em;background-color:#8db444;border-radius:4px;border:0;color:#fff;width:70%}\n.amp-access-laterpay-already-purchased-link-container{font-size:0.9em}\n/*# sourceURL=/extensions/amp-access-laterpay/0.1/amp-access-laterpay.css*/";try{return(a.head||
a.documentElement).appendChild(b),b.sheet?b.sheet.cssRules:null}finally{b.parentNode&&b.parentNode.removeChild(b)}};var da={premiumContentTitle:"Buy only this article",payLaterButton:"Buy Now, Pay Later",payNowButton:"Buy Now",defaultButton:"Buy Now",alreadyPurchasedLink:"I already bought this"};
function S(a){this.ampdoc=a.ampdoc;this.g=a;this.D=u(this.ampdoc);this.a=this.g.getAdapterConfig();this.i=this.j=this.c=null;this.s=[];this.m=!0;this.l=this.h=this.b=null;this.w=this.a.locale||"en";this.f=Object.assign({},da,this.a.localeMessages||{});this.o=(n().development&&this.a.configUrl?this.a.configUrl:n().development&&this.a.sandbox?"https://connector.sandbox.laterpaytest.net":"https://connector.laterpay.net")+"/api/public/amp?article_url=CANONICAL_URL&amp_reader_id=READER_ID&return_url=RETURN_URL";
var b=this.a.articleId;b&&(this.o+="&article_id="+encodeURIComponent(b));this.C=r(this.ampdoc.win,"timer");this.u=r(this.ampdoc.win,"vsync");this.F=r(this.ampdoc.win,"xhr");if(this.ampdoc.isSingleDoc()){var c=this.ampdoc.getRootNode();D(c,function(){})}else c=this.ampdoc.getRootNode(),aa(c)}
S.prototype.authorize=function(){var a=this;return ea(this).then(function(b){if(204===b.status)throw q().createError("No merchant domains have been matched for this article, or no paid content configurations are setup.");a.a.scrollToTopAfterAuth&&a.u.mutate(function(){return a.D.setScrollTop(0)});T(a);return{access:b.access}},function(b){if(!b||!b.response)throw b;var c=b.response;if(402!==c.status)throw b;return c.json().catch(function(){}).then(function(b){a.c=b;T(a).then(a.B.bind(a));return{access:!1}})})};
function ea(a){var b=a.o+"&article_title="+encodeURIComponent(U(a)),c=a.g.buildUrl(b,!1);return c.then(function(b){return a.g.getLoginUrl(b)}).then(function(b){var c;if(p.dev)c=p.dev;else throw Error("failed to call initLogConstructor");c.info("amp-access-laterpay","Authorization URL: ",b);return a.C.timeoutPromise(3E3,a.F.fetchJson(b,{credentials:"include"})).then(function(a){return a.json()})})}function V(a,b){return a.ampdoc.win.document.createElement(b)}
function U(a){var b=a.ampdoc.getRootNode().querySelector(a.a.articleTitleSelector);q().assert(b,"No article title element found with selector %s",a.a.articleTitleSelector);return b.textContent.trim()}function W(a){var b=a.ampdoc.getElementById("amp-access-laterpay-dialog");return q().assert(b,"No element found with id %s","amp-access-laterpay-dialog")}
function T(a){if(a.m)return Promise.resolve();for(var b;b=a.s.shift();)b();a.j&&(a.j(),a.j=null);a.i&&(a.i(),a.i=null);return a.u.mutatePromise(function(){a.m=!0;a.b=null;for(var b=W(a);b.firstChild;)b.removeChild(b.firstChild)})}
S.prototype.B=function(){var a=this,b=W(this);this.b=V(this,"div");this.b.className="amp-access-laterpay-container";X(this,"header");var c=V(this,"ul");this.c.premiumcontent.tp_title=this.f.premiumContentTitle;this.c.premiumcontent.description=U(this);c.appendChild(Y(this,this.c.premiumcontent));this.c.timepasses.forEach(function(b){c.appendChild(Y(a,b))});this.c.subscriptions.forEach(function(b){c.appendChild(Y(a,b))});var d=V(this,"button");d.className="amp-access-laterpay-purchase-button";d.textContent=
this.f.defaultButton;d.disabled=!0;this.l=d;this.j=I(d,"click",function(b){Z(a,b,a.h.value)});this.b.appendChild(c);this.b.appendChild(d);this.b.appendChild(fa(this,this.c.apl));X(this,"footer");b.appendChild(this.b);b.appendChild(ga(this));this.m=!1};function X(a,b){if(a.f[b]){var c=V(a,"p");c.className="amp-access-laterpay-"+b;c.textContent=a.f[b];a.b.appendChild(c)}}
function ga(a){var b=V(a,"a");b.href="https://laterpay.net";b.target="_blank";b.textContent="LaterPay";a=V(a,"p");a.className="amp-access-laterpay-badge";a.textContent="Powered by ";a.appendChild(b);return a}
function Y(a,b){var c=V(a,"li"),d=V(a,"label");d.for=b.tp_title;d.appendChild(ha(a,b));var e=V(a,"div");e.className="amp-access-laterpay-metadata";var f=V(a,"span");f.className="amp-access-laterpay-title";f.textContent=b.tp_title;e.appendChild(f);f=V(a,"p");f.className="amp-access-laterpay-description";f.textContent=b.description;e.appendChild(f);d.appendChild(e);c.appendChild(d);c.appendChild(ia(a,b.price));return c}
function ha(a,b){var c=V(a,"input");c.name="purchaseOption";c.type="radio";c.id=b.tp_title;c.value=b.purchase_url;var d="ppu"===b.purchase_type?"payLater":"payNow",e=a.f[d+"Button"];c.setAttribute("data-purchase-action-label",e);c.setAttribute("data-purchase-type",d);a.s.push(I(c,"change",a.A.bind(a)));return c}
function ia(a,b){var c=Object.keys(b)[0],d=(b[c]/100).toLocaleString(a.w,{style:"decimal",minimumFractionDigits:0}),e=V(a,"span");e.className="amp-access-laterpay-price";e.textContent=d;var f=V(a,"sup");f.className="amp-access-laterpay-currency";f.textContent=c;var h=V(a,"p");h.className="amp-access-laterpay-price-container";h.appendChild(e);h.appendChild(f);return h}
function fa(a,b){var c=V(a,"p");c.className="amp-access-laterpay-already-purchased-link-container";var d=V(a,"a");d.href=b;d.textContent=a.f.alreadyPurchasedLink;a.i=I(d,"click",function(c){Z(a,c,b)});c.appendChild(d);return c}
S.prototype.A=function(a){a.preventDefault();var b="amp-access-laterpay-selected",c=this.h,d=a.target.dataset.purchaseActionLabel;c&&c.classList.contains(b)&&c.classList.remove(b);this.h=a.target;this.h.classList.add(b);this.l.disabled&&(this.l.disabled=!1);this.l.textContent=d};function Z(a,b,c){b.preventDefault();a.g.buildUrl(c,!1).then(function(b){a.g.loginWithUrl(b,a.h.dataset.purchaseType)})}S.prototype.pingback=function(){return Promise.resolve()};(function(a){a.registerServiceForDoc("laterpay",function(a){return B(a).then(function(a){var b=new S(a);a.registerVendor("laterpay",b);return b})})})(self.AMP);
})});
//# sourceMappingURL=amp-access-laterpay-0.1.js.map

