(self.AMP=self.AMP||[]).push({n:"amp-kaltura-player",v:"123456789",f:(function(AMP){function f(a,b){function d(){}d.prototype=b.prototype;a.prototype=new d;a.prototype.constructor=a;for(var c in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,c);e&&Object.defineProperty(a,c,e)}else a[c]=b[c]};Date.now();self.log=self.log||{user:null,dev:null};var l=self.log;function m(){var a={method:"pause",value:""},b=Object.create(null);a&&Object.assign(b,a);return b};function n(a,b){var d;if(!b)return a;var c=a.split("#",2),e=c[0].split("?",2),g=e[0]+(e[1]?d?"?"+b+"&"+e[1]:"?"+e[1]+"&"+b:"?"+b);return g+=c[1]?"#"+c[1]:""}function p(a){var b=[],d;for(d in a){var c=a[d];if(null!=c)if(Array.isArray(c))for(var e=0;e<c.length;e++){var g=c[e];b.push(encodeURIComponent(d)+"="+encodeURIComponent(g))}else e=c,b.push(encodeURIComponent(d)+"="+encodeURIComponent(e))}return b.join("&")};function q(a,b){var d,c=b||function(a){return a},e=a.dataset;a=Object.create(null);var g=d?d:/^param(.+)/,h;for(h in e){var k=h.match(g);if(k){var t=k[1][0].toLowerCase()+k[1].substr(1);a[c(t)]=e[h]}}return a};function r(a){AMP.BaseElement.call(this,a);this.b=null;this.c=this.a=""}f(r,AMP.BaseElement);r.prototype.preconnectCallback=function(a){this.preconnect.url("https://cdnapisec.kaltura.com",a)};r.prototype.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a};
r.prototype.buildCallback=function(){var a;if(l.user)a=l.user;else throw Error("failed to call initLogConstructor");this.a=a.assert(this.element.getAttribute("data-partner"),"The data-partner attribute is required for <amp-kaltura-player> %s",this.element);this.c=this.element.getAttribute("data-entryid")||"default"};
r.prototype.layoutCallback=function(){var a=this.element.getAttribute("data-uiconf")||this.element.getAttribute("data-uiconf-id")||"default",b=this.element.ownerDocument.createElement("iframe"),d="https://cdnapisec.kaltura.com/p/"+encodeURIComponent(this.a)+"/sp/"+encodeURIComponent(this.a)+"00/embedIframeJs/uiconf_id/"+encodeURIComponent(a)+"/partner_id/"+encodeURIComponent(this.a)+"?iframeembed=true&playerId=kaltura_player_amp&entry_id="+encodeURIComponent(this.c),c=q(this.element,function(a){return"flashvars["+
a+"]"}),d=n(d,p(c));b.setAttribute("frameborder","0");b.setAttribute("allowfullscreen","true");b.src=d;this.applyFillContent(b);this.element.appendChild(b);this.b=b;return this.loadPromise(b)};
r.prototype.createPlaceholderCallback=function(){var a=this.win.document.createElement("amp-img"),b=this.element.getAttribute("width"),d=this.element.getAttribute("height"),c="https://cdnapisec.kaltura.com/p/"+encodeURIComponent(this.a)+"/thumbnail/entry_id/"+encodeURIComponent(this.c);b&&(c+="/width/"+b);d&&(c+="/height/"+d);a.setAttribute("src",c);a.setAttribute("layout","fill");a.setAttribute("placeholder","");a.setAttribute("referrerpolicy","origin");return a};
r.prototype.pauseCallback=function(){this.b&&this.b.contentWindow&&this.b.contentWindow.postMessage(JSON.stringify(m()),"*")};AMP.registerElement("amp-kaltura-player",r);
})});
//# sourceMappingURL=amp-kaltura-player-0.1.js.map

