(self.AMP=self.AMP||[]).push({n:"amp-list",v:"123456789",f:(function(AMP){function e(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var n=Object.getOwnPropertyDescriptor(b,d);n&&Object.defineProperty(a,d,n)}else a[d]=b[d]};var f=Object.prototype.toString;Date.now();self.log=self.log||{user:null,dev:null};var g=self.log;function k(){if(g.user)return g.user;throw Error("failed to call initLogConstructor");};var l,m;
function p(a){if("string"==typeof a){l||(l=self.document.createElement("a"),m=self.UrlCache||(self.UrlCache=Object.create(null)));var b=m[a];if(b)a=b;else{b=l;b.href=a;b.protocol||(b.href=b.href);var c={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:"0"==b.port?"":b.port,pathname:b.pathname,search:b.search,hash:b.hash,origin:null};"/"!==c.pathname[0]&&(c.pathname="/"+c.pathname);if("http:"==c.protocol&&80==c.port||"https:"==c.protocol&&443==c.port)c.port="",c.host=c.hostname;c.origin=
b.origin&&"null"!=b.origin?b.origin:"data:"!=c.protocol&&c.host?c.protocol+"//"+c.host:c.href;a=m[a]=c}}(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}
function q(a,b){var c;c=void 0===c?"source":c;k().assert(null!=a,"%s %s must be available",b,c);var d=a;k().assert(p(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d);return d};function r(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView;if(b=b!=(b.__AMP_TOP||b)&&t(b,"url-replace")?u(b,"url-replace"):null)return b}b=v(a);b=v(b);b=b.isSingleDoc()?b.win:b;return u(b,"url-replace")}function w(a,b){a=a.__AMP_TOP||a;return u(a,b)}function v(a){return a.nodeType?w((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}
function u(a,b){t(a,b);var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function t(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};function x(a){for(;a.firstChild;)a.removeChild(a.firstChild)};function y(a){var b={bubbles:!0},c={detail:null};Object.assign(c,b);if("function"==typeof a.CustomEvent)return new a.CustomEvent("amp:template-rendered",c);a=a.document.createEvent("CustomEvent");a.initCustomEvent("amp:template-rendered",!!c.bubbles,!!c.cancelable,null);return a};function z(a,b,c){var d=q(b.getAttribute("src"),b);return r(a).expandAsync(d).then(function(c){var d={};b.hasAttribute("credentials")?d.credentials=b.getAttribute("credentials"):d.requireAmpResponseSourceOrigin=!1;return w(a.win,"batched-xhr").fetchJson(c,d)}).then(function(a){return a.json()}).then(function(a){if(null==a)throw Error("Response is undefined.");var b;b=c||".";if("."!=b){b=b.split(".");for(var d=0;d<b.length;d++){var h=b[d];if(!h){a=void 0;break}if("[object Object]"!==f.call(a)||void 0===
a[h]||null==a||"object"!=typeof a||!Object.prototype.hasOwnProperty.call(a,h)){a=void 0;break}a=a[h]}}b=a;return b})};function A(a){AMP.BaseElement.apply(this,arguments)}e(A,AMP.BaseElement);A.prototype.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a};A.prototype.buildCallback=function(){this.a=this.win.document.createElement("div");this.applyFillContent(this.a,!0);this.element.appendChild(this.a);this.a.hasAttribute("role")||this.a.setAttribute("role","list");this.element.hasAttribute("aria-live")||this.element.setAttribute("aria-live","polite")};
A.prototype.reconstructWhenReparented=function(){return!1};A.prototype.layoutCallback=function(){return B(this)};A.prototype.mutatedAttributesCallback=function(a){var b=a.src,c=a.state;if(void 0!=b)B(this);else if(void 0!=c){var d=Array.isArray(c)?c:[c];w(this.win,"templates").findAndRenderTemplateArray(this.element,d).then(this.b.bind(this))}void 0!=b&&void 0!=c&&k().warn("AMP-LIST","[src] and [state] mutated simultaneously.The [state] mutation will be dropped.")};
function B(a){var b=a.element.getAttribute("items")||"items";return C(a,b).then(function(c){k().assert(Array.isArray(c),'Response must contain an array at "%s". %s',b,a.element);return w(a.win,"templates").findAndRenderTemplateArray(a.element,c).then(a.b.bind(a))},function(a){throw k().createError("Error fetching amp-list",a);})}
A.prototype.b=function(a){var b=this;x(this.a);a.forEach(function(a){a.hasAttribute("role")||a.setAttribute("role","listitem");b.a.appendChild(a)});var c=y(this.win);this.a.dispatchEvent(c);this.getVsync().measure(function(){var a=b.a.scrollHeight;a>b.element.offsetHeight&&b.attemptChangeHeight(a).catch(function(){})})};function C(a,b){return z(a.getAmpDoc(),a.element,b)}AMP.registerElement("amp-list",A);
})});
//# sourceMappingURL=amp-list-0.1.js.map

