(self.AMP=self.AMP||[]).push({n:"amp-accordion",v:"123456789",f:(function(AMP){function f(a,c){function d(){}d.prototype=c.prototype;a.prototype=new d;a.prototype.constructor=a;for(var b in c)if(Object.defineProperties){var g=Object.getOwnPropertyDescriptor(c,b);g&&Object.defineProperty(a,b,g)}else a[b]=c[b]};Date.now();self.log=self.log||{user:null,dev:null};var k=self.log;function l(){if(k.user)return k.user;throw Error("failed to call initLogConstructor");};function m(a,c,d){for(var b=a;b&&b!==d;b=b.parentElement)if(c(b))return b;return null};function n(a){AMP.BaseElement.call(this,a);this.b=[];this.a=this.c=null;this.f=!1}f(n,AMP.BaseElement);n.prototype.isLayoutSupported=function(a){return"container"==a};
n.prototype.buildCallback=function(){var a=this;this.f=this.element.hasAttribute("disable-session-states");this.c=p(this);this.a=q(this);var c=this.getRealChildren();c.forEach(function(d,b){l().assert("section"==d.tagName.toLowerCase(),"Sections should be enclosed in a <section> tag, See https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md. Found in: %s",a.element);var c=d.children;l().assert(2==c.length,"Each section must have exactly two children. See https://github.com/ampproject/amphtml/blob/master/extensions/amp-accordion/amp-accordion.md. Found in: %s",
a.element);var h=c[1],e=h.getAttribute("id");e||(e=a.element.id+"_AMP_content_"+b,h.setAttribute("id",e));null!=!a.a[e]&&(a.a[e]?d.setAttribute("expanded",""):!1===a.a[e]&&d.removeAttribute("expanded"),a.mutateElement(function(){}));b=c[0];b.setAttribute("role","heading");b.setAttribute("aria-controls",e);b.setAttribute("aria-expanded",d.hasAttribute("expanded").toString());b.hasAttribute("tabindex")||b.setAttribute("tabindex",0);a.b.push(b);b.addEventListener("click",a.g.bind(a));b.addEventListener("keydown",
a.h.bind(a))})};function p(a){var c=a.element.id||a.element.getResourceId();a=a.win.location.href;var d=a.indexOf("#");a=-1==d?a:a.substring(0,d);return"amp-"+c+"-"+a}function q(a){if(a.f)return Object.create(null);try{var c=a.win.sessionStorage.getItem(a.c);return c?JSON.parse(c):Object.create(null)}catch(d){return Object.create(null)}}function r(a){if(!a.f){var c=JSON.stringify(a.a);try{a.win.sessionStorage.setItem(a.c,c)}catch(d){}}}
function t(a,c){c.preventDefault();var d=c.currentTarget,b=d.parentElement,g=b.children[1].getAttribute("id"),h=b.hasAttribute("expanded");a.mutateElement(function(){b.hasAttribute("expanded")?(b.removeAttribute("expanded"),d.setAttribute("aria-expanded","false")):(b.setAttribute("expanded",""),d.setAttribute("aria-expanded","true"))},b);a.a[g]=!h;r(a)}n.prototype.g=function(a){var c=m(a.target,function(a){return"A"==a.tagName},a.currentTarget);null===c&&t(this,a)};
n.prototype.h=function(a){if(!a.defaultPrevented){var c=a.keyCode;switch(c){case 38:case 40:var d=this.b.indexOf(a.currentTarget);if(-1!==d){a.preventDefault();a=(d+(38==a.keyCode?-1:1))%this.b.length;0>a&&(a+=this.b.length);try{this.b[a].focus()}catch(b){}}break;case 13:case 32:a.target==a.currentTarget&&t(this,a)}}};AMP.registerElement("amp-accordion",n);
})});
//# sourceMappingURL=amp-accordion-0.1.js.map

