(self.AMP=self.AMP||[]).push({n:"amp-live-list",v:"123456789",f:(function(AMP){var g;function k(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,d);f&&Object.defineProperty(a,d,f)}else a[d]=b[d]};Date.now();self.log=self.log||{user:null,dev:null};var m=self.log;function p(){if(m.user)return m.user;throw Error("failed to call initLogConstructor");};function q(a,b){a=a.__AMP_TOP||a;return r(a,b)}function t(a,b){a=u(a);a=v(a);return r(a,b)}function u(a){return a.nodeType?q((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function v(a){a=u(a);return a.isSingleDoc()?a.win:a}function r(a,b){var c=w(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function w(a){var b=a.services;b||(b=a.services={});return b};var x;function y(a,b){b="> ["+b+"]";if(null==x)try{a.ownerDocument.querySelector(":scope"),x=!0}catch(c){x=!1}x?a=a.querySelector(":scope "+b):(a.classList.add("i-amphtml-scoped"),b=a.querySelector(".i-amphtml-scoped "+b),a.classList.remove("i-amphtml-scoped"),a=b);return a};function z(){var a=0;return function(){var b=Math.pow(2,a++),b=b+A(b);return 1E3*b}}function A(a,b){b=b||.3;var c=a*b*Math.random();.5<Math.random()&&(c*=-1);return c};function C(a,b,c){this.win=a;this.N=b;this.I=c;this.u=null;this.l=!1;this.S=this.j=null}function D(a){return a.j?a.j():a.N+A(a.N,.2)}C.prototype.isRunning=function(){return this.l};C.prototype.start=function(a){this.l||(this.l=!0,E(this,a))};C.prototype.stop=function(){this.l&&(this.l=!1,this.u&&(q(this.win,"timer").cancel(this.u),this.u=null))};
function E(a,b){if(a.l){var c=function(){a.S=a.I().then(function(){a.j&&(a.j=null);E(a)}).catch(function(b){if(b.retriable)a.j||(a.j=z()),E(a);else throw b;})};b?c():a.u=q(a.win,"timer").delay(c,D(a))}};function F(a){var b=this;this.ampdoc=a;this.c=Object.create(null);this.H=t(this.ampdoc,"viewer");this.D=15E3;this.J=[this.D];this.o=null;this.V=this.ampdoc.getUrl();this.w=0;this.I=this.P.bind(this);this.ampdoc.whenReady().then(function(){b.D=Math.min.apply(Math,b.J);var a=Object.keys(b.c).map(function(a){return b.c[a].getUpdateTime()});b.w=Math.max.apply(Math,a);b.o=new C(b.ampdoc.win,b.D,b.I);b.H.isVisible()&&G(b)&&b.o.start();H(b)})}g=F.prototype;g.dispose=function(){this.o.stop()};
function G(a){return Object.keys(a.c).some(function(b){return a.c[b].isEnabled()})}g.P=function(){var a=this.V;if(0<this.w){var b=a,a=String(this.w),a=encodeURIComponent("amp_latest_update_time")+"="+encodeURIComponent(a);if(a)var b=b.split("#",2),c=b[0].split("?",2),a=c[0]+(c[1]?"?"+c[1]+"&"+a:"?"+a),a=a+(b[1]?"#"+b[1]:"");else a=b}return q(this.ampdoc.win,"xhr").fetchDocument(a,{requireAmpResponseSourceOrigin:!1}).then(this.R.bind(this))};
g.R=function(a){var b=Array.prototype.slice.call(a.getElementsByTagName("amp-live-list")),c=b.map(this.U.bind(this)),d=Math.max.apply(Math,[0].concat(c));0<d&&(this.w=d);G(this)||this.o.stop()};g.U=function(a){var b=a.getAttribute("id");p().assert(b,"amp-live-list must have an id.");p().assert(b in this.c,"amp-live-list#"+b+" found but did not exist on original page load.");var c=this.c[b];c.toggle(!a.hasAttribute("disabled"));return c.isEnabled()?c.update(a):0};
g.register=function(a,b){var c=!(a in this.c);c&&(this.c[a]=b,this.J.push(b.getInterval()))};function H(a){a.H.onVisibilityChanged(function(){a.H.isVisible()?a.o.start(!0):a.o.stop()})}function I(a){var b=u(a),c=v(b),d=w(c),f=d.liveListManager;f||(f=d.liveListManager={obj:null,promise:null,resolve:null,context:null,ctor:null});f.ctor||f.obj||(f.ctor=F,f.context=b,f.resolve&&r(c,"liveListManager"));r(c,"liveListManager");return t(a,"liveListManager")};function J(a,b){return Math.max(parseInt(a,10)||0,b)}function K(a){AMP.BaseElement.call(this,a);this.B=this.a=this.G=this.K=this.s=null;this.A="";this.i=this.L=this.M=0;this.b=Object.create(null);this.m=[];this.f=[];this.h=[];this.C=null;this.g=0;this.O=this.T.bind(this)}k(K,AMP.BaseElement);g=K.prototype;g.isLayoutSupported=function(a){return"container"==a||"fixed-height"==a};
g.buildCallback=function(){this.s=this.getViewport();this.K=I(this.getAmpDoc());this.G=p().assert(y(this.element,"update"),'amp-live-list must have an "update" slot.');this.a=p().assert(y(this.element,"items"),'amp-live-list must have an "items" slot.');this.B=y(this.element,"pagination");this.A=p().assert(this.element.getAttribute("id"),"amp-live-list must have an id.");this.M=J(this.element.getAttribute("data-poll-interval"),15E3);var a=this.element.getAttribute("data-max-items-per-page");p().assert(0<
Number(a),"amp-live-list#"+this.A+" must have data-max-items-per-page attribute with numeric value. "+("Found "+a));var b=[].slice.call(this.a.children).filter(function(a){return!a.hasAttribute("data-tombstone")}).length;this.L=Math.max(J(a,1),b);this.K.register(this.A,this);L(this,!1);M(this.a,function(a){a.classList.add("amp-live-list-item")});this.g=N(this,this.a,!0);this.registerAction("update",this.F.bind(this),1);this.element.hasAttribute("aria-live")||this.element.setAttribute("aria-live",
"polite")};g.isEnabled=function(){return!this.element.hasAttribute("disabled")};g.toggle=function(a){a?this.element.removeAttribute("disabled"):this.element.setAttribute("disabled","")};g.activate=function(){this.F()};
g.update=function(a){var b=this,c=y(a,"items");if(!c)return this.i;N(this,c);var d=O(this,c);P(this,d.insert);Q(this,d.replace);this.h.push.apply(this.h,d.tombstone);this.C=y(a,"pagination");0<this.m.length?this.deferMutate(function(){L(b,!0);b.s.updateFixedLayer()}):(0<this.f.length||0<this.h.length)&&this.F();return this.i};
g.F=function(){var a=this,b=0<this.m.length,c=0<this.h.length,d=0<this.f.length,f=b||d,e=this.mutateElement(function(){var d=p().assertElement(a.a);b&&(M(d,function(a){a.classList.remove("amp-live-list-item-new")}),a.g+=R(a,a.m),a.m.length=0);0<a.f.length&&(S(d,a.f),a.f.length=0);0<a.h.length&&(a.g-=T(d,a.h),a.h.length=0);(b||c)&&a.B&&a.C&&(a.element.replaceChild(a.C,a.B),a.B=y(a.element,"pagination"));L(a,!1);a.C=null;return U(a,d)});f&&(e=e.then(function(){var b=a.win.document.createEvent("Event");
b.initEvent("amp:dom-update",!0,!0);a.win.document.dispatchEvent(b);var c=a.win,b={detail:null};Object.assign(b,{bubbles:!0});"function"==typeof c.CustomEvent?b=new c.CustomEvent("amp:template-rendered",b):(c=c.document.createEvent("CustomEvent"),c.initCustomEvent("amp:template-rendered",!!b.bubbles,!!b.cancelable,null),b=c);var d=b;a.a.dispatchEvent(d)}));b&&(e=e.then(function(){return a.s.animateScrollIntoView(a.element)}));return e};
function L(a,b){a.G.classList.toggle("amp-hidden",!b);a.G.classList.toggle("amp-active",b)}function R(a,b){var c=0;b.forEach(function(b){if(0==a.a.childElementCount)a.a.appendChild(b);else for(var d=V(b),e=a.a.firstElementChild;e;e=e.nextElementSibling){var h=V(e);if(d>=h){a.a.insertBefore(b,e);c++;break}else e.nextElementSibling||a.a.appendChild(b)}});return c}function S(a,b){var c=0;b.forEach(function(b){var d=b.getAttribute("id"),e=a.querySelector("#"+d);e&&(a.replaceChild(b,e),c++)})}
function T(a,b){var c=0;b.forEach(function(b){b=b.getAttribute("id");if(b=a.querySelector("#"+b))b.setAttribute("data-tombstone",""),b.textContent="",c++});return c}
function U(a,b){var c=a.g-a.L;if(1>c)return Promise.resolve();for(var d=[],f=[],e=b.lastElementChild;e&&!(d.length>=c);e=e.previousElementSibling)e.hasAttribute("data-tombstone")||d.push(e);return a.getVsync().runPromise({measure:function(){for(var b=0;b<d.length;b++){var c=d[b];if(!(a.s.getLayoutRect(c).top>a.s.getScrollTop()+a.s.getSize().height))break;f.push(c)}},mutate:function(){f.forEach(function(c){b.removeChild(c);a.g--})}})}
function P(a,b){b.sort(a.O).forEach(function(a){a.classList.add("amp-live-list-item");a.classList.add("amp-live-list-item-new")});a.m.push.apply(a.m,b)}function Q(a,b){b.forEach(function(b){var c;a:{c=a.f;for(var f=0;f<c.length;f++)if(c[f].getAttribute("id")==b.getAttribute("id")){c=f;break a}c=-1}var e=c;b.classList.add("amp-live-list-item");-1==e?a.f.push(b):a.f[e]=b})}g.getInterval=function(){return this.M};
function O(a,b){var c=[],d=[],f=[];for(b=b.firstElementChild;b;b=b.nextElementSibling){var e=b.getAttribute("id"),h=a,n=b,l=n.getAttribute("id");if(n.hasAttribute("data-tombstone")||l in h.b)if(h=a,l=b,!l.hasAttribute("data-update-time")||l.hasAttribute("data-tombstone")?h=!1:(n=l.getAttribute("id"),l=W(l),h=n in h.b&&-1!=h.b[n]&&l>h.b[n]),h){var B=W(b);a.b[e]=B;e=a.win.document.importNode(b,!0);B>a.i&&(a.i=B);d.push(e)}else b.hasAttribute("data-tombstone")&&-1!=a.b[e]&&(a.b[e]=-1,f.push(b));else e=
a.win.document.importNode(b,!0),c.push(e),X(a,b)}return{insert:c,replace:d,tombstone:f}}function X(a,b){var c=b.getAttribute("id");b=W(b);b>a.i&&(a.i=b);a.b[c]=b}g.W=function(a){delete this.b[a]};
function N(a,b,c){var d=0,f=!1;M(b,function(b){b.hasAttribute("id")&&0<Number(b.getAttribute("data-sort-time"))?c&&X(a,b):f=!0;d++});p().assert(!f,"All amp-live-list-items under amp-live-list#"+a.A+" children must have id and data-sort-time attributes. data-sort-time must be a Number greater than 0.");return d}function M(a,b){for(a=a.firstElementChild;a;a=a.nextElementSibling)b(a)}g.T=function(a,b){return V(a)-V(b)};function V(a){return Y(a,"data-sort-time")}
function W(a){return a.hasAttribute("data-update-time")?Y(a,"data-update-time"):V(a)}function Y(a,b){var c=Number(a.getAttribute(b));p().assert(0<c,'"'+b+'" attribute must exist and value '+("must be a number greater than 0. Found "+c+" on ")+(a.getAttribute("id")+" instead."));return c}g.getUpdateTime=function(){return this.i};(function(a){a.registerElement("amp-live-list",K,"amp-live-list>[update]{position:relative;z-index:1000}amp-live-list>.amp-active[update]{display:block}amp-live-list>[items]>[data-tombstone]{display:none}@-webkit-keyframes amp-live-list-item-highlight{0%{box-shadow:0 0 5px 2px #51cbee}to{box-shadow:0}}@keyframes amp-live-list-item-highlight{0%{box-shadow:0 0 5px 2px #51cbee}to{box-shadow:0}}\n/*# sourceURL=/extensions/amp-live-list/0.1/amp-live-list.css*/")})(self.AMP);
})});
//# sourceMappingURL=amp-live-list-0.1.js.map

