(self.AMP=self.AMP||[]).push({n:"amp-viewer-integration",p:"high",v:"123456789",f:(function(AMP){Date.now();self.log=self.log||{user:null,dev:null};var h=self.log;function k(){if(h.user)return h.user;throw Error("failed to call initLogConstructor");};function l(a){var b=Object.create(null);a&&Object.assign(b,a);return b};var m=self.AMP_CONFIG||{},n=("string"==typeof m.cdnProxyRegex?new RegExp(m.cdnProxyRegex):m.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org/;var p,q,r=/[?&]amp_js[^&]*/;
function t(a){var b;p||(p=self.document.createElement("a"),q=self.UrlCache||(self.UrlCache=Object.create(null)));var c=q[a];if(c)return c;var d=p;d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=d.origin&&
"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;var f=e,g=f;return b?g:q[a]=g}
function u(a){"string"==typeof a&&(a=t(a));var b=a;"string"==typeof b&&(b=t(b));if(!n.test(b.origin))return a.href;var b=a.pathname.split("/"),c=b[1];k().assert("a"==c||"c"==c||"v"==c,"Unknown path prefix in url %s",a.href);var d=b[2],e="s"==d?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(d);k().assert(0<e.indexOf("."),"Expected a . in origin %s",e);b.splice(1,"s"==d?3:2);b=e+b.join("/");c=(c=a.search)&&"?"!=c?(c=c.replace(r,"").replace(/^[?&]/,""))?"?"+c:"":"";return b+c+(a.hash||
"")};function v(a){a=a.__AMP_TOP||a;return w(a,"ampdoc")}function x(a){a=y(a);a=y(a);a=a.isSingleDoc()?a.win:a;return w(a,"viewer")}function y(a){return a.nodeType?v((a.ownerDocument||a).defaultView).getAmpDoc(a):a}function w(a,b){var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};function z(a){return a.parent&&a.parent!=a};function A(a,b,c){function d(a){try{return g(a)}catch(B){throw self.reportError(B),B;}}var e=void 0,f=a,g=c,C=e||!1;f.addEventListener(b,d,C);return function(){f&&f.removeEventListener(b,d,C);d=f=g=null}};function D(a,b){return A(a,"message",b)}function E(a,b){var c=b,d=A(a,"unload",function(a){try{c(a)}finally{c=null,d()}})};function F(a){return v((a.ownerDocument||a).defaultView).getAmpDoc(a)};var G="altKey charCode ctrlKey detail eventPhase keyCode layerX layerY metaKey pageX pageY returnValue shiftKey timeStamp type which".split(" "),H="clientX clientY force identifier pageX pageY radiusX radiusY screenX screenY".split(" ");function I(a,b){this.win=a;this.w=b;this.j=!1;b.registerHandler("scrollLock",this.B.bind(this));this.listenForTouchEvents()}
I.prototype.listenForTouchEvents=function(){var a=this.m.bind(this),b=this.win.document;A(b,"touchstart",a);A(b,"touchend",a);A(b,"touchmove",a)};I.prototype.m=function(a){switch(a.type){case "touchstart":case "touchend":case "touchmove":if(a&&a.type){var b=J(a,G);a.touches&&(b.touches=K(a.touches));a.changedTouches&&(b.changedTouches=K(a.changedTouches));this.w.sendRequest(a.type,b,!1)}this.j&&a.preventDefault()}};function K(a){for(var b=[],c=0;c<a.length;c++)b.push(J(a[c],H));return b}
function J(a,b){for(var c=l(void 0),d=0;d<b.length;d++){var e=b[d];void 0!==a[e]&&(c[e]=a[e])}return c}I.prototype.B=function(a,b,c){this.j=!!b;return c?Promise.resolve({}):void 0};function L(a){if("string"!=typeof a)return a;if("{"!=a.charAt(0))return null;try{return JSON.parse(a)}catch(b){return null}}function M(a,b,c){this.win=a;this.i=b;this.l=c}M.prototype.addEventListener=function(a,b){var c=this;this.win.addEventListener("message",function(a){a.origin==c.i&&a.source==c.l&&"__AMPHTML__"==a.data.app&&b(a)})};M.prototype.postMessage=function(a){this.l.postMessage(a,this.i)};M.prototype.start=function(){};
function N(a,b,c){this.win=a;this.c=b;this.u=!!c;this.A=0;this.f={};this.b={};this.g=null;this.c.addEventListener("message",this.o.bind(this));this.c.start()}N.prototype.registerHandler=function(a,b){this.b[a]=b};N.prototype.unregisterHandler=function(a){delete this.b[a]};N.prototype.setDefaultHandler=function(a){this.g=a};
N.prototype.o=function(a){if(a=L(a.data))if("q"==a.type)O(this,a);else if("s"==a.type){var b=a.requestid,c=this.f[b];c&&(delete this.f[b],a.error?(P(this,"amp-viewer-messaging: handleResponse_ error: ",a.error),c.reject(Error("Request "+a.name+" failed: "+a.error))):c.resolve(a.data))}};N.prototype.sendRequest=function(a,b,c){var d=this,e=++this.A,f=void 0;c&&(f=new Promise(function(a,b){d.f[e]={resolve:a,reject:b}}));Q(this,{app:"__AMPHTML__",requestid:e,type:"q",name:a,data:b,rsvp:c});return f};
function R(a,b,c,d){var e=S(d);P(a,"amp-viewer-messaging: sendResponseError_, Message name: "+c,e);Q(a,{app:"__AMPHTML__",requestid:b,type:"s",name:c,data:null,error:e})}function Q(a,b){a.c.postMessage(a.u?JSON.stringify(b):b)}
function O(a,b){var c=a.b[b.name];c||(c=a.g);if(!c)throw c=Error("Cannot handle request because handshake is not yet confirmed!"),c.args=b.name,c;c=c(b.name,b.data,!!b.rsvp);if(b.rsvp){var d=b.requestid;if(!c)throw R(a,d,b.name,Error("no response")),Error("expected response but none given: "+b.name);c.then(function(c){Q(a,{app:"__AMPHTML__",requestid:d,type:"s",name:b.name,data:c})},function(c){R(a,d,b.name,c)})}}
function P(a,b,c){var d="amp-messaging-error-logger: "+b,e=" data: "+S(c),d=d+e;a.win.viewerState=d}function S(a){return a?a.message?a.message:String(a):"unknown error"};function T(a){this.win=a;this.h=this.a=!1}T.prototype.init=function(){var a=this,b=x(this.win.document);this.a="1"==b.getParam("webview");this.h=b.hasCapability("handshakepoll");var c=b.getParam("origin")||"";if(!this.a&&!c)return Promise.resolve();var d=F(this.win.document);if(this.a||this.h){var e=z(this.win)?this.win.parent:null;return U(this,e,c).then(function(e){return V(a,b,d,c,new N(a.win,e,a.a))})}e=new M(this.win,c,this.win.parent);return V(this,b,d,c,new N(this.win,e,this.a))};
function U(a,b,c){return new Promise(function(d){var e=D(a.win,function(f){var g=L(f.data);if(g&&f.origin===c&&f.source===b&&"__AMPHTML__"==g.app&&"handshake-poll"==g.name){if(a.a&&(!f.ports||!f.ports.length))throw Error("Did not receive communication port from the Viewer!");f=f.ports&&0<f.ports.length?f.ports[0]:new M(a.win,c,a.win.parent);d(f);e()}})})}function V(a,b,c,d,e){var f=c.getUrl(),g=u(f);return e.sendRequest("channelOpen",l({url:f,sourceUrl:g}),!0).then(function(){W(a,e,b,d)})}
function W(a,b,c,d){b.setDefaultHandler(function(a,b,d){return c.receiveMessage(a,b,d)});c.setMessageDeliverer(b.sendRequest.bind(b),d);E(a.win,a.s.bind(a,b));c.hasCapability("swipe")&&new I(a.win,b)}T.prototype.s=function(a){return a.sendRequest("unloaded",l(void 0),!0)};(function(a){(new T(a.win)).init()})(self.AMP);
})});
//# sourceMappingURL=amp-viewer-integration-0.1.js.map

