(self.AMP=self.AMP||[]).push({n:"amp-sidebar",v:"123456789",f:(function(AMP){function h(a,b){function d(){}d.prototype=b.prototype;a.prototype=new d;a.prototype.constructor=a;for(var c in b)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,c);f&&Object.defineProperty(a,c,f)}else a[c]=b[c]};var k=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;Date.now();self.log=self.log||{user:null,dev:null};var l=self.log;var m,n;function p(a){var b=a.indexOf("#");return-1==b?a:a.substring(0,b)};function q(a,b){a=a.__AMP_TOP||a;return r(a,b)}function u(a){a=v(a);a=v(a);a=a.isSingleDoc()?a.win:a;return r(a,"history")}function v(a){return a.nodeType?q((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function r(a,b){var d=a.services;d||(d=a.services={});var c=d;a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};var w=null;Promise.resolve();
function x(a){var b;if(!w){w=Object.create(null);if(a.AMP_CONFIG)for(b in a.AMP_CONFIG){var d=a.AMP_CONFIG[b];"number"===typeof d&&0<=d&&1>=d&&(w[b]=Math.random()<d)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(b=a.AMP_CONFIG["allow-doc-opt-in"],d=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var d=d.getAttribute("content").split(","),c=0;c<d.length;c++)-1!=b.indexOf(d[c])&&(w[d[c]]=!0);Object.assign(w,y(a));
if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){b=a.AMP_CONFIG["allow-url-opt-in"];d=a.location.originalHash||a.location.hash;a=Object.create(null);if(d)for(var f;f=k.exec(d);)c=decodeURIComponent(f[1]).trim(),f=f[2]?decodeURIComponent(f[2]).trim():"",a[c]=f;for(d=0;d<b.length;d++)c=a["e-"+b[d]],"1"==c&&(w[b[d]]=!0),"0"==c&&(w[b[d]]=!1)}}b=w;var g=b;return!!g["amp-sidebar 1.0"]}
function y(a){a:{var b;b:{try{b=a.document.cookie;break b}catch(t){}b=void 0}if(a=b)for(a=a.split(";"),b=0;b<a.length;b++){var d=a[b].trim(),c=d.indexOf("=");if(-1!=c&&"AMP_EXP"==decodeURIComponent(d.substring(0,c).trim())){a=decodeURIComponent(d.substring(c+1).trim());break a}}a=null}var f=a,g=f?f.split(/\s*,\s*/g):[];a=Object.create(null);for(b=0;b<g.length;b++)0!=g[b].length&&("-"==g[b][0]?a[g[b].substr(1)]=!1:a[g[b]]=!0);return a};function z(a,b){for(var d,c=a;c&&c!==d;c=c.parentElement)if(b(c))return c;return null}function A(a){var b="A";if(a.closest)return a.closest(b);b=b.toUpperCase();return z(a,function(a){return a.tagName==b})};var B,C="Webkit webkit Moz moz ms O o".split(" ");function D(a,b){var d=void 0;if(2>b.length?0:0==b.lastIndexOf("--",0))return b;B||(B=Object.create(null));var c=B[b];if(!c||d){c=b;if(void 0===a[b]){var f=b.charAt(0).toUpperCase()+b.slice(1);a:{for(var g=0;g<C.length;g++){var t=C[g]+f;if(void 0!==a[t]){f=t;break a}}f=""}var e=f;void 0!==a[e]&&(c=e)}d||(B[b]=c)}return c}function E(a,b,d){var c;(b=D(a.style,b))&&(a.style[b]=c?d+c:d)}
function F(a,b){if(void 0===b){var d;d=(d=D(a.style,"display"))?a.style[d]:void 0;b="none"==d}E(a,"display",b?"":"none")};function G(a){AMP.BaseElement.call(this,a);this.l=null;this.m=q(this.win,"vsync");this.f=null;this.c=this.win.document;this.s=this.c.documentElement;this.g=null;var b=q(this.win,"platform");this.u=b.isIos()&&b.isSafari();this.h=-1;this.o=!1;this.j=q(this.win,"timer");this.b=null}h(G,AMP.BaseElement);G.prototype.isLayoutSupported=function(a){return"nodisplay"==a};
G.prototype.buildCallback=function(){var a=this,b;if(l.user)b=l.user;else throw Error("failed to call initLogConstructor");b.assert(x(this.win),"Experiment amp-sidebar 1.0 is disabled.");this.g=this.element.getAttribute("side");this.l=this.getViewport();this.l.addToFixedLayer(this.element,!0);if("left"!=this.g&&"right"!=this.g){var d=this.c.body.getAttribute("dir")||this.s.getAttribute("dir")||"ltr";this.g="rtl"==d?"right":"left";this.element.setAttribute("side",this.g)}this.u&&H(this);I(this)?this.i():
this.element.setAttribute("aria-hidden","true");this.element.hasAttribute("role")||this.element.setAttribute("role","menu");this.element.tabIndex=-1;this.s.addEventListener("keydown",function(b){27==b.keyCode&&a.a()});var c=this.c.createElement("button");c.textContent="Close the sidebar";c.classList.add("i-amphtml-screen-reader");c.tabIndex=-1;c.addEventListener("click",function(){a.a()});this.element.appendChild(c);this.registerAction("toggle",this.w.bind(this));this.registerAction("open",this.i.bind(this));
this.registerAction("close",this.a.bind(this));this.element.addEventListener("click",function(b){if((b=A(b.target))&&b.href){var d;d=b.href;m||(m=self.document.createElement("a"),n=self.UrlCache||(self.UrlCache=Object.create(null)));var c=n[d];if(c)d=c;else{c=m;c.href=d;c.protocol||(c.href=c.href);var e={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);
if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=c.origin&&"null"!=c.origin?c.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;d=n[d]=e}var f=d,J=a.getAmpDoc().win.location.href;p(b.href)==p(J)&&f.hash&&a.a()}},!0)};function I(a){return a.element.hasAttribute("open")}G.prototype.activate=function(){this.i()};G.prototype.w=function(){I(this)?this.a():this.i()};
G.prototype.i=function(){var a=this;I(this)||(this.l.enterOverlayMode(),this.m.mutate(function(){F(a.element,!0);K(a);a.u&&L(a);a.element.scrollTop=1;a.m.mutate(function(){a.element.setAttribute("open","");a.element.setAttribute("aria-hidden","false");a.b&&a.j.cancel(a.b);a.b=a.j.delay(function(){var b=a.getRealChildren();a.scheduleLayout(b);a.scheduleResume(b);try{a.element.focus()}catch(d){}},550)})}),u(this.getAmpDoc()).push(this.a.bind(this)).then(function(b){a.h=b}))};
G.prototype.a=function(){var a=this;I(this)&&(this.l.leaveOverlayMode(),this.m.mutate(function(){a.f&&F(a.f,!1);a.element.removeAttribute("open");a.element.setAttribute("aria-hidden","true");a.b&&a.j.cancel(a.b);a.b=a.j.delay(function(){I(a)||a.m.mutate(function(){F(a.element,!1);a.schedulePause(a.getRealChildren())})},550)}),-1!=this.h&&(u(this.getAmpDoc()).pop(this.h),this.h=-1))};
function K(a){if(!a.f){var b=a.c.createElement("div");b.classList.add("i-amphtml-sidebar-mask");b.addEventListener("click",function(){a.a()});a.element.ownerDocument.body.appendChild(b);b.addEventListener("touchmove",function(a){a.preventDefault()});a.f=b}F(a.f,!0)}
function H(a){a.element.addEventListener("scroll",function(b){I(a)&&(1>a.element.scrollTop?(a.element.scrollTop=1,b.preventDefault()):a.element.scrollHeight==a.element.scrollTop+a.element.offsetHeight&&(--a.element.scrollTop,b.preventDefault()))})}function L(a){if(!a.o){var b=a.c.createElement("div"),d={height:"10vh",width:"100%","background-color":"transparent"},c;for(c in d)E(b,c,d[c]);a.element.appendChild(b);a.o=!0}}(function(a){a.registerElement("amp-sidebar",G,"amp-sidebar{position:fixed!important;top:0;max-height:100vh!important;height:100vh;max-width:80vw!important;background-color:#efefef;min-width:45px!important;outline:none;overflow-x:hidden!important;overflow-y:auto!important;z-index:2147483647;-webkit-overflow-scrolling:touch;will-change:transform}amp-sidebar[side=left]{left:0!important;-webkit-transform:translateX(-100%)!important;transform:translateX(-100%)!important}amp-sidebar[side=right]{right:0!important;-webkit-transform:translateX(100%)!important;transform:translateX(100%)!important}amp-sidebar[side][open]{-webkit-transform:translateX(0)!important;transform:translateX(0)!important}amp-sidebar[side]{-webkit-transition:-webkit-transform 233ms cubic-bezier(0,0,.21,1);transition:-webkit-transform 233ms cubic-bezier(0,0,.21,1);transition:transform 233ms cubic-bezier(0,0,.21,1);transition:transform 233ms cubic-bezier(0,0,.21,1),-webkit-transform 233ms cubic-bezier(0,0,.21,1)}.i-amphtml-sidebar-mask{position:fixed!important;top:0!important;left:0!important;width:100vw!important;height:100vh!important;opacity:0.2;background-image:none!important;background-color:#000;z-index:2147483646}\n/*# sourceURL=/extensions/amp-sidebar/1.0/amp-sidebar.css*/")})(self.AMP);
})});
//# sourceMappingURL=amp-sidebar-1.0.js.map

