(self.AMP=self.AMP||[]).push({n:"amp-user-notification",v:"123456789",f:(function(AMP){var k;function l(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};Date.now();function m(a){for(var b=null,c="",d=0;d<arguments.length;d++){var e=arguments[d];if(e instanceof Error&&!b){var b=e,e=b.message,g=String(Math.random());b.message=g;if(b.message===g)b.message=e;else{e=Error(b.message);g=void 0;for(g in b)e[g]=b[g];e.stack=b.stack;b=e}}else c&&(c+=" "),c+=e}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}function n(a){var b=m.apply(null,arguments);setTimeout(function(){self.reportError(b);throw b;})}self.log=self.log||{user:null,dev:null};var p=self.log;
function q(){if(p.user)return p.user;throw Error("failed to call initLogConstructor");};var r,t;
function u(a){if("string"==typeof a){r||(r=self.document.createElement("a"),t=self.UrlCache||(self.UrlCache=Object.create(null)));var b=t[a];if(b)a=b;else{b=r;b.href=a;b.protocol||(b.href=b.href);var c={href:b.href,protocol:b.protocol,host:b.host,hostname:b.hostname,port:"0"==b.port?"":b.port,pathname:b.pathname,search:b.search,hash:b.hash,origin:null};"/"!==c.pathname[0]&&(c.pathname="/"+c.pathname);if("http:"==c.protocol&&80==c.port||"https:"==c.protocol&&443==c.port)c.port="",c.host=c.hostname;c.origin=
b.origin&&"null"!=b.origin?b.origin:"data:"!=c.protocol&&c.host?c.protocol+"//"+c.host:c.href;a=t[a]=c}}(b="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,b=a.length-10,b=0<=b&&a.indexOf(".localhost",b)==b);return b}function v(a,b){var c;c=void 0===c?"source":c;q().assert(null!=a,"%s %s must be available",b,c);var d=a;q().assert(u(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,d)};function w(a){if(a.nodeType){var b=(a.ownerDocument||a).defaultView;if(b=b!=(b.__AMP_TOP||b)&&x(b,"url-replace")?y(b,"url-replace"):null)return b}return z(a,"url-replace")}function B(a,b){a=a.__AMP_TOP||a;return y(a,b)}
function C(a){var b,c=D,d=a=a.__AMP_TOP||a,e=a,g=c,h=E(d),f=h.userNotificationManager;f||(f=h.userNotificationManager={obj:null,promise:null,resolve:null,context:null,ctor:null});f.ctor||f.obj||(f.ctor=g,f.context=e,f.resolve&&y(d,"userNotificationManager"));b&&y(a,"userNotificationManager")}function z(a,b){a=F(a);a=G(a);return y(a,b)}function F(a){return a.nodeType?B((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function G(a){a=F(a);return a.isSingleDoc()?a.win:a}
function y(a,b){x(a,b);var c=E(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function H(a,b){var c=I(a,b);if(c)return c;var d,e=new Promise(function(a){d=a});E(a)[b]={obj:null,promise:e,resolve:d,context:null,ctor:null};return e}function I(a,b){var c=E(a)[b];if(c){if(c.promise)return c.promise;y(a,b);return c.promise=Promise.resolve(c.obj)}return null}function E(a){var b=a.services;b||(b=a.services={});return b}
function x(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)};function J(a){return a.ampExtendedElements?!!a.ampExtendedElements["amp-analytics"]:!1}function K(a){return L(a).then(function(a){return q().assert(a,"Service %s was requested to be provided through %s, but %s is not loaded in the current page. To fix this problem load the JavaScript file for %s in this page.","cid","amp-analytics","amp-analytics","amp-analytics")})}
function L(a){var b=F(a),c=I(G(a),"cid");return c?c:Promise.resolve().then(function(){return J(b.win)?H(G(a),"cid"):b.whenBodyAvailable().then(function(){return J(b.win)?H(G(a),"cid"):null})})};var M,N="Webkit webkit Moz moz ms O o".split(" ");function O(a){return"loading"!=a.readyState&&"uninitialized"!=a.readyState}function P(a,b){var c=O,d=c(a);if(d)b(a);else{var e=function(){c(a)&&(d||(d=!0,b(a)),a.removeEventListener("readystatechange",e))};a.addEventListener("readystatechange",e)}}function Q(a){return new Promise(function(b){P(a,b)})};function R(a){AMP.BaseElement.call(this,a);this.h=this.i=this.B=null}l(R,AMP.BaseElement);k=R.prototype;k.isAlwaysFixed=function(){return!0};
k.buildCallback=function(){var a=this,b=this.getAmpDoc();this.B=w(b);this.h=H(G(b),"storage");this.i||(C(window),this.i=B(window,"userNotificationManager"));this.g=this.j=null;this.l=new Promise(function(b){a.g=b});this.b=q().assert(this.element.id,"amp-user-notification should have an id.");this.A="amp-user-notification:"+this.b;(this.c=this.element.getAttribute("data-show-if-href"))&&v(this.c,this.element);(this.a=this.element.getAttribute("data-dismiss-href"))&&v(this.a,this.element);var c=this.element.getAttribute("role");
c||this.element.setAttribute("role","alert");var d=this.element.getAttribute("data-persist-dismissal");this.u="false"!=d&&"no"!=d;this.i.registerUserNotification(this.b,this);this.registerAction("dismiss",this.dismiss.bind(this))};
function S(a,b){var c=a.c;return a.B.expandAsync(c).then(function(c){var e;e={elementId:a.b,ampUserId:b};var d=[],h;for(h in e){var f=e[h];if(null!=f)if(Array.isArray(f))for(var A=0;A<f.length;A++){var U=f[A];d.push(encodeURIComponent(h)+"="+encodeURIComponent(U))}else d.push(encodeURIComponent(h)+"="+encodeURIComponent(f))}e=d.join("&");d=c;e?(d=d.split("#",2),h=d[0].split("?",2),e=h[0]+(h[1]?"?"+h[1]+"&"+e:"?"+e),e+=d[1]?"#"+d[1]:""):e=d;return e})}
k.C=function(a){var b=this;this.j=a;return S(this,a).then(function(a){var c={credentials:"include",requireAmpResponseSourceOrigin:!1};return B(b.win,"xhr").fetchJson(a,c).then(function(a){return a.json()})})};k.D=function(a){q().assert("boolean"==typeof a.showNotification,'`showNotification` should be a boolean. Got "%s" which is of type %s.',a.showNotification,typeof a.showNotification);a.showNotification||this.g();return Promise.resolve(a.showNotification)};
function T(a){return K(a.element).then(function(b){return b.get({scope:"amp-user-notification",createCookieIfNotPresent:!0},Promise.resolve(),a.l)})}k.shouldShow=function(){var a=this;return this.isDismissed().then(function(b){return b?!1:a.c?T(a).then(a.C.bind(a)).then(a.D.bind(a)):!0})};
k.show=function(){var a=this.element,b;b=a.style;M||(M=Object.create(null));var c=M.display;if(!c){c="display";if(void 0===b.display){var d="D"+"display".slice(1);b:{for(var e=0;e<N.length;e++){var g=N[e]+d;if(void 0!==b[g]){d=g;break b}}d=""}void 0!==b[d]&&(c=d)}M.display=c}b=c;b&&(a.style[b]="");this.element.classList.add("amp-active");this.getViewport().addToFixedLayer(this.element);return this.l};
k.isDismissed=function(){var a=this;return this.u?this.h.then(function(b){return b.get(a.A)}).then(function(a){return!!a},function(a){var b;if(p.dev)b=p.dev;else throw Error("failed to call initLogConstructor");b.error("amp-user-notification","Failed to read storage",a);return!1}):Promise.resolve(!1)};k.activate=function(){this.dismiss()};
k.dismiss=function(){var a=this;this.element.classList.remove("amp-active");this.element.classList.add("amp-hidden");this.g();this.getViewport().removeFromFixedLayer(this.element);this.u&&this.h.then(function(b){b.set(a.A,!0)});this.a&&B(this.win,"xhr").fetchJson(this.a,{method:"POST",credentials:"include",requireAmpResponseSourceOrigin:!1,body:{elementId:this.b,ampUserId:this.j}})};
function D(a){this.win=a;this.w=Object.create(null);this.f=Object.create(null);this.F=z(this.win.document,"viewer");this.m=Q(this.win.document);this.s=this.o=Promise.all([this.F.whenFirstVisible(),this.m])}D.prototype.get=function(a){var b=this;this.o.then(function(){null==b.win.document.getElementById(a)&&q().warn("amp-user-notification","Did not find amp-user-notification element "+a+".")});return V(this,a).promise};D.prototype.getNotification=function(a){var b=this;return this.m.then(function(){return b.w[a]})};
D.prototype.registerUserNotification=function(a,b){this.w[a]=b;var c=V(this,a);return this.s=this.s.then(function(){return b.shouldShow().then(function(a){if(a)return b.show()})}).then(c.resolve.bind(this,b)).catch(n.bind(null,"Notification service failed amp-user-notification",a))};function V(a,b){if(a.f[b])return a.f[b];var c,d=new Promise(function(a){c=a});return a.f[b]={promise:d,resolve:c}}C(AMP.win);AMP.registerElement("amp-user-notification",R,"amp-user-notification{position:fixed!important;bottom:0;left:0;overflow:hidden!important;visibility:hidden;background:hsla(0,0%,100%,.7);z-index:1000;width:100%}amp-user-notification.amp-active{visibility:visible}amp-user-notification.amp-hidden{visibility:hidden}\n/*# sourceURL=/extensions/amp-user-notification/0.1/amp-user-notification.css*/");
})});
//# sourceMappingURL=amp-user-notification-0.1.js.map

