(self.AMP=self.AMP||[]).push({n:"amp-lightbox",v:"123456789",f:(function(AMP){var e;function h(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(b,d);f&&Object.defineProperty(a,d,f)}else a[d]=b[d]};Date.now();self.log=self.log||{user:null,dev:null};function l(a,b){a=a.__AMP_TOP||a;return m(a,b)}function n(a){a=p(a);a=p(a);a=a.isSingleDoc()?a.win:a;return m(a,"history")}function p(a){return a.nodeType?l((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function m(a,b){var c=a.services;c||(c=a.services={});var d=c;a=d[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};function q(){this.f=null}e=q.prototype;e.add=function(a){var b=this;this.f||(this.f=[]);this.f.push(a);return function(){b.remove(a)}};e.remove=function(a){this.f&&(a=this.f.indexOf(a),-1<a&&this.f.splice(a,1))};e.removeAll=function(){this.f&&(this.f.length=0)};e.fire=function(a){if(this.f)for(var b=this.f,c=0;c<b.length;c++)(0,b[c])(a)};e.getHandlerCount=function(){return this.f?this.f.length:0};var r,t="Webkit webkit Moz moz ms O o".split(" ");function u(a,b,c){var d;var f=a.style;if(2>b.length||0!=b.lastIndexOf("--",0)){r||(r=Object.create(null));var g=r[b];if(!g){g=b;if(void 0===f[b]){var k=b.charAt(0).toUpperCase()+b.slice(1);b:{for(var v=0;v<t.length;v++){var D=t[v]+k;if(void 0!==f[D]){k=D;break b}}k=""}void 0!==f[k]&&(g=k)}r[b]=g}b=g}b&&(a.style[b]=d?c+d:c)}function w(a){var b={display:"",opacity:0,transition:"opacity 0.1s ease-in"},c;for(c in b)u(a,c,b[c])};function x(a,b,c){var d=this;this.fa=l(a,"timer");this.ja=b;this.ia=c||0;this.w=-1;this.O=0;this.V=!1;this.ga=function(){return d.K()}}x.prototype.isPending=function(){return-1!=this.w};x.prototype.schedule=function(a){var b=a||this.ia;this.V&&10>b&&(b=10);var c=Date.now()+b;return!this.isPending()||-10>c-this.O?(this.cancel(),this.O=c,this.w=this.fa.delay(this.ga,b),!0):!1};x.prototype.K=function(){this.w=-1;this.O=0;this.V=!0;this.ja();this.V=!1};
x.prototype.cancel=function(){this.isPending()&&(this.fa.cancel(this.w),this.w=-1)};function y(a,b,c,d){this.type=a;this.data=b;this.time=c;this.event=d}
function z(a,b){this.h=a;this.b=[];this.C=[];this.g=[];this.a=[];this.c=null;this.pa=b;this.M=!1;this.K=new x(a.ownerDocument.defaultView,this.ba.bind(this));this.da=new q;this.P=Object.create(null);this.aa=this.na.bind(this);this.Z=this.la.bind(this);this.$=this.ma.bind(this);this.Y=this.ka.bind(this);this.h.addEventListener("touchstart",this.aa);this.h.addEventListener("touchend",this.Z);this.h.addEventListener("touchmove",this.$);this.h.addEventListener("touchcancel",this.Y);this.R=!1}
function A(a){var b=a.__AMP_Gestures;b||(b=new z(a,!1),a.__AMP_Gestures=b);return b}e=z.prototype;e.cleanup=function(){this.h.removeEventListener("touchstart",this.aa);this.h.removeEventListener("touchend",this.Z);this.h.removeEventListener("touchmove",this.$);this.h.removeEventListener("touchcancel",this.Y);delete this.h.__AMP_Gestures;this.K.cancel()};e.onGesture=function(a,b){var c=new a(this),d=c.getType(),f=this.P[d];f||(this.b.push(c),f=new q,this.P[d]=f);return f.add(b)};e.onPointerDown=function(a){return this.da.add(a)};
e.na=function(a){var b=Date.now();this.M=!1;this.da.fire(a);for(var c=0;c<this.b.length;c++)if(!this.g[c]&&(this.a[c]&&this.a[c]<b&&B(this,c),this.b[c].onTouchStart(a))){var d=c;this.C[d]=!0;this.a[d]=0}C(this,a)};e.ma=function(a){for(var b=Date.now(),c=0;c<this.b.length;c++)this.C[c]&&(this.a[c]&&this.a[c]<b?B(this,c):this.b[c].onTouchMove(a)||B(this,c));C(this,a)};
e.la=function(a){for(var b=Date.now(),c=0;c<this.b.length;c++)this.C[c]&&(this.a[c]&&this.a[c]<b?B(this,c):(this.b[c].onTouchEnd(a),(!this.a[c]||this.a[c]<b)&&B(this,c)));C(this,a)};e.ka=function(a){for(var b=0;b<this.b.length;b++){var c=b;this.g[c]=0;B(this,c)}C(this,a)};function C(a,b){var c=!!a.c||a.M;a.M=!1;if(!c)for(var d=Date.now(),f=0;f<a.b.length;f++)if(a.g[f]||a.a[f]&&a.a[f]>=d){c=!0;break}c&&(b.stopPropagation(),a.pa||b.preventDefault());a.R&&(a.R=!1,a.ba())}
e.ba=function(){for(var a=Date.now(),b=-1,c=0;c<this.b.length;c++)if(!this.g[c])this.a[c]&&this.a[c]<a&&B(this,c);else if(-1==b||this.g[c]>this.g[b])b=c;if(-1!=b){for(var d=0,c=0;c<this.b.length;c++)!this.g[c]&&this.C[c]&&(d=Math.max(d,this.a[c]-a));if(2>d){for(var a=b,c=this.b[a],f=0;f<this.b.length;f++)if(f!=a){var g=f;this.g[g]=0;B(this,g)}this.g[a]=0;this.a[a]=0;this.c=c;c.acceptStart()}else this.K.schedule(d)}};function B(a,b){a.C[b]=!1;a.a[b]=0;a.g[b]||a.b[b].acceptCancel()}
function E(a,b){this.qa=a;this.J=b}e=E.prototype;e.getType=function(){return this.qa};e.signalReady=function(a){var b=this.J;if(b.c)this.acceptCancel();else{for(var c=Date.now(),d=0;d<b.b.length;d++)b.b[d]==this&&(b.g[d]=c+a,b.a[d]=0);b.R=!0}};e.signalPending=function(a){var b=this.J;if(b.c)this.acceptCancel();else for(var c=Date.now(),d=0;d<b.b.length;d++)b.b[d]==this&&(b.a[d]=c+a)};e.signalEnd=function(){var a=this.J;a.c==this&&(a.c=null,a.M=!0)};
e.signalEmit=function(a,b){var c=this.J.P[this.getType()];c&&c.fire(new y(this.getType(),a,Date.now(),b))};e.acceptStart=function(){};e.acceptCancel=function(){};e.onTouchStart=function(){return!1};e.onTouchMove=function(){return!1};e.onTouchEnd=function(){};function F(a,b,c){1>b&&(b=1);var d=a/b,f=.5+Math.min(b/33.34,.5);return d*f+c*(1-f)};function G(a,b,c,d){E.call(this,a,b);this.H=c;this.L=d;this.c=!1;this.o=this.m=this.S=this.I=this.ea=this.U=this.T=this.u=this.s=this.B=this.A=0}h(G,E);e=G.prototype;e.onTouchStart=function(a){a=a.touches;if(!a||1!=a.length)return!1;this.ea=Date.now();this.A=a[0].clientX;this.B=a[0].clientY;return!0};
e.onTouchMove=function(a){var b=a.changedTouches||a.touches;if(b&&1==b.length){var c=b[0].clientX,b=b[0].clientY;this.s=c;this.u=b;if(this.c)H(this,!1,!1,a);else if(a=Math.abs(c-this.A),c=Math.abs(b-this.B),this.H&&this.L)(8<=a||8<=c)&&this.signalReady(-10);else if(this.H)if(8<=a&&a>c)this.signalReady(-10);else{if(8<=c)return!1}else if(this.L)if(8<=c&&c>a)this.signalReady(-10);else{if(8<=a)return!1}else return!1}return!0};e.onTouchEnd=function(a){this.c&&(this.c=!1,H(this,!1,!0,a),this.signalEnd())};
e.acceptStart=function(){this.c=!0;this.T=this.A;this.U=this.B;this.S=this.ea;this.A=this.s;this.B=this.u;H(this,!0,!1,null)};e.acceptCancel=function(){this.c=!1};function H(a,b,c,d){a.I=Date.now();var f=a.I-a.S;if(!c&&4<f||c&&16<f)a.m=F(a.s-a.T,f,a.m),a.o=F(a.u-a.U,f,a.o),a.m=1E-4<Math.abs(a.m)?a.m:0,a.o=1E-4<Math.abs(a.o)?a.o:0,a.T=a.s,a.U=a.u,a.S=a.I;a.signalEmit({first:b,last:c,time:a.I,deltaX:a.H?a.s-a.A:0,deltaY:a.L?a.u-a.B:0,velocityX:a.H?a.m:0,velocityY:a.L?a.o:0},d)}
function I(a){G.call(this,"swipe-xy",a,!0,!0)}h(I,G);function J(a){AMP.BaseElement.call(this,a);this.G=this.j=this.X=null;this.N=-1;this.D=!1;this.F=null;this.i=!1;this.ca=this.l=0;this.W=null}h(J,AMP.BaseElement);e=J.prototype;e.isLayoutSupported=function(a){return"nodisplay"==a};
function K(a){if(!a.j&&(a.i=a.element.hasAttribute("scrollable"),a.G=a.getRealChildren(),a.j=a.element.ownerDocument.createElement("div"),a.i||a.applyFillContent(a.j),a.element.appendChild(a.j),a.G.forEach(function(b){a.i&&a.setAsOwner(b);a.j.appendChild(b)}),a.i&&a.element.addEventListener("scroll",a.oa.bind(a)),a.registerAction("open",a.activate.bind(a)),a.registerAction("close",a.close.bind(a)),!a.i)){var b=A(a.element);b.onGesture(I,function(){})}}e.layoutCallback=function(){return Promise.resolve()};
e.activate=function(){var a=this;this.D||(K(this),this.F=this.ha.bind(this),this.win.document.documentElement.addEventListener("keydown",this.F),this.getViewport().enterLightboxMode(this.element).then(function(){return L(a)}))};
function L(a){a.i&&u(a.element,"webkitOverflowScrolling","touch");a.mutateElement(function(){w(a.element);l(a.win,"vsync").mutate(function(){u(a.element,"opacity","")})}).then(function(){var b=a.j;a.i?M(a,a.l,a.l):a.updateInViewport(b,!0);a.scheduleLayout(b);a.scheduleResume(b)});n(a.getAmpDoc()).push(a.close.bind(a)).then(function(b){a.N=b});a.D=!0}e.ha=function(a){27==a.keyCode&&this.close()};
e.close=function(){var a=this;this.D&&(this.i&&u(this.element,"webkitOverflowScrolling",""),this.getViewport().leaveLightboxMode(this.element).then(function(){a.collapse();-1!=a.N&&n(a.getAmpDoc()).pop(a.N);a.win.document.documentElement.removeEventListener("keydown",a.F);a.F=null;a.schedulePause(a.j);a.D=!1}))};e.oa=function(){var a=this.element.scrollTop;this.l=a;null===this.W&&N(this,a)};
function N(a,b){a.W=l(a.win,"timer").delay(function(){if(30>Math.abs(b-a.l)){a.W=null;var c=a.l;M(a,c,a.ca);a.ca=c;a.l=c}else N(a,a.l)},100)}function M(a,b,c){var d=[];O(a,b,function(b){d.push(b);a.updateInViewport(b,!0)});c!=b&&O(a,c,function(b){d.includes(b)||a.updateInViewport(b,!1)})}function O(a,b,c){a.X||(a.X={width:a.element.clientWidth,height:a.element.clientHeight});for(var d=a.X.height,f=0;f<a.G.length;f++){var g=a.G[f];g.offsetTop+g.offsetHeight>=b&&g.offsetTop<=b+d&&c(g)}}
AMP.registerElement("amp-lightbox",J,"amp-lightbox{display:none;position:fixed!important;z-index:1000;top:0!important;left:0!important;bottom:0!important;right:0!important}amp-lightbox[scrollable]{overflow-y:auto!important;overflow-x:hidden!important}\n/*# sourceURL=/extensions/amp-lightbox/0.1/amp-lightbox.css*/");
})});
//# sourceMappingURL=amp-lightbox-0.1.js.map

