(self.AMP=self.AMP||[]).push({n:"amp-sort",v:"123456789",f:(function(AMP){function g(a,c){function b(){}b.prototype=c.prototype;a.prototype=new b;a.prototype.constructor=a;for(var d in c)if(Object.defineProperties){var f=Object.getOwnPropertyDescriptor(c,d);f&&Object.defineProperty(a,d,f)}else a[d]=c[d]};var h=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function k(a){if(!a)return[];for(var c=Array(a.length),b=0;b<a.length;b++)c[b]=a[b];return c};Date.now();self.log=self.log||{user:null,dev:null};var p=self.log;function q(){if(p.user)return p.user;throw Error("failed to call initLogConstructor");};var r=null;Promise.resolve();
function t(a){var c;if(!r){r=Object.create(null);if(a.AMP_CONFIG)for(c in a.AMP_CONFIG){var b=a.AMP_CONFIG[c];"number"===typeof b&&0<=b&&1>=b&&(r[c]=Math.random()<b)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&(c=a.AMP_CONFIG["allow-doc-opt-in"],b=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(var b=b.getAttribute("content").split(","),d=0;d<b.length;d++)-1!=c.indexOf(b[d])&&(r[b[d]]=!0);Object.assign(r,u(a));
if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){c=a.AMP_CONFIG["allow-url-opt-in"];b=a.location.originalHash||a.location.hash;a=Object.create(null);if(b)for(var f;f=h.exec(b);)d=decodeURIComponent(f[1]).trim(),f=f[2]?decodeURIComponent(f[2]).trim():"",a[d]=f;for(b=0;b<c.length;b++)d=a["e-"+c[b]],"1"==d&&(r[c[b]]=!0),"0"==d&&(r[c[b]]=!1)}}c=r;var e=c;return!!e["amp-sort"]}
function u(a){a:{var c;b:{try{c=a.document.cookie;break b}catch(l){}c=void 0}if(a=c)for(a=a.split(";"),c=0;c<a.length;c++){var b=a[c].trim(),d=b.indexOf("=");if(-1!=d&&"AMP_EXP"==decodeURIComponent(b.substring(0,d).trim())){a=decodeURIComponent(b.substring(d+1).trim());break a}}a=null}var f=a,e=f?f.split(/\s*,\s*/g):[];a=Object.create(null);for(c=0;c<e.length;c++)0!=e[c].length&&("-"==e[c][0]?a[e[c].substr(1)]=!1:a[e[c]]=!0);return a};function v(a){AMP.BaseElement.call(this,a);this.a=null}g(v,AMP.BaseElement);v.prototype.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"container"};
v.prototype.buildCallback=function(){var a=this;AMP.toggleExperiment("amp-sort",!0);q().assert(t(this.win),"Experiment amp-sort disabled");this.registerAction("sort",function(c){var b=c.args,d=c.source.cellIndex;b&&(void 0!==b.sortBy?a.element.setAttribute("sort-by",b.sortBy):q().error("amp-sort","<amp-sort> elements must have a `sort-by` attribute.",a.element),void 0!==b.sortDirecion&&a.element.setAttribute("sort-direction",b.sortDirecion),void 0!==b.sortedDirecion&&a.element.setAttribute("sorted-direction",
b.sortDirecion),void 0!==b.valueType&&a.element.setAttribute("value-type",b.valueType));w(a,d)})};v.prototype.mutatedAttributesCallback=function(a){(a["sort-by"]||a["sort-direction"])&&w(this)};
function w(a,c){var b=a.element.getAttribute("sort-by"),d=a.element.getAttribute("value-type")||"string",f=a.element.getAttribute("sorted-direction");a.a=f||null;var e=a.element.getAttribute("sort-direction")||("string"==d?"asc":"desc");null==a.a&&"toggle"==e&&(e="string"==d?"asc":"desc");"toggle|asc"==e?e=null==a.a?"asc":"toggle":"toggle|desc"==e&&(e=null==a.a?"desc":"toggle");"toggle"==e&&(e="asc"==a.a?"desc":"asc");0==e&&q().error("amp-sort","Invalid value for `sort-direction` attribute.",a.element);
var l="asc"==e?"ascending":"descending",m=k(a.element.querySelectorAll("["+b+"]")),n=x(a,b,e,d),y=m.sort(n);y.forEach(function(a){a.parentNode.hasAttribute("aria-live")||a.parentNode.setAttribute("aria-live","polite");if("TR"==a.nodeName){for(var b=a.closest("table").querySelector("thead").querySelector("tr").children,d=b.length;d--;)b[d].removeAttribute("aria-sort");b[c].setAttribute("aria-sort",l)}a.parentNode.appendChild(a)});a.element.setAttribute("sorted","");a.element.setAttribute("sorted-by",
b);a.element.setAttribute("sorted-direction",e)}function x(a,c,b,d){return function(f,e){if("desc"==b){var l=f;f=e;e=l}var m=f.getAttribute(""+c),n=e.getAttribute(""+c);if("string"==d)return m.localeCompare(n);if("number"==d)return Number(m)-Number(n);q().error("amp-sort","Invalid value for `value-type` attribute.",a.element)}}AMP.registerElement("amp-sort",v,CSS);
})});
//# sourceMappingURL=amp-sort-0.1.js.map

