(function(){var p=(self.AMP_CONFIG||{}).cdnUrl||"https://cdn.ampproject.org";var q=self.AMP_CONFIG["cache-service-worker-blacklist"]||[],r=self.AMP_CONFIG.v,t=r.substr(0,2),u,v=Object.create(null),w=Object.create(null),x=Object.create(null),y=new RegExp("^"+p.replace(/\./g,"\\.")+"(?:/rtv/(\\d{2}\\d{13,}))?(/v0(?:/(?!experiments|validator).+)?\\.js)$");function z(a){var b=y.exec(a);return b?{explicitRtv:b[1]||"",pathname:b[2],rtv:b[1]||r}:null}
function A(a,b){var c=a.url,d=z(c);if(!d||d.explicitRtv!==b){d=Request;var e=z(c);if(e){var h=e.explicitRtv,e=e.pathname;b=h?c.replace(h,b):c.replace(e,"/rtv/"+b+e)}else b=c;a=new d(b,{referer:p+"/sw.js",headers:a.headers,method:a.method,mode:a.mode,credentials:a.credentials,cache:a.cache,redirect:a.redirect,integrity:a.integrity})}return a}function B(a){var b=Date.now(),c=w[a]||0;c<b-6E4&&(c=w[a]=b);return a+c}
function C(a,b){var c=b.url;return x[c]?x[c].then(function(){return a.match(b)}):x[c]=a.match(b).then(function(d){return d&&!D(d)?(delete x[c],d):fetch(b).then(function(d){delete x[c];if(!d.ok)throw Error("fetching "+c+" failed with statusCode "+(d.status+"."));a.put(b,d.clone());return d},function(a){delete x[c];throw a;})})}
function D(a){var b=a.headers;if(!b.has("date")||!b.has("cache-control"))return!0;var c=/max-age=(\d+)/i.exec(b.get("cache-control"));a=b.get("date");var d=c?1E3*c[1]:-Infinity;return Date.now()>=Number(new Date(a))+d}function E(a){var b=new Request(p+"/diversions");return C(a,b).then(function(a){return a.json()}).then(function(a){return Array.isArray(a)?a:null},function(){return null})}var F=self.caches.open("cdn-js").then(function(a){u=a});
function G(a,b,c){var d=u;return C(d,a).then(function(e){E(d).then(function(e){H(d,b,c,e);if(e)for(var m=new Promise(function(a){setTimeout(a,1E4)}),g={i:0};g.i<e.length;g={i:g.i},g.i++)m=m.then(function(b){return function(){var c=A(a,e[b.i]);return C(d,c)}}(g))});return e})}
function H(a,b,c,d){a.keys().then(function(e){for(var h=b.substr(0,2),m=0;m<e.length;m++){var g=e[m],l=z(g.url);if(l&&b!==l.rtv){var n=l.rtv.substr(0,2),k=t===n;if(k){if(t!==h)continue;if(c!==l.pathname)continue}else if(!d||d.includes(l.rtv))continue;a.delete(g)}}})}
function I(a,b){var c=u,d=a.substr(0,2);return d!==t?Promise.resolve(a):c.keys().then(function(c){for(var e={},m=a,g=0,l=0;l<c.length;l++){var n=z(c[l].url);if(n){var k=n,n=k.pathname,k=k.rtv,f;if(f=d===k.substr(0,2))f=k.substr(2),f=!(-1<q.indexOf(f));f&&(f=e[k]||0,n.includes("/",1)?b===n?f+=2:f++:f+=5,e[k]=f,f>g&&(m=k,g=f))}}return m})}
function J(a,b){var c=z(a.url);if(!b||!c)return null;var d=b,e=c.pathname,h=c.rtv;a=A(a,h);return F.then(function(){return v[d]?v[d]:v[d]=I(h,e)}).then(function(b){var c=A(a,b);return u.match(c).then(function(d){return d?(b!==h&&h==r&&G(a,h,e),d):G(c,b,e)})}).catch(function(a){Promise.reject(a);throw a;})}self.addEventListener("install",function(a){a.waitUntil(F);a.registerForeignFetch&&a.registerForeignFetch({scopes:[self.registration.scope],origins:["*"]})});
self.addEventListener("fetch",function(a){var b=J(a.request,a.clientId);b&&a.respondWith(b)});self.addEventListener("foreignfetch",function(a){var b=J(a.request,a.clientId||B(a.request.referrer));b&&a.respondWith(b.then(function(b){return{response:b,origin:a.origin}}))});})();
//# sourceMappingURL=cache-service-worker-0.1.js.map

